import type { Cafe24OperationMetadata } from './types.js';

/**
 * Cafe24 `category` resource metadata.
 *
 * G-1-remaining (plan `cafe24-backlog-residual.md` §G-1-remaining, 2026-07-05):
 * field-set 을 공식 docs 카탈로그(`spec/conventions/cafe24-api-catalog/category/*.md`
 * 의 각 operation `요청 파라미터` 표)와 **전량 미러**했다. 필드명은 docs Parameter 를
 * 그대로 사용한다 — 핸들러가 field key 를 query/body 파라미터명으로 그대로 전송하므로
 * (`cafe24.handler.ts` buildRequest), docs 명이 아닌 alias 는 Cafe24 가 인식하지 못한다.
 *
 * 규칙:
 * - `offset`/`limit` 은 field 로 넣지 않는다 — paginated op 는 핸들러 pagination 층이 주입.
 * - `requiredFields` 는 기존 계약을 보존하되 docs 로 schema 가 바뀐 필드는 신규 fields 에
 *   실재하는 것만 남긴다 (metadata.spec 의 subset 불변식).
 * - `category_products_list` 는 공식 카탈로그에 대응 문서가 없어(별도 endpoint) 기존
 *   field-set 을 그대로 유지한다.
 */
export const categoryOperations: Cafe24OperationMetadata[] = [
  {
    id: 'category_list',
    description: 'List product categories in the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      category_depth: {
        type: 'number',
        location: 'query',
        description: 'Category depth to search (1-4)',
      },
      category_no: {
        type: 'string',
        location: 'query',
        description: 'Category number(s), comma-separated multi-search',
      },
      parent_category_no: {
        type: 'number',
        location: 'query',
        description: 'Parent category number (1 = top-level)',
      },
      category_name: {
        type: 'string',
        location: 'query',
        description: 'Search by category name (partial)',
      },
      use_main: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Main-category display (T=on, F=off)',
      },
      use_display: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Display status (T=on, F=off)',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'category_get',
    description: 'Get a single category by category_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/{category_no}',
    requiredFields: ['category_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      category_no: {
        type: 'number',
        location: 'path',
        description: 'Category number',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'category_create',
    description: 'Create a new category.',
    scopeType: 'write',
    method: 'POST',
    path: 'categories',
    requiredFields: ['category_name'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      parent_category_no: {
        type: 'number',
        location: 'body',
        description: 'Parent category number',
      },
      category_name: {
        type: 'string',
        location: 'body',
        description: 'Category name',
      },
      display_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'P', 'M', 'F'],
        description: 'Storefront display (A=PC+mobile, P=PC, M=mobile, F=none)',
      },
      use_main: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Main-category display (T=on, F=off)',
      },
      use_display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Display status (T=on, F=off)',
      },
      soldout_product_display: {
        type: 'enum',
        location: 'body',
        enum: ['B', 'N'],
        description: 'Soldout placement (B=back, N=no order)',
      },
      sub_category_product_display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Include sub-category products (T=yes, F=no)',
      },
      hashtag_product_display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Curation hashtag display (T=yes, F=no)',
      },
      hash_tags: {
        type: 'array',
        location: 'body',
        description: 'Curation hashtag list',
      },
      product_display_scope: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'G'],
        description: 'Display scope (A=all, G=per-area)',
      },
      product_display_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'U', 'M'],
        description: 'Display method (A=auto, U=manual, M=auto+manual)',
      },
      product_display_key: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'R', 'U', 'N', 'P', 'S', 'C', 'L'],
        description: 'Sort key (A/R/U/N/P/S/C/L)',
      },
      product_display_sort: {
        type: 'enum',
        location: 'body',
        enum: ['D', 'A'],
        description: 'Sort order (D=desc, A=asc)',
      },
      product_display_period: {
        type: 'enum',
        location: 'body',
        enum: ['W', '1D', '3D', '7D', '15D', '1M', '3M', '6M'],
        description: 'Aggregation period for S/C keys',
      },
      normal_product_display_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'U', 'M'],
        description: 'Normal-area display method (A=auto, U=manual, M=both)',
      },
      normal_product_display_key: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'R', 'U', 'N', 'P', 'S', 'C', 'L'],
        description: 'Normal-area sort key (A/R/U/N/P/S/C/L)',
      },
      normal_product_display_sort: {
        type: 'enum',
        location: 'body',
        enum: ['D', 'A'],
        description: 'Normal-area sort order (D=desc, A=asc)',
      },
      normal_product_display_period: {
        type: 'enum',
        location: 'body',
        enum: ['W', '1D', '3D', '7D', '15D', '1M', '3M', '6M'],
        description: 'Normal-area aggregation period for S/C keys',
      },
      recommend_product_display_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'U', 'M'],
        description: 'Recommend-area display method (A=auto, U=manual, M=both)',
      },
      recommend_product_display_key: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'R', 'U', 'N', 'P', 'S', 'C', 'L'],
        description: 'Recommend-area sort key (A/R/U/N/P/S/C/L)',
      },
      recommend_product_display_sort: {
        type: 'enum',
        location: 'body',
        enum: ['D', 'A'],
        description: 'Recommend-area sort order (D=desc, A=asc)',
      },
      recommend_product_display_period: {
        type: 'enum',
        location: 'body',
        enum: ['W', '1D', '3D', '7D', '15D', '1M', '3M', '6M'],
        description: 'Recommend-area aggregation period for S/C keys',
      },
      new_product_display_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'U', 'M'],
        description: 'New-area display method (A=auto, U=manual, M=both)',
      },
      new_product_display_key: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'R', 'U', 'N', 'P', 'S', 'C', 'L'],
        description: 'New-area sort key (A/R/U/N/P/S/C/L)',
      },
      new_product_display_sort: {
        type: 'enum',
        location: 'body',
        enum: ['D', 'A'],
        description: 'New-area sort order (D=desc, A=asc)',
      },
      new_product_display_period: {
        type: 'enum',
        location: 'body',
        enum: ['W', '1D', '3D', '7D', '15D', '1M', '3M', '6M'],
        description: 'New-area aggregation period for S/C keys',
      },
    },
    constraints: [
      {
        kind: 'impliesValue',
        if: 'product_display_scope',
        value: 'A',
        then: [
          'product_display_type',
          'product_display_key',
          'product_display_sort',
        ],
      },
      {
        kind: 'impliesValue',
        if: 'product_display_scope',
        value: 'G',
        then: [
          'normal_product_display_type',
          'normal_product_display_key',
          'normal_product_display_sort',
          'recommend_product_display_type',
          'recommend_product_display_key',
          'recommend_product_display_sort',
          'new_product_display_type',
          'new_product_display_key',
          'new_product_display_sort',
        ],
      },
    ],
    responseShape: 'single',
  },
  {
    id: 'category_update',
    description: 'Update a category.',
    scopeType: 'write',
    method: 'PUT',
    path: 'categories/{category_no}',
    requiredFields: ['category_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      category_no: {
        type: 'number',
        location: 'path',
        description: 'Category number',
      },
      category_name: {
        type: 'string',
        location: 'body',
        description: 'Category name',
      },
      display_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'P', 'M', 'F'],
        description: 'Storefront display (A=PC+mobile, P=PC, M=mobile, F=none)',
      },
      use_main: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Main-category display (T=on, F=off)',
      },
      use_display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Display status (T=on, F=off)',
      },
      soldout_product_display: {
        type: 'enum',
        location: 'body',
        enum: ['B', 'N'],
        description: 'Soldout placement (B=back, N=no order)',
      },
      sub_category_product_display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Include sub-category products (T=yes, F=no)',
      },
      hashtag_product_display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Curation hashtag display (T=yes, F=no)',
      },
      hash_tags: {
        type: 'array',
        location: 'body',
        description: 'Curation hashtag list',
      },
      product_display_scope: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'G'],
        description: 'Display scope (A=all, G=per-area)',
      },
      product_display_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'U', 'M'],
        description: 'Display method (A=auto, U=manual, M=auto+manual)',
      },
      product_display_key: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'R', 'U', 'N', 'P', 'S', 'C', 'L'],
        description: 'Sort key (A/R/U/N/P/S/C/L)',
      },
      product_display_sort: {
        type: 'enum',
        location: 'body',
        enum: ['D', 'A'],
        description: 'Sort order (D=desc, A=asc)',
      },
      product_display_period: {
        type: 'enum',
        location: 'body',
        enum: ['W', '1D', '3D', '7D', '15D', '1M', '3M', '6M'],
        description: 'Aggregation period for S/C keys',
      },
      normal_product_display_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'U', 'M'],
        description: 'Normal-area display method (A=auto, U=manual, M=both)',
      },
      normal_product_display_key: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'R', 'U', 'N', 'P', 'S', 'C', 'L'],
        description: 'Normal-area sort key (A/R/U/N/P/S/C/L)',
      },
      normal_product_display_sort: {
        type: 'enum',
        location: 'body',
        enum: ['D', 'A'],
        description: 'Normal-area sort order (D=desc, A=asc)',
      },
      normal_product_display_period: {
        type: 'enum',
        location: 'body',
        enum: ['W', '1D', '3D', '7D', '15D', '1M', '3M', '6M'],
        description: 'Normal-area aggregation period for S/C keys',
      },
      recommend_product_display_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'U', 'M'],
        description: 'Recommend-area display method (A=auto, U=manual, M=both)',
      },
      recommend_product_display_key: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'R', 'U', 'N', 'P', 'S', 'C', 'L'],
        description: 'Recommend-area sort key (A/R/U/N/P/S/C/L)',
      },
      recommend_product_display_sort: {
        type: 'enum',
        location: 'body',
        enum: ['D', 'A'],
        description: 'Recommend-area sort order (D=desc, A=asc)',
      },
      recommend_product_display_period: {
        type: 'enum',
        location: 'body',
        enum: ['W', '1D', '3D', '7D', '15D', '1M', '3M', '6M'],
        description: 'Recommend-area aggregation period for S/C keys',
      },
      new_product_display_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'U', 'M'],
        description: 'New-area display method (A=auto, U=manual, M=both)',
      },
      new_product_display_key: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'R', 'U', 'N', 'P', 'S', 'C', 'L'],
        description: 'New-area sort key (A/R/U/N/P/S/C/L)',
      },
      new_product_display_sort: {
        type: 'enum',
        location: 'body',
        enum: ['D', 'A'],
        description: 'New-area sort order (D=desc, A=asc)',
      },
      new_product_display_period: {
        type: 'enum',
        location: 'body',
        enum: ['W', '1D', '3D', '7D', '15D', '1M', '3M', '6M'],
        description: 'New-area aggregation period for S/C keys',
      },
    },
    constraints: [
      {
        kind: 'impliesValue',
        if: 'product_display_scope',
        value: 'A',
        then: [
          'product_display_type',
          'product_display_key',
          'product_display_sort',
        ],
      },
      {
        kind: 'impliesValue',
        if: 'product_display_scope',
        value: 'G',
        then: [
          'normal_product_display_type',
          'normal_product_display_key',
          'normal_product_display_sort',
          'recommend_product_display_type',
          'recommend_product_display_key',
          'recommend_product_display_sort',
          'new_product_display_type',
          'new_product_display_key',
          'new_product_display_sort',
        ],
      },
    ],
    responseShape: 'single',
  },
  {
    id: 'category_delete',
    description: 'Delete a category by category_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'categories/{category_no}',
    requiredFields: ['category_no'],
    fields: {
      category_no: {
        type: 'number',
        location: 'path',
        description: 'Category number',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'category_products_list',
    description: 'List products belonging to a category.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/{category_no}/products',
    requiredFields: ['category_no', 'display_group'],
    fields: {
      category_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
      display_group: {
        type: 'enum',
        location: 'query',
        enum: ['1', '2', '3'],
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  // Phase 6d — category baselines
  {
    id: 'category_count',
    description: 'Retrieve the count of product categories.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/count',
    requiredFields: [],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      category_depth: {
        type: 'number',
        location: 'query',
        description: 'Category depth to search (1-4)',
      },
      category_no: {
        type: 'string',
        location: 'query',
        description: 'Category number(s), comma-separated multi-search',
      },
      parent_category_no: {
        type: 'number',
        location: 'query',
        description: 'Parent category number (1 = top-level)',
      },
      category_name: {
        type: 'string',
        location: 'query',
        description: 'Search by category name (partial)',
      },
      use_main: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Main-category display (T=on, F=off)',
      },
      use_display: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Display status (T=on, F=off)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'mains_list',
    description: 'List the main categories pinned to the storefront home.',
    scopeType: 'read',
    method: 'GET',
    path: 'mains',
    requiredFields: [],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'autodisplay_list',
    description: 'List automated category display layouts.',
    scopeType: 'read',
    method: 'GET',
    path: 'autodisplay',
    requiredFields: [],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      display_no: {
        type: 'number',
        location: 'query',
        description: 'Auto-layout number',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  // Phase 7f — Category 완성 (decorationimages + seo + mains add/update/delete + autodisplay CUD)
  {
    id: 'category_decorationimages_get',
    description: 'Retrieve decoration image settings for a category.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/{category_no}/decorationimages',
    requiredFields: ['category_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      category_no: {
        type: 'number',
        location: 'path',
        description: 'Category number',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'category_decorationimages_update',
    description: 'Update decoration image settings for a category.',
    scopeType: 'write',
    method: 'PUT',
    path: 'categories/{category_no}/decorationimages',
    requiredFields: ['category_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      category_no: {
        type: 'number',
        location: 'path',
        description: 'Category number',
      },
      use_menu_image_pc: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'PC menu image use (T=on, F=off)',
      },
      menu_image_pc: {
        type: 'string',
        location: 'body',
        description: 'PC menu default image',
      },
      menu_over_image_pc: {
        type: 'string',
        location: 'body',
        description: 'PC menu over image',
      },
      use_top_image_pc: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'PC top image use (T=on, F=off)',
      },
      top_images_pc: {
        type: 'array',
        location: 'body',
        description: 'PC top images (max 3)',
      },
      use_title_image_pc: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'PC title image use (T=on, F=off)',
      },
      title_image_pc: {
        type: 'string',
        location: 'body',
        description: 'PC title image',
      },
      use_menu_image_mobile: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Mobile menu image use (T=on, F=off)',
      },
      menu_image_mobile: {
        type: 'string',
        location: 'body',
        description: 'Mobile menu default image',
      },
      use_top_image_mobile: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Mobile top image use (T=on, F=off)',
      },
      top_images_mobile: {
        type: 'array',
        location: 'body',
        description: 'Mobile top images (max 3)',
      },
      use_title_image_mobile: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Mobile title image use (T=on, F=off)',
      },
      title_image_mobile: {
        type: 'string',
        location: 'body',
        description: 'Mobile title image',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'category_seo_get',
    description: 'Retrieve SEO settings of a category.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/{category_no}/seo',
    requiredFields: ['category_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      category_no: {
        type: 'number',
        location: 'path',
        description: 'Category number',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'category_seo_update',
    description: 'Update SEO settings of a category (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'categories/{category_no}/seo',
    requiredFields: ['category_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      category_no: {
        type: 'number',
        location: 'path',
        description: 'Category number',
      },
      search_engine_exposure: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Search-engine exposure (T=on, F=off)',
      },
      meta_title: {
        type: 'string',
        location: 'body',
        description: 'Browser title',
      },
      meta_author: {
        type: 'string',
        location: 'body',
        description: 'Meta tag: Author',
      },
      meta_description: {
        type: 'string',
        location: 'body',
        description: 'Meta tag: Description',
      },
      meta_keywords: {
        type: 'string',
        location: 'body',
        description: 'Meta tag: Keywords',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'mains_add',
    description: 'Add a main category (pin to storefront home).',
    scopeType: 'write',
    method: 'POST',
    path: 'mains',
    requiredFields: ['group_name'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      group_name: {
        type: 'string',
        location: 'body',
        description: 'Main-category name (max 50 chars)',
      },
      soldout_sort_type: {
        type: 'enum',
        location: 'body',
        enum: ['B', 'N'],
        default: 'N',
        description: 'Soldout placement (B=back, N=no order)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'autodisplay_create',
    description: 'Create an auto-layout rule for a category.',
    scopeType: 'write',
    method: 'POST',
    path: 'autodisplay',
    requiredFields: [
      'category_no',
      'use_main',
      'display_group',
      'display_count',
      'use_reservation',
      'use_hashtag',
    ],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      use_main: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Main-category flag (T=main, F=product category)',
      },
      category_no: {
        type: 'number',
        location: 'body',
        description: 'Category number',
      },
      display_group: {
        type: 'number',
        location: 'body',
        description: 'Detailed product category',
      },
      display_count: {
        type: 'number',
        location: 'body',
        description: 'Max auto-displayed products (1-200)',
      },
      use_reservation: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Reserved display use (T=on, F=off)',
      },
      start_date: {
        type: 'string',
        location: 'body',
        description:
          'ISO8601 datetime (KST, UTC+9) — reserved display start. e.g. "2026-05-18T00:00:00+09:00".',
      },
      use_hashtag: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Hashtag use (T=on, F=off)',
      },
      hash_tags: {
        type: 'array',
        location: 'body',
        description: 'Hashtag list',
      },
      display_sort: {
        type: 'enum',
        location: 'body',
        enum: [
          'AOD',
          'AOA',
          'AVD',
          'AVA',
          'ARD',
          'ARA',
          'ACD',
          'AND',
          'APD',
          'APA',
          'RD',
          'RA',
          'UD',
          'UA',
          'NA',
          'ND',
          'PD',
          'PA',
          'SD',
          'SA',
          'CD',
          'CA',
          'LD',
          'LA',
        ],
        description: 'Sort order code',
      },
      timetable: {
        type: 'array',
        location: 'body',
        description: 'Update hours (max 24)',
      },
      period: {
        type: 'enum',
        location: 'body',
        enum: ['1', '3', '7', '30'],
        description: 'Aggregation period days (1/3/7/30)',
      },
      except_categories_scope: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'C'],
        default: 'A',
        description: 'Excluded-category scope (A=all, C=this only)',
      },
      except_categories: {
        type: 'array',
        location: 'body',
        description: 'Excluded categories',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'autodisplay_update',
    description: 'Update an auto-layout rule by display_no.',
    scopeType: 'write',
    method: 'PUT',
    // cafe24 docs placeholder: `{display_no}` (auto-layout rule id, not the
    // target category number — pre-2026-05-22 seed conflated these).
    path: 'autodisplay/{display_no}',
    requiredFields: ['display_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      display_no: {
        type: 'number',
        location: 'path',
        description: 'Auto-layout number',
      },
      display_count: {
        type: 'number',
        location: 'body',
        description: 'Max auto-displayed products (1-200)',
      },
      use_reservation: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Reserved display use (T=on, F=off)',
      },
      start_date: {
        type: 'string',
        location: 'body',
        description:
          'ISO8601 datetime (KST, UTC+9) — reserved display start. e.g. "2026-05-18T00:00:00+09:00".',
      },
      use_hashtag: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Hashtag use (T=on, F=off)',
      },
      hash_tags: {
        type: 'array',
        location: 'body',
        description: 'Hashtag list',
      },
      display_sort: {
        type: 'enum',
        location: 'body',
        enum: [
          'AOD',
          'AOA',
          'AVD',
          'AVA',
          'ARD',
          'ARA',
          'ACD',
          'AND',
          'APD',
          'APA',
          'RD',
          'RA',
          'UD',
          'UA',
          'NA',
          'ND',
          'PD',
          'PA',
          'SD',
          'SA',
          'CD',
          'CA',
          'LD',
          'LA',
        ],
        description: 'Sort order code',
      },
      timetable: {
        type: 'array',
        location: 'body',
        description: 'Update hours (max 24)',
      },
      period: {
        type: 'enum',
        location: 'body',
        enum: ['1', '3', '7', '30'],
        description: 'Aggregation period days (1/3/7/30)',
      },
      except_categories_scope: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'C'],
        description: 'Excluded-category scope (A=all, C=this only)',
      },
      except_categories: {
        type: 'array',
        location: 'body',
        description: 'Excluded categories',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'autodisplay_delete',
    description: 'Delete an auto-layout rule by display_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'autodisplay/{display_no}',
    requiredFields: ['display_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      display_no: {
        type: 'number',
        location: 'path',
        description: 'Auto-layout number',
      },
    },
    responseShape: 'single',
  },
];
