import type { Cafe24OperationMetadata } from './types.js';

export const categoryOperations: Cafe24OperationMetadata[] = [
  {
    id: 'category_list',
    description: 'List product categories in the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      parent_category_no: { type: 'number', location: 'query' },
      display: { type: 'enum', location: 'query', enum: ['T', 'F'] },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'category_get',
    description: 'Get a single category by category_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/{category_no}',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'category_create',
    description: 'Create a new category.',
    scopeType: 'write',
    method: 'POST',
    path: 'categories',
    requiredFields: ['category_name'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      parent_category_no: { type: 'number', location: 'body' },
      category_name: { type: 'string', location: 'body' },
      category_depth: { type: 'number', location: 'body' },
      display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'T',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'category_update',
    description: 'Update a category.',
    scopeType: 'write',
    method: 'PUT',
    path: 'categories/{category_no}',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      category_name: { type: 'string', location: 'body' },
      display: { type: 'enum', location: 'body', enum: ['T', 'F'] },
    },
    responseShape: 'single',
  },
  {
    id: 'category_delete',
    description: 'Delete a category by category_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'categories/{category_no}',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'category_products_list',
    description: 'List products belonging to a category.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/{category_no}/products',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
      display_group: {
        type: 'enum',
        location: 'query',
        enum: ['1', '2', '3'],
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  // Phase 6d — category baselines
  {
    id: 'category_count',
    description: 'Retrieve the count of product categories.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'mains_list',
    description: 'List the main categories pinned to the storefront home.',
    scopeType: 'read',
    method: 'GET',
    path: 'mains',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'autodisplay_list',
    description: 'List automated category display layouts.',
    scopeType: 'read',
    method: 'GET',
    path: 'autodisplay',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  // Phase 7f — Category 완성 (decorationimages + seo + mains add/update/delete + autodisplay CUD)
  {
    id: 'category_decorationimages_get',
    description: 'Retrieve decoration image settings for a category.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/{category_no}/decorationimages',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'category_decorationimages_update',
    description: 'Update decoration image settings for a category.',
    scopeType: 'write',
    method: 'PUT',
    path: 'categories/{category_no}/decorationimages',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'category_seo_get',
    description: 'Retrieve SEO settings of a category.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/{category_no}/seo',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'category_seo_update',
    description: 'Update SEO settings of a category (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'categories/{category_no}/seo',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      meta_title: { type: 'string', location: 'body' },
      meta_description: { type: 'string', location: 'body' },
      meta_keyword: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'mains_add',
    description: 'Add a main category (pin to storefront home).',
    scopeType: 'write',
    method: 'POST',
    path: 'mains',
    requiredFields: ['category_no'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      category_no: { type: 'number', location: 'body' },
    },
    responseShape: 'single',
  },
  // ⚠ mains_update / mains_delete — cafe24 admin docs (Latest 2026-03-01)
  // 는 `PUT/DELETE mains/{main_code}` 자체를 노출하지 않는다 (mains/
  // {display_group}/products 와 mains/properties 영역만 문서화). 본 row 들
  // 은 seed 이며 cafe24 wire 상 실제 동작 여부 미확인. 운영 검증 / 제거
  // 결정은 `cafe24-backlog-residual.md §G-2` 트랙.
  {
    id: 'mains_update',
    description:
      'Update a main category. ⚠ Not documented in cafe24 admin docs (Latest 2026-03-01); kept for backwards compatibility pending production verification.',
    scopeType: 'write',
    method: 'PUT',
    path: 'mains/{main_code}',
    requiredFields: ['main_code'],
    fields: {
      main_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      display_name: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'mains_delete',
    description:
      'Delete a main category. ⚠ Not documented in cafe24 admin docs (Latest 2026-03-01); kept for backwards compatibility pending production verification.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'mains/{main_code}',
    requiredFields: ['main_code'],
    fields: {
      main_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'autodisplay_create',
    description: 'Create an auto-layout rule for a category.',
    scopeType: 'write',
    method: 'POST',
    path: 'autodisplay',
    requiredFields: ['category_no'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      category_no: { type: 'number', location: 'body' },
      sort_type: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'autodisplay_update',
    description: 'Update an auto-layout rule by display_no.',
    scopeType: 'write',
    method: 'PUT',
    // cafe24 docs placeholder: `{display_no}` (auto-layout rule id, not the
    // target category number — pre-2026-05-22 seed conflated these).
    path: 'autodisplay/{display_no}',
    requiredFields: ['display_no'],
    fields: {
      display_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      sort_type: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'autodisplay_delete',
    description: 'Delete an auto-layout rule by display_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'autodisplay/{display_no}',
    requiredFields: ['display_no'],
    fields: {
      display_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
];
