import type { Cafe24OperationMetadata } from './types.js';

export const collectionOperations: Cafe24OperationMetadata[] = [
  {
    id: 'brands_list',
    description: 'List brands in the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'brands',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'manufacturers_list',
    description: 'List manufacturers.',
    scopeType: 'read',
    method: 'GET',
    path: 'manufacturers',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'trends_list',
    description: 'List trends.',
    scopeType: 'read',
    method: 'GET',
    path: 'trends',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  // Phase 6d — collection (brands CRUD baseline)
  {
    id: 'brands_count',
    description: 'Retrieve the count of brands.',
    scopeType: 'read',
    method: 'GET',
    path: 'brands/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'brands_create',
    description: 'Create a brand. brand_name required.',
    scopeType: 'write',
    method: 'POST',
    path: 'brands',
    requiredFields: ['brand_name'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      brand_name: { type: 'string', location: 'body' },
      brand_code: { type: 'string', location: 'body' },
      brand_description: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'brands_update',
    description: 'Update a brand by brand_code.',
    scopeType: 'write',
    method: 'PUT',
    path: 'brands/{brand_code}',
    requiredFields: ['brand_code'],
    fields: {
      brand_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      brand_name: { type: 'string', location: 'body' },
      brand_description: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'brands_delete',
    description: 'Delete a brand by brand_code.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'brands/{brand_code}',
    requiredFields: ['brand_code'],
    fields: {
      brand_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  // Phase 8h — Collection 완성 (manufacturers + trends + classifications + origin)
  {
    id: 'manufacturers_count',
    description: 'Retrieve the count of manufacturers.',
    scopeType: 'read',
    method: 'GET',
    path: 'manufacturers/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'manufacturers_get',
    description: 'Retrieve a manufacturer by manufacturer_code.',
    scopeType: 'read',
    method: 'GET',
    path: 'manufacturers/{manufacturer_code}',
    requiredFields: ['manufacturer_code'],
    fields: {
      manufacturer_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'manufacturers_create',
    description:
      'Create a manufacturer. Body schema partial — refer to Cafe24 docs.',
    scopeType: 'write',
    method: 'POST',
    path: 'manufacturers',
    requiredFields: ['manufacturer_name'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      manufacturer_name: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'manufacturers_update',
    description: 'Update a manufacturer (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'manufacturers/{manufacturer_code}',
    requiredFields: ['manufacturer_code'],
    fields: {
      manufacturer_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      manufacturer_name: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'trends_count',
    description: 'Retrieve the count of trend tags.',
    scopeType: 'read',
    method: 'GET',
    path: 'trends/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'classifications_list',
    description: 'List custom (user-defined) classifications.',
    scopeType: 'read',
    method: 'GET',
    path: 'classifications',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'classifications_count',
    description: 'Retrieve the count of custom classifications.',
    scopeType: 'read',
    method: 'GET',
    path: 'classifications/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'origin_list',
    description: 'List country-of-origin entries.',
    scopeType: 'read',
    method: 'GET',
    path: 'origin',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
];
