import type { Cafe24OperationMetadata } from './types.js';

export const communityOperations: Cafe24OperationMetadata[] = [
  {
    id: 'boards_list',
    label: '게시판 목록 조회',
    description: 'List boards in the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'boards',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'board_articles_list',
    label: '게시판 글 목록 조회',
    description: 'List articles in a specific board.',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}/articles',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'board_article_get',
    label: '게시판 글 단건 조회',
    description: 'Get a single article.',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}/articles/{article_no}',
    requiredFields: ['board_no', 'article_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  // Phase 7c — Community boards CRUD + comments + commenttemplates + urgentinquiry
  {
    id: 'boards_settings_get',
    label: '게시판 설정 조회',
    description: "Retrieve a board's settings.",
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'boards_settings_update',
    label: '게시판 설정 수정',
    description: "Update a board's settings (partial).",
    scopeType: 'write',
    method: 'PUT',
    path: 'boards/{board_no}',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      board_name: { type: 'string', location: 'body' },
      use_board: { type: 'enum', location: 'body', enum: ['T', 'F'] },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_create',
    label: '게시판 글 작성',
    description: 'Create a board article.',
    scopeType: 'write',
    method: 'POST',
    path: 'boards/{board_no}/articles',
    requiredFields: ['board_no', 'title', 'content'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      title: { type: 'string', location: 'body' },
      content: { type: 'string', location: 'body' },
      writer_name: { type: 'string', location: 'body' },
      writer_email: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_update',
    label: '게시판 글 수정',
    description: 'Update a board article.',
    scopeType: 'write',
    method: 'PUT',
    path: 'boards/{board_no}/articles/{article_no}',
    requiredFields: ['board_no', 'article_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      title: { type: 'string', location: 'body' },
      content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_delete',
    label: '게시판 글 삭제',
    description: 'Delete a board article.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'boards/{board_no}/articles/{article_no}',
    requiredFields: ['board_no', 'article_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_comments_list',
    label: '게시판 댓글 목록',
    description: 'List comments on a board article.',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}/articles/{article_no}/comments',
    requiredFields: ['board_no', 'article_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'board_articles_comments_create',
    label: '게시판 댓글 작성',
    description: 'Create a comment on a board article.',
    scopeType: 'write',
    method: 'POST',
    path: 'boards/{board_no}/articles/{article_no}/comments',
    requiredFields: ['board_no', 'article_no', 'content'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      content: { type: 'string', location: 'body' },
      writer_name: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_comments_delete',
    label: '게시판 댓글 삭제',
    description: 'Delete a comment on a board article.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'boards/{board_no}/articles/{article_no}/comments/{comment_no}',
    requiredFields: ['board_no', 'article_no', 'comment_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      comment_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'commenttemplates_list',
    label: '자주 쓰는 답변 목록',
    description: 'List the frequently-used reply templates.',
    scopeType: 'read',
    method: 'GET',
    path: 'commenttemplates',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'commenttemplates_create',
    label: '자주 쓰는 답변 생성',
    description: 'Create a frequently-used reply template.',
    scopeType: 'write',
    method: 'POST',
    path: 'commenttemplates',
    requiredFields: ['template_name', 'template_content'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      template_name: { type: 'string', location: 'body' },
      template_content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  // Phase 8j — Community 완성 (boards extras + commenttemplates rest + financials + urgentinquiry)
  {
    id: 'boards_comments_bulk',
    label: '게시판 댓글 일괄 조회',
    description: 'Bulk list of comments across a board (all articles).',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}/comments',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'boards_seo_get',
    label: '게시판 SEO 조회',
    description: "Retrieve a board's SEO settings.",
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}/seo',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'boards_seo_update',
    label: '게시판 SEO 수정',
    description: "Update a board's SEO settings (partial).",
    scopeType: 'write',
    method: 'PUT',
    path: 'boards/{board_no}/seo',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      meta_title: { type: 'string', location: 'body' },
      meta_description: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'commenttemplates_get',
    label: '자주 쓰는 답변 단건',
    description: 'Retrieve a single comment template by template_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'commenttemplates/{template_no}',
    requiredFields: ['template_no'],
    fields: {
      template_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'commenttemplates_update',
    label: '자주 쓰는 답변 수정',
    description: 'Update a comment template (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'commenttemplates/{template_no}',
    requiredFields: ['template_no'],
    fields: {
      template_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      template_name: { type: 'string', location: 'body' },
      template_content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'commenttemplates_delete',
    label: '자주 쓰는 답변 삭제',
    description: 'Delete a comment template.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'commenttemplates/{template_no}',
    requiredFields: ['template_no'],
    fields: {
      template_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'financials_monthlyreviews_count',
    label: '월별 후기 카운트',
    description: 'Retrieve the count of product reviews by month.',
    scopeType: 'read',
    method: 'GET',
    path: 'financials/monthlyreviews/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      start_month: { type: 'string', location: 'query' },
      end_month: { type: 'string', location: 'query' },
    },
    responseShape: 'single',
  },
  {
    id: 'urgentinquiry_get',
    label: '긴급 문의 게시글 조회',
    description: 'Retrieve an urgent-inquiry article by inquiry_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'urgentinquiry/{inquiry_no}',
    requiredFields: ['inquiry_no'],
    fields: {
      inquiry_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'urgentinquiry_reply_get',
    label: '긴급 문의 답변 조회',
    description: 'Retrieve the reply to an urgent inquiry.',
    scopeType: 'read',
    method: 'GET',
    path: 'urgentinquiry/{inquiry_no}/reply',
    requiredFields: ['inquiry_no'],
    fields: {
      inquiry_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'urgentinquiry_reply_create',
    label: '긴급 문의 답변 작성',
    description: 'Create a reply to an urgent inquiry.',
    scopeType: 'write',
    method: 'POST',
    path: 'urgentinquiry/{inquiry_no}/reply',
    requiredFields: ['inquiry_no', 'content'],
    fields: {
      inquiry_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'urgentinquiry_reply_update',
    label: '긴급 문의 답변 수정',
    description: 'Update the reply to an urgent inquiry (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'urgentinquiry/{inquiry_no}/reply',
    requiredFields: ['inquiry_no'],
    fields: {
      inquiry_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
];
