import type { Cafe24OperationMetadata } from './types.js';

export const communityOperations: Cafe24OperationMetadata[] = [
  {
    id: 'boards_list',
    description: 'List boards in the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'boards',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'board_articles_list',
    description: 'List articles in a specific board.',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}/articles',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  // Phase 7c — Community boards CRUD + comments + commenttemplates + urgentinquiry
  {
    id: 'boards_settings_get',
    description: "Retrieve a board's settings.",
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'boards_settings_update',
    description: "Update a board's settings (partial).",
    scopeType: 'write',
    method: 'PUT',
    path: 'boards/{board_no}',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      board_name: { type: 'string', location: 'body' },
      use_board: { type: 'enum', location: 'body', enum: ['T', 'F'] },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_create',
    description: 'Create a board article.',
    scopeType: 'write',
    method: 'POST',
    path: 'boards/{board_no}/articles',
    requiredFields: ['board_no', 'title', 'content'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      title: { type: 'string', location: 'body' },
      content: { type: 'string', location: 'body' },
      writer_name: { type: 'string', location: 'body' },
      writer_email: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_update',
    description: 'Update a board article.',
    scopeType: 'write',
    method: 'PUT',
    path: 'boards/{board_no}/articles/{article_no}',
    requiredFields: ['board_no', 'article_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      title: { type: 'string', location: 'body' },
      content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_delete',
    description: 'Delete a board article.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'boards/{board_no}/articles/{article_no}',
    requiredFields: ['board_no', 'article_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_comments_list',
    description: 'List comments on a board article.',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}/articles/{article_no}/comments',
    requiredFields: ['board_no', 'article_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'board_articles_comments_create',
    description: 'Create a comment on a board article.',
    scopeType: 'write',
    method: 'POST',
    path: 'boards/{board_no}/articles/{article_no}/comments',
    requiredFields: ['board_no', 'article_no', 'content'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      content: { type: 'string', location: 'body' },
      writer_name: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_comments_delete',
    description: 'Delete a comment on a board article.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'boards/{board_no}/articles/{article_no}/comments/{comment_no}',
    requiredFields: ['board_no', 'article_no', 'comment_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      comment_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'commenttemplates_list',
    description: 'List the frequently-used reply templates.',
    scopeType: 'read',
    method: 'GET',
    path: 'commenttemplates',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'commenttemplates_create',
    description: 'Create a frequently-used reply template.',
    scopeType: 'write',
    method: 'POST',
    path: 'commenttemplates',
    requiredFields: ['template_name', 'template_content'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      template_name: { type: 'string', location: 'body' },
      template_content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  // Phase 8j — Community 완성 (boards extras + commenttemplates rest + financials + urgentinquiry)
  {
    id: 'boards_comments_bulk',
    description: 'Bulk list of comments across a board (all articles).',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}/comments',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'boards_seo_get',
    description: "Retrieve a board's SEO settings.",
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}/seo',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'boards_seo_update',
    description: "Update a board's SEO settings (partial).",
    scopeType: 'write',
    method: 'PUT',
    path: 'boards/{board_no}/seo',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      meta_title: { type: 'string', location: 'body' },
      meta_description: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'commenttemplates_get',
    description: 'Retrieve a single comment template by template_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'commenttemplates/{comment_no}',
    requiredFields: ['comment_no'],
    fields: {
      comment_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'commenttemplates_update',
    description: 'Update a comment template (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'commenttemplates/{comment_no}',
    requiredFields: ['comment_no'],
    fields: {
      comment_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      template_name: { type: 'string', location: 'body' },
      template_content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'commenttemplates_delete',
    description: 'Delete a comment template.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'commenttemplates/{comment_no}',
    requiredFields: ['comment_no'],
    fields: {
      comment_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'urgentinquiry_reply_get',
    description: 'Retrieve the reply to an urgent inquiry.',
    scopeType: 'read',
    method: 'GET',
    // cafe24 docs placeholder: `{article_no}` (not `{inquiry_no}`).
    path: 'urgentinquiry/{article_no}/reply',
    requiredFields: ['article_no'],
    fields: {
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'urgentinquiry_reply_create',
    description: 'Create a reply to an urgent inquiry.',
    scopeType: 'write',
    method: 'POST',
    path: 'urgentinquiry/{article_no}/reply',
    requiredFields: ['article_no', 'content'],
    fields: {
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'urgentinquiry_reply_update',
    description: 'Update the reply to an urgent inquiry (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'urgentinquiry/{article_no}/reply',
    requiredFields: ['article_no'],
    fields: {
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
];
