import type { Cafe24OperationMetadata } from './types.js';

export const customerOperations: Cafe24OperationMetadata[] = [
  {
    id: 'customer_list',
    label: '회원 목록 조회',
    description:
      'List members (customers) with filters by group, signup date, etc.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      group_no: { type: 'number', location: 'query' },
      member_id: { type: 'string', location: 'query' },
      since: {
        type: 'string',
        location: 'query',
        description:
          'ISO8601 datetime (KST, UTC+9) — created_after. Cafe24 interprets naive ISO as KST.',
      },
      until: {
        type: 'string',
        location: 'query',
        description:
          'ISO8601 datetime (KST, UTC+9) — created_before. Cafe24 interprets naive ISO as KST.',
      },
    },
    // cafe24 docs 본문 박스: "회원 ID · 가입 시작/종료일 · 회원 등급 번호 중
    // 한 가지는 반드시 입력하셔야 합니다" — requiredFields (AND) 로 표현 불가한
    // OR 제약. spec/conventions/cafe24-api-metadata.md §2 "constraints 의 의미".
    constraints: [
      { kind: 'oneOf', fields: ['member_id', 'group_no', 'since'] },
    ],
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'customer_get',
    label: '회원 단건 조회',
    description: 'Get a single customer by member_id.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_update',
    label: '회원 정보 수정',
    description: 'Update customer profile fields.',
    scopeType: 'write',
    method: 'PUT',
    path: 'customers/{member_id}',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      email: { type: 'string', location: 'body' },
      phone: { type: 'string', location: 'body' },
      sms: { type: 'enum', location: 'body', enum: ['T', 'F'] },
      news_mail: { type: 'enum', location: 'body', enum: ['T', 'F'] },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_group_update',
    label: '회원 등급 변경',
    description: 'Move a customer to a different group.',
    scopeType: 'write',
    method: 'PUT',
    path: 'customergroups/customers',
    requiredFields: ['member_id', 'group_no'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      member_id: { type: 'string', location: 'body' },
      group_no: { type: 'number', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_memos_create',
    label: '회원 메모 작성',
    description: 'Add a memo to a customer.',
    scopeType: 'write',
    method: 'POST',
    path: 'customers/{member_id}/memos',
    requiredFields: ['member_id', 'author', 'content'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      author: { type: 'string', location: 'body' },
      content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_memos_count',
    label: '회원 메모 개수 조회',
    description:
      'Retrieve the count of memos attached to a customer. Sibling of `customer_memos_list`.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/memos/count',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_memos_list',
    label: '회원 메모 목록 조회',
    description: 'List the memos attached to a customer.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/memos',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'customer_memos_get',
    label: '회원 메모 단건 조회',
    description: 'Get a single customer memo by `memo_no`.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/memos/{memo_no}',
    requiredFields: ['member_id', 'memo_no'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      memo_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_memos_update',
    label: '회원 메모 수정',
    description:
      'Update an existing customer memo. `content` is required; other fields are optional.',
    scopeType: 'write',
    method: 'PUT',
    path: 'customers/{member_id}/memos/{memo_no}',
    requiredFields: ['member_id', 'memo_no', 'content'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      memo_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      content: { type: 'string', location: 'body' },
      memo_type: {
        type: 'string',
        location: 'body',
        description: 'Memo classification (e.g. general, warning)',
      },
      is_display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Visibility flag (T=show, F=hidden)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_memos_delete',
    label: '회원 메모 삭제',
    description: 'Delete a customer memo by `memo_no`.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'customers/{member_id}/memos/{memo_no}',
    requiredFields: ['member_id', 'memo_no'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      memo_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  // Phase 7b — Customer deep (paymentinfo / properties / groups / social)
  {
    id: 'customer_delete',
    label: '회원 탈퇴 처리',
    description: 'Delete a customer account by member_id.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'customers/{member_id}',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_autoupdate_get',
    label: '회원 등급 자동 갱신 조회',
    description: 'Retrieve the auto-update setting for customer tier.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/autoupdate',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_paymentinfo_list',
    label: '회원 결제수단 목록',
    description: "List a customer's saved payment methods.",
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/paymentinformation',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'customer_paymentinfo_delete',
    label: '회원 결제수단 삭제',
    description: 'Remove all saved payment information for a customer.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'customers/{member_id}/paymentinformation',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_paymentinfo_delete_by_id',
    label: '회원 결제수단 ID 삭제',
    description: 'Remove a specific payment method from a customer.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'customers/{member_id}/paymentinformation/{payment_method_id}',
    requiredFields: ['member_id', 'payment_method_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      payment_method_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_plusapp_get',
    label: 'Plus 앱 설치 정보 조회',
    description: 'Retrieve Plus-app installation info for a customer.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/plusapp',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_social_get',
    label: '소셜 계정 조회',
    description: "Retrieve a customer's linked social account.",
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/social',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customers_properties_view',
    label: '회원가입 필드 조회',
    description: 'View the configured signup fields for the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/properties',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customers_properties_edit',
    label: '회원가입 필드 수정',
    description: 'Edit the configured signup fields (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'customers/properties',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'social_list',
    label: '소셜 연동 목록',
    description: 'List all social-login integrations configured on the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'social',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'customergroups_list',
    label: '회원 등급 목록',
    description: 'List the customer tiers configured on the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'customergroups',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'customergroups_count',
    label: '회원 등급 개수',
    description: 'Retrieve the count of configured customer tiers.',
    scopeType: 'read',
    method: 'GET',
    path: 'customergroups/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customergroups_get',
    label: '회원 등급 단건 조회',
    description: 'Retrieve a customer tier by group_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'customergroups/{group_no}',
    requiredFields: ['group_no'],
    fields: {
      group_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customergroups_settings_get',
    label: '회원 등급 설정 조회',
    description: 'Retrieve mall-level customer tier settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'customergroups/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
];
