import type { Cafe24OperationMetadata } from './types.js';

export const designOperations: Cafe24OperationMetadata[] = [
  {
    id: 'themes_list',
    label: '테마 목록 조회',
    description: 'List installed themes.',
    scopeType: 'read',
    method: 'GET',
    path: 'themes',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  // Phase 8i — Design 완성 (themes count/get + theme_pages CRUD + icons)
  {
    id: 'themes_count',
    label: '테마 개수 조회',
    description: 'Retrieve the count of installed themes.',
    scopeType: 'read',
    method: 'GET',
    path: 'themes/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'themes_get',
    label: '테마 단건 조회',
    description: 'Retrieve a single theme by theme_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'themes/{theme_no}',
    requiredFields: ['theme_no'],
    fields: {
      theme_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'theme_pages_get',
    label: '테마 페이지 조회',
    description: 'Retrieve theme page contents (HTML/CSS).',
    scopeType: 'read',
    method: 'GET',
    path: 'themes/{theme_no}/pages/{page_path}',
    requiredFields: ['theme_no', 'page_path'],
    fields: {
      theme_no: { type: 'number', location: 'path' },
      page_path: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'theme_pages_create',
    label: '테마 페이지 생성',
    description: 'Create a theme page. Body schema partial — refer to Cafe24 docs.',
    scopeType: 'write',
    method: 'POST',
    path: 'themes/{theme_no}/pages',
    requiredFields: ['theme_no', 'page_path'],
    fields: {
      theme_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      page_path: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'theme_pages_update',
    label: '테마 페이지 수정',
    description: 'Update theme page contents (partial). Refer to Cafe24 docs for full schema.',
    scopeType: 'write',
    method: 'PUT',
    path: 'themes/{theme_no}/pages/{page_path}',
    requiredFields: ['theme_no', 'page_path'],
    fields: {
      theme_no: { type: 'number', location: 'path' },
      page_path: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'theme_pages_delete',
    label: '테마 페이지 삭제',
    description: 'Delete a theme page.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'themes/{theme_no}/pages/{page_path}',
    requiredFields: ['theme_no', 'page_path'],
    fields: {
      theme_no: { type: 'number', location: 'path' },
      page_path: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'icons_list',
    label: '디자인 아이콘 목록 조회',
    description: 'List storefront design icons (new/best/sale badges, etc.).',
    scopeType: 'read',
    method: 'GET',
    path: 'icons',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'icons_update_settings',
    label: '상점 아이콘 설정 수정',
    description: 'Update storefront icon settings (partial). Refer to Cafe24 docs for full schema.',
    scopeType: 'write',
    method: 'PUT',
    path: 'icons',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
];
