import type { Cafe24OperationMetadata } from './types.js';
import { RESTRICTED_APPROVAL } from './restricted-approval.js';

export const notificationOperations: Cafe24OperationMetadata[] = [
  {
    id: 'sms_send',
    description: 'Send an SMS via the Cafe24 SMS service.',
    scopeType: 'write',
    method: 'POST',
    path: 'sms',
    requiredFields: ['content'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      sender_no: {
        type: 'number',
        location: 'body',
        description: 'Sender id (unique serial number of the sender)',
      },
      content: {
        type: 'string',
        location: 'body',
        description: 'Message body',
      },
      recipients: {
        type: 'array',
        location: 'body',
        description: 'Recipient phone numbers (max 100)',
      },
      member_id: {
        type: 'array',
        location: 'body',
        description: 'Member ids (max 100)',
      },
      group_no: {
        type: 'number',
        location: 'body',
        description: 'Member group number (0=all groups)',
      },
      exclude_unsubscriber: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'T',
        description: 'Exclude unsubscribers (T=exclude, F=include)',
      },
      type: {
        type: 'enum',
        location: 'body',
        enum: ['SMS', 'LMS'],
        default: 'SMS',
        description: 'Send type (SMS=short, LMS=long)',
      },
      title: { type: 'string', location: 'body', description: 'Title' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'sms_balance_get',
    description: 'Get the remaining SMS credit balance.',
    scopeType: 'read',
    method: 'GET',
    path: 'sms/balance',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  // Phase 6f — Notification 보완
  {
    id: 'sms_senders_list',
    description: 'List the registered SMS sender numbers.',
    scopeType: 'read',
    method: 'GET',
    path: 'sms/senders',
    requiredFields: [],
    fields: {},
    responseShape: 'list',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'sms_receivers_get',
    description: 'Retrieve a single SMS recipient.',
    scopeType: 'read',
    method: 'GET',
    path: 'sms/receivers',
    requiredFields: [],
    fields: {
      recipient_type: {
        type: 'enum',
        location: 'query',
        enum: ['ALL', 'S', 'A'],
        description: 'Recipient type (ALL=all, S=supplier, A=operator)',
      },
      supplier_name: {
        type: 'string',
        location: 'query',
        description: 'Supplier name',
      },
      supplier_id: {
        type: 'string',
        location: 'query',
        description: 'Supplier id',
      },
      user_name: {
        type: 'string',
        location: 'query',
        description: 'Operator name',
      },
      user_id: {
        type: 'string',
        location: 'query',
        description: 'Operator id',
      },
      manager_name: {
        type: 'string',
        location: 'query',
        description: 'Manager name',
      },
      cellphone: {
        type: 'string',
        location: 'query',
        description: 'Mobile phone number',
      },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'automails_get',
    description: 'Retrieve the automated email settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'automails',
    requiredFields: [],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'automails_update',
    description:
      'Update the automated email settings. Body fields are partial — refer to Cafe24 docs for the full schema.',
    scopeType: 'write',
    method: 'PUT',
    path: 'automails',
    requiredFields: [],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      type: {
        type: 'string',
        location: 'body',
        description: 'Mail item (automails_typecode)',
      },
      use_customer: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Customer (T=use, F=off)',
      },
      use_admin: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Operator (T=use, F=off)',
      },
      use_supplier: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Supplier (T=use, F=off)',
      },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'recipientgroups_list',
    description: 'List distribution (recipient) groups.',
    scopeType: 'read',
    method: 'GET',
    path: 'recipientgroups',
    requiredFields: [],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
    },
    responseShape: 'list',
    paginated: true,
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'recipientgroups_get',
    description: 'Retrieve details of a single distribution group by group_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'recipientgroups/{group_no}',
    requiredFields: ['group_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      group_no: {
        type: 'number',
        location: 'path',
        description: 'Distribution group number',
      },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  // Phase 8e — Notification 완성 (invitation + recipientgroups CUD)
  {
    id: 'customers_invitation_send',
    description:
      'Send an invitation to a member (member_id is a path parameter) to activate their account.',
    scopeType: 'write',
    method: 'POST',
    path: 'customers/{member_id}/invitation',
    requiredFields: ['member_id'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      member_id: {
        type: 'string',
        location: 'path',
        description: 'Member id',
      },
      invitation_type: {
        type: 'string',
        location: 'body',
        description: 'Account activation invitation channel',
      },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'recipientgroups_create',
    description:
      'Create a distribution group. Body schema partial — refer to Cafe24 docs.',
    scopeType: 'write',
    method: 'POST',
    path: 'recipientgroups',
    requiredFields: ['group_name'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      group_name: {
        type: 'string',
        location: 'body',
        description: 'Distribution group name',
      },
      group_description: {
        type: 'string',
        location: 'body',
        description: 'Distribution group description',
      },
      news_mail: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F', 'D'],
        description: 'News mail opt-in (T=allow, F=off, D=never)',
      },
      sms: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Mobile message opt-in (T=receive, F=off)',
      },
      member_group_no: {
        type: 'number',
        location: 'body',
        description: 'Member group number',
      },
      member_class: {
        type: 'enum',
        location: 'body',
        enum: ['p', 'c', 'f'],
        description: 'Member class (p=personal, c=business, f=foreigner)',
      },
      member_type: {
        type: 'enum',
        location: 'body',
        enum: ['vip', 'poor'],
        description: 'Member type (vip=special, poor=bad member)',
      },
      join_path: {
        type: 'enum',
        location: 'body',
        enum: ['P', 'M'],
        description: 'Join path (P=PC, M=mobile)',
      },
      inflow_path: {
        type: 'string',
        location: 'body',
        description: 'Inflow path',
      },
      inflow_path_detail: {
        type: 'string',
        location: 'body',
        description: 'Inflow path detail',
      },
      date_type: {
        type: 'enum',
        location: 'body',
        enum: ['join', 'birthday', 'wedding', 'partner'],
        description:
          'Search date type (join, birthday, wedding, partner birthday)',
      },
      start_date: {
        type: 'string',
        location: 'body',
        description: 'Search start date (YYYY-MM-DD, KST)',
      },
      end_date: {
        type: 'string',
        location: 'body',
        description: 'Search end date (YYYY-MM-DD, KST)',
      },
      solar_calendar: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Solar calendar (T=solar, F=lunar)',
      },
      age_min: {
        type: 'number',
        location: 'body',
        description: 'Age search minimum',
      },
      age_max: {
        type: 'number',
        location: 'body',
        description: 'Age search maximum',
      },
      gender: {
        type: 'enum',
        location: 'body',
        enum: ['M', 'F'],
        description: 'Gender (M=male, F=female)',
      },
      available_points_min: {
        type: 'number',
        location: 'body',
        description: 'Points search minimum',
      },
      available_points_max: {
        type: 'number',
        location: 'body',
        description: 'Points search maximum',
      },
      use_mobile_app: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Mobile app usage (T=use, F=off)',
      },
      plusapp_member_join: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Brand-app joined member (T=yes, F=no)',
      },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'recipientgroups_update',
    description: 'Update a distribution group (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'recipientgroups/{group_no}',
    requiredFields: ['group_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      group_no: {
        type: 'number',
        location: 'path',
        description: 'Distribution group number',
      },
      group_name: {
        type: 'string',
        location: 'body',
        description: 'Distribution group name',
      },
      group_description: {
        type: 'string',
        location: 'body',
        description: 'Distribution group description',
      },
      news_mail: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F', 'D'],
        description: 'News mail opt-in (T=allow, F=off, D=never)',
      },
      sms: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Mobile message opt-in (T=receive, F=off)',
      },
      member_group_no: {
        type: 'number',
        location: 'body',
        description: 'Member group number',
      },
      member_class: {
        type: 'enum',
        location: 'body',
        enum: ['p', 'c', 'f'],
        description: 'Member class (p=personal, c=business, f=foreigner)',
      },
      member_type: {
        type: 'enum',
        location: 'body',
        enum: ['vip', 'poor'],
        description: 'Member type (vip=special, poor=bad member)',
      },
      join_path: {
        type: 'enum',
        location: 'body',
        enum: ['P', 'M'],
        description: 'Join path (P=PC, M=mobile)',
      },
      inflow_path: {
        type: 'string',
        location: 'body',
        description: 'Inflow path',
      },
      inflow_path_detail: {
        type: 'string',
        location: 'body',
        description: 'Inflow path detail',
      },
      date_type: {
        type: 'enum',
        location: 'body',
        enum: ['join', 'birthday', 'wedding', 'partner'],
        description:
          'Search date type (join, birthday, wedding, partner birthday)',
      },
      start_date: {
        type: 'string',
        location: 'body',
        description: 'Search start date (YYYY-MM-DD, KST)',
      },
      end_date: {
        type: 'string',
        location: 'body',
        description: 'Search end date (YYYY-MM-DD, KST)',
      },
      solar_calendar: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Solar calendar (T=solar, F=lunar)',
      },
      age_min: {
        type: 'number',
        location: 'body',
        description: 'Age search minimum',
      },
      age_max: {
        type: 'number',
        location: 'body',
        description: 'Age search maximum',
      },
      gender: {
        type: 'enum',
        location: 'body',
        enum: ['M', 'F'],
        description: 'Gender (M=male, F=female)',
      },
      available_points_min: {
        type: 'number',
        location: 'body',
        description: 'Points search minimum',
      },
      available_points_max: {
        type: 'number',
        location: 'body',
        description: 'Points search maximum',
      },
      use_mobile_app: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Mobile app usage (T=use, F=off)',
      },
      plusapp_member_join: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Brand-app joined member (T=yes, F=no)',
      },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'recipientgroups_delete',
    description: 'Delete a distribution group by group_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'recipientgroups/{group_no}',
    requiredFields: ['group_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      group_no: {
        type: 'number',
        location: 'path',
        description: 'Distribution group number',
      },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
];
