import type { Cafe24OperationMetadata } from './types.js';
import { RESTRICTED_APPROVAL } from './restricted-approval.js';

export const notificationOperations: Cafe24OperationMetadata[] = [
  {
    id: 'sms_send',
    label: 'SMS 발송',
    description: 'Send an SMS via the Cafe24 SMS service.',
    scopeType: 'write',
    method: 'POST',
    path: 'sms',
    requiredFields: ['sender', 'receiver', 'content'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      sender: { type: 'string', location: 'body' },
      receiver: { type: 'string', location: 'body' },
      content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'sms_balance_get',
    label: 'SMS 잔액 조회',
    description: 'Get the remaining SMS credit balance.',
    scopeType: 'read',
    method: 'GET',
    path: 'sms/balance',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  // Phase 6f — Notification 보완
  {
    id: 'sms_senders_list',
    label: 'SMS 발신자 목록 조회',
    description: 'List the registered SMS sender numbers.',
    scopeType: 'read',
    method: 'GET',
    path: 'sms/senders',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'sms_receivers_get',
    label: 'SMS 수신자 조회',
    description: 'Retrieve a single SMS recipient.',
    scopeType: 'read',
    method: 'GET',
    path: 'sms/receivers',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      member_id: { type: 'string', location: 'query' },
      cellphone: { type: 'string', location: 'query' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'automails_get',
    label: '자동 이메일 설정 조회',
    description: 'Retrieve the automated email settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'automails',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'automails_update',
    label: '자동 이메일 설정 수정',
    description:
      'Update the automated email settings. Body fields are partial — refer to Cafe24 docs for the full schema.',
    scopeType: 'write',
    method: 'PUT',
    path: 'automails',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'recipientgroups_list',
    label: '수신자 그룹 목록',
    description: 'List distribution (recipient) groups.',
    scopeType: 'read',
    method: 'GET',
    path: 'recipientgroups',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'recipientgroups_get',
    label: '수신자 그룹 상세',
    description: 'Retrieve details of a single distribution group by group_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'recipientgroups/{group_no}',
    requiredFields: ['group_no'],
    fields: {
      group_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  // Phase 8e — Notification 완성 (invitation + recipientgroups CUD)
  {
    id: 'customers_invitation_send',
    label: '회원 활성화 초대 발송',
    description: 'Send an invitation to a member to activate their account.',
    scopeType: 'write',
    method: 'POST',
    path: 'customers/invitation',
    requiredFields: ['member_id'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      member_id: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'recipientgroups_create',
    label: '수신자 그룹 생성',
    description:
      'Create a distribution group. Body schema partial — refer to Cafe24 docs.',
    scopeType: 'write',
    method: 'POST',
    path: 'recipientgroups',
    requiredFields: ['group_name'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      group_name: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'recipientgroups_update',
    label: '수신자 그룹 수정',
    description: 'Update a distribution group (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'recipientgroups/{group_no}',
    requiredFields: ['group_no'],
    fields: {
      group_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      group_name: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
  {
    id: 'recipientgroups_delete',
    label: '수신자 그룹 삭제',
    description: 'Delete a distribution group by group_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'recipientgroups/{group_no}',
    requiredFields: ['group_no'],
    fields: {
      group_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.notification,
  },
];
