import type { Cafe24OperationMetadata } from './types.js';
import {
  CAFE24_DATE_FIELD_SINCE,
  CAFE24_DATE_FIELD_UNTIL,
} from './date-descriptions.js';

export const orderOperations: Cafe24OperationMetadata[] = [
  {
    id: 'order_list',
    description:
      'List orders with filters by date range, status, payment method, etc.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders',
    requiredFields: ['shop_no', 'start_date', 'end_date'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      start_date: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_SINCE,
      },
      end_date: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_UNTIL,
      },
      date_type: {
        type: 'enum',
        location: 'query',
        enum: ['order_date', 'pay_date', 'ship_date'],
        default: 'order_date',
      },
      order_status: {
        type: 'string',
        location: 'query',
        description: 'Comma-separated order status codes (e.g. "N00,N10")',
      },
      payment_method: { type: 'string', location: 'query' },
      member_id: { type: 'string', location: 'query' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'order_get',
    description: 'Get a single order by order_id.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}',
    requiredFields: ['order_id'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'order_items_list',
    description: 'List items in an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/items',
    requiredFields: ['order_id'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'order_shipments_create',
    description:
      'Register shipping info (carrier, tracking number) for order items.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/shipments',
    requiredFields: ['order_id', 'shipping_company_code', 'tracking_no'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      shipping_company_code: { type: 'string', location: 'body' },
      tracking_no: { type: 'string', location: 'body' },
      status: {
        type: 'enum',
        location: 'body',
        enum: ['standby', 'shipping', 'shipped'],
        default: 'shipped',
      },
      items: {
        type: 'array',
        location: 'body',
        description: 'Array of `{ order_item_code, ... }`',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'order_buyer_update',
    description: 'Update buyer information on an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/buyer',
    requiredFields: ['order_id'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      name: { type: 'string', location: 'body' },
      phone: { type: 'string', location: 'body' },
      email: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_memos_create',
    description: 'Add a memo to an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/memos',
    requiredFields: ['order_id', 'author', 'content'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      author: { type: 'string', location: 'body' },
      content: { type: 'string', location: 'body' },
      fixed: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'F',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'order_count',
    description:
      'Retrieve a count of orders matching the supplied filter (status, payment status, date range).',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      status: {
        type: 'string',
        location: 'query',
        description:
          'Order status filter (Cafe24 status codes, comma-separated)',
      },
      payment_status: {
        type: 'string',
        location: 'query',
        description: 'Payment status filter',
      },
      order_date_from: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_SINCE,
      },
      order_date_to: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_UNTIL,
      },
    },
    responseShape: 'single',
  },
  {
    id: 'order_status_update',
    description:
      'Update the status of a single order. Path placeholder reuses the codebase-wide `order_id` naming (Cafe24 docs call this `order_no`).',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}',
    requiredFields: ['order_id', 'status'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
      status: {
        type: 'string',
        location: 'body',
        description:
          'New order status code. Allowed values depend on the mall workflow (e.g. N00, N10, N20, ...). See Cafe24 docs for the current status table.',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'order_status_update_multiple',
    description:
      'Update the status of multiple orders at once. Returns HTTP 207 (Multi-Status) when individual orders have differing outcomes.',
    scopeType: 'write',
    method: 'PUT',
    // cafe24 docs path: `orders` (no `/status` suffix — anchor
    // `update-status-for-multiple-orders`. The status field is in the body,
    // path is just `orders`).
    path: 'orders',
    requiredFields: ['order_id', 'status'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      order_id: {
        type: 'array',
        location: 'body',
        description:
          'Array of order ids to update (Cafe24 docs label this `order_no`). Each entry receives the same `status` change.',
      },
      status: {
        type: 'string',
        location: 'body',
        description:
          'New status applied to every order in the batch. See Cafe24 docs for valid status codes.',
      },
    },
    responseShape: 'list',
  },
  // Phase 6a — A/S 자동화 (cancellation / exchange / return / refund)
  {
    id: 'refunds_list',
    description: 'List refunds for the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'refunds',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      start_date: { type: 'string', location: 'query' },
      end_date: { type: 'string', location: 'query' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'refunds_get',
    description: 'Retrieve a single refund by refund_code.',
    scopeType: 'read',
    method: 'GET',
    // cafe24 docs placeholder: `{refund_code}` (not `{refund_no}` — fix).
    path: 'refunds/{refund_code}',
    requiredFields: ['refund_code'],
    fields: {
      refund_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'cancellation_get',
    description: 'Retrieve an order cancellation by claim_code.',
    scopeType: 'read',
    method: 'GET',
    // cafe24 docs placeholder: `{claim_code}` (not `{cancellation_no}` — fix).
    path: 'cancellation/{claim_code}',
    requiredFields: ['claim_code'],
    fields: {
      claim_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'cancellation_create_multiple',
    description:
      'Bulk-create order cancellations. Pass `requests` as an array of cancellation request objects; see Cafe24 docs for the per-item schema. HTTP 207 when statuses vary by object.',
    scopeType: 'write',
    method: 'POST',
    path: 'cancellation',
    requiredFields: ['requests'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      requests: {
        type: 'array',
        location: 'body',
        description:
          'Array of cancellation request objects (order_id, items, reason, ...).',
      },
    },
    responseShape: 'list',
  },
  {
    id: 'exchange_get',
    description: 'Retrieve an exchange by claim_code.',
    scopeType: 'read',
    method: 'GET',
    // cafe24 docs path: `exchange/{claim_code}` (not `orders/exchange/{order_id}`
    // — exchange is a top-level resource keyed by claim_code).
    path: 'exchange/{claim_code}',
    requiredFields: ['claim_code'],
    fields: {
      claim_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'exchange_create_multiple',
    description:
      'Bulk-create exchanges. Pass `requests` as an array — each entry typically carries order_id, exchange_item_no, product_no, variant_code, exchange_reason, exchange_quantity, shipping fees.',
    scopeType: 'write',
    method: 'POST',
    // cafe24 docs path: `exchange` (not `orders/exchanges`).
    path: 'exchange',
    requiredFields: ['requests'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      requests: {
        type: 'array',
        location: 'body',
        description:
          'Array of exchange request objects. HTTP 207 when statuses vary by object.',
      },
    },
    responseShape: 'list',
  },
  {
    id: 'return_get',
    description: 'Retrieve a return by claim_code.',
    scopeType: 'read',
    method: 'GET',
    // cafe24 docs placeholder: `{claim_code}` (not `{return_no}`).
    path: 'return/{claim_code}',
    requiredFields: ['claim_code'],
    fields: {
      claim_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'return_create_multiple',
    description:
      'Bulk-create order returns. Pass `requests` as an array of return-item objects (order_id, items, return reason, refund method).',
    scopeType: 'write',
    method: 'POST',
    path: 'return',
    requiredFields: ['requests'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      requests: {
        type: 'array',
        location: 'body',
        description:
          'Array of return request objects. HTTP 207 when individual items have differing outcomes.',
      },
    },
    responseShape: 'list',
  },
  // Batch 3-A — autocalculation · buyer · cancellation · completions · exchange · exchangerequests · items (CRUD/labels/options)
  {
    id: 'order_autocalculation_delete',
    description: 'Remove auto-calculation setting from an order.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/{order_id}/autocalculation',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'empty',
  },
  {
    id: 'order_buyer_get',
    description: 'Retrieve customer details of an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/buyer',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_buyer_history_list',
    description: 'Retrieve buyer-info change history for an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/buyer/history',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'order_cancellation_create',
    description: 'Create a cancellation for an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/cancellation',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_cancellation_update',
    description: 'Update cancellation details of an order.',
    scopeType: 'write',
    method: 'PUT',
    // cafe24 docs path: `orders/{order_id}/cancellation/{claim_code}`
    // (claim_code path placeholder added).
    path: 'orders/{order_id}/cancellation/{claim_code}',
    requiredFields: ['order_id', 'claim_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      claim_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_completions_complete',
    description: 'Mark an order as completed after PG payment confirmation.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/completions',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_exchange_create',
    description: 'Create an exchange request for an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/exchange',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_exchange_update',
    description: 'Update an exchange of an order.',
    scopeType: 'write',
    method: 'PUT',
    // cafe24 docs path: `orders/{order_id}/exchange/{claim_code}`.
    path: 'orders/{order_id}/exchange/{claim_code}',
    requiredFields: ['order_id', 'claim_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      claim_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_exchangerequests_reject',
    description: 'Reject an exchange request for an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/exchangerequests',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_items_create',
    description: 'Add an item to an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/items',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_items_update',
    description: 'Update an order item.',
    scopeType: 'write',
    method: 'PUT',
    // cafe24 docs path: `orders/{order_id}/items/{order_item_code}`
    // (per-item scope — order_item_code path placeholder added).
    path: 'orders/{order_id}/items/{order_item_code}',
    requiredFields: ['order_id', 'order_item_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      order_item_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  // cafe24 docs labels endpoints are item-scoped (`items/{order_item_code}/labels`).
  {
    id: 'order_items_labels_get',
    description: 'Retrieve labels attached to an order item.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/items/{order_item_code}/labels',
    requiredFields: ['order_id', 'order_item_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      order_item_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_items_labels_create',
    description: 'Create labels for an order item.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/items/{order_item_code}/labels',
    requiredFields: ['order_id', 'order_item_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      order_item_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_items_labels_update',
    description: 'Update labels for an order item.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/items/{order_item_code}/labels',
    requiredFields: ['order_id', 'order_item_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      order_item_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_items_labels_delete',
    description: 'Delete a label (by name) from an order item.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/{order_id}/items/{order_item_code}/labels/{name}',
    requiredFields: ['order_id', 'order_item_code', 'name'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      order_item_code: { type: 'string', location: 'path' },
      name: { type: 'string', location: 'path' },
    },
    responseShape: 'empty',
  },
  // cafe24 docs options endpoints are item-scoped (`items/{order_item_code}/options`).
  {
    id: 'order_items_options_create',
    description: 'Create options for an order item.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/items/{order_item_code}/options',
    requiredFields: ['order_id', 'order_item_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      order_item_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_items_options_update',
    description: 'Update options for an order item.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/items/{order_item_code}/options',
    requiredFields: ['order_id', 'order_item_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      order_item_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  // Batch 3-B — memos · payments · paymenttimeline · receivers · refunds · return · shipments
  {
    id: 'order_memos_list',
    description: 'List memos for an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/memos',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'order_memos_update',
    description: 'Update an order memo.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/memos/{memo_no}',
    requiredFields: ['order_id', 'memo_no'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      memo_no: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_memos_delete',
    description: 'Delete an order memo.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/{order_id}/memos/{memo_no}',
    requiredFields: ['order_id', 'memo_no'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      memo_no: { type: 'string', location: 'path' },
    },
    responseShape: 'empty',
  },
  {
    id: 'order_payments_status_update',
    description: 'Update the payment status of an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/payments',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_paymenttimeline_history',
    description: 'Retrieve the payment-history timeline of an order.',
    scopeType: 'read',
    method: 'GET',
    // cafe24 docs path: `orders/{order_id}/paymenttimeline` (no `/history`
    // suffix — anchor `retrieve-payment-history-of-an-order`).
    path: 'orders/{order_id}/paymenttimeline',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'order_paymenttimeline_details',
    description: 'Retrieve payment-detail breakdown of an order by payment_no.',
    scopeType: 'read',
    method: 'GET',
    // cafe24 docs path: `orders/{order_id}/paymenttimeline/{payment_no}`
    // (not `/details` — anchor `retrieve-payment-details-of-an-order`).
    path: 'orders/{order_id}/paymenttimeline/{payment_no}',
    requiredFields: ['order_id', 'payment_no'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      payment_no: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_receivers_list',
    description: 'List recipients attached to an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/receivers',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'order_receivers_update',
    description: 'Update recipients attached to an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/receivers',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_receivers_change_shipping',
    description:
      'Change shipping information for a specific recipient (shipping_code) of an order.',
    scopeType: 'write',
    method: 'PUT',
    // cafe24 docs path: `orders/{order_id}/receivers/{shipping_code}`
    // (per-recipient scope, not `/changeshipping` suffix — anchor
    // `change-shipping-information`).
    path: 'orders/{order_id}/receivers/{shipping_code}',
    requiredFields: ['order_id', 'shipping_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shipping_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_receivers_history_list',
    description: 'List recipient-change history for an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/receivers/history',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'order_refunds_update',
    description: 'Update an order refund by refund_code.',
    scopeType: 'write',
    method: 'PUT',
    // cafe24 docs path: `orders/{order_id}/refunds/{refund_code}`.
    path: 'orders/{order_id}/refunds/{refund_code}',
    requiredFields: ['order_id', 'refund_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      refund_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_return_create',
    description: 'Create a return for an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/return',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_return_update',
    description: 'Update a return of an order by claim_code.',
    scopeType: 'write',
    method: 'PUT',
    // cafe24 docs path: `orders/{order_id}/return/{claim_code}`.
    path: 'orders/{order_id}/return/{claim_code}',
    requiredFields: ['order_id', 'claim_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      claim_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_shipments_list',
    description: 'List shipping information of an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/shipments',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'order_shipments_update',
    description: 'Update an order shipment.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/shipments/{shipping_code}',
    requiredFields: ['order_id', 'shipping_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shipping_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_shipments_delete',
    description: 'Delete an order shipment.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/{order_id}/shipments/{shipping_code}',
    requiredFields: ['order_id', 'shipping_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shipping_code: { type: 'string', location: 'path' },
    },
    responseShape: 'empty',
  },
  // Batch 3-C — shippingfeecancellation · shortagecancellation · benefits · calculation · coupons · dashboard · inflowgroups
  {
    id: 'order_shippingfeecancellation_get',
    description: 'Retrieve shipping-fee cancellation details of an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/shippingfeecancellation',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_shippingfeecancellation_create',
    description: 'Create a shipping-fee cancellation for an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/shippingfeecancellation',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_shortagecancellation_create',
    description: 'Create a stock-shortage cancellation for an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/shortagecancellation',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'orders_benefits_list',
    description: 'Retrieve a list of order benefits.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/benefits',
    requiredFields: [],
    fields: {},
    responseShape: 'list',
  },
  {
    id: 'orders_calculation_total',
    description: 'Calculate the total payment amount for an order.',
    scopeType: 'read',
    method: 'POST',
    path: 'orders/{order_id}/calculation/total',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'orders_coupons_list',
    description: 'Retrieve a list of coupons applied to orders.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/coupons',
    requiredFields: [],
    fields: {},
    responseShape: 'list',
  },
  {
    id: 'orders_dashboard_list',
    description: 'Retrieve orders dashboard summary.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/dashboard',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_inflowgroups_list',
    description: 'List traffic-source (inflow) groups.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/inflowgroups',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'orders_inflowgroups_create',
    description: 'Create a traffic-source (inflow) group.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/inflowgroups',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_inflowgroups_update',
    description: 'Update a traffic-source (inflow) group by group_id.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/inflowgroups/{inflow_group_id}',
    requiredFields: ['inflow_group_id'],
    fields: { inflow_group_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'orders_inflowgroups_delete',
    description: 'Delete a traffic-source (inflow) group by group_id.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/inflowgroups/{inflow_group_id}',
    requiredFields: ['inflow_group_id'],
    fields: { inflow_group_id: { type: 'string', location: 'path' } },
    responseShape: 'empty',
  },
  // Batch 3-D — inflows · orders_memos_list · migrations · paymentamount · saleschannels
  // cafe24 docs path 의 inflows 영역은 inflowgroup 안에 nested 됨
  // (`orders/inflowgroups/{group_id}/inflows/...`). pre-2026-05-22 seed
  // 의 top-level `orders/inflows/*` path 는 docs 부재 — group_id path
  // 추가로 정정.
  {
    id: 'orders_inflows_list',
    description: 'List traffic sources (inflows) for an inflow group.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/inflowgroups/{group_id}/inflows',
    requiredFields: ['group_id'],
    fields: {
      group_id: { type: 'string', location: 'path' },
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'orders_inflows_create',
    description: 'Create a traffic source (inflow) under an inflow group.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/inflowgroups/{group_id}/inflows',
    requiredFields: ['group_id'],
    fields: {
      group_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'orders_inflows_update',
    description:
      'Update a traffic source (inflow) by inflow_id within a group.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/inflowgroups/{group_id}/inflows/{inflow_id}',
    requiredFields: ['group_id', 'inflow_id'],
    fields: {
      group_id: { type: 'string', location: 'path' },
      inflow_id: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'orders_inflows_delete',
    description:
      'Delete a traffic source (inflow) by inflow_id within a group.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/inflowgroups/{group_id}/inflows/{inflow_id}',
    requiredFields: ['group_id', 'inflow_id'],
    fields: {
      group_id: { type: 'string', location: 'path' },
      inflow_id: { type: 'string', location: 'path' },
    },
    responseShape: 'empty',
  },
  {
    id: 'orders_memos_list',
    description:
      'List admin memos across all orders (no order_id filter). Distinct from `order_memos_list` which lists memos for a single order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/memos',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
  },
  {
    id: 'orders_migrations_get',
    description: 'Retrieve migrated orders.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/migrations',
    requiredFields: [],
    fields: {},
    responseShape: 'list',
  },
  {
    id: 'orders_migrations_create',
    description: 'Create migration order entries.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/migrations',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_migrations_update',
    description: 'Update migration order entries.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/migrations',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_migrations_delete',
    description: 'Delete a migrated order by order_id.',
    scopeType: 'write',
    method: 'DELETE',
    // cafe24 docs path: `orders/migrations/{order_id}` (per-order scope).
    path: 'orders/migrations/{order_id}',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'empty',
  },
  {
    id: 'orders_paymentamount_get',
    description: 'Retrieve calculated payment amount.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/paymentamount',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_saleschannels_list',
    description: 'List sales channels.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/saleschannels',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'orders_saleschannels_create',
    description: 'Create a sales channel.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/saleschannels',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_saleschannels_update',
    description: 'Update a sales channel by sales_channel_id.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/saleschannels/{sales_channel_id}',
    requiredFields: ['sales_channel_id'],
    fields: { sales_channel_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'orders_saleschannels_delete',
    description: 'Delete a sales channel by sales_channel_id.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/saleschannels/{sales_channel_id}',
    requiredFields: ['sales_channel_id'],
    fields: { sales_channel_id: { type: 'string', location: 'path' } },
    responseShape: 'empty',
  },
  // Batch 3-E — payments multi · reservations · return · returnrequests · cancellation bulk · cancellationrequests · cashreceipt
  {
    id: 'payments_status_update_multiple',
    description: 'Update payment status for multiple orders in bulk.',
    scopeType: 'write',
    method: 'PUT',
    path: 'payments',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'reservations_get',
    description: 'Retrieve a booked (reserved) item (filter via query).',
    scopeType: 'read',
    method: 'GET',
    // cafe24 docs path: `reservations` (single resource, query-based
    // lookup — no path placeholder).
    path: 'reservations',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'return_update',
    description: 'Update a return record (top-level resource).',
    scopeType: 'write',
    method: 'PUT',
    path: 'return',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'returnrequests_create',
    description: 'Create a return request for multiple items.',
    scopeType: 'write',
    method: 'POST',
    path: 'returnrequests',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'returnrequests_reject',
    description: 'Reject a return request for multiple items.',
    scopeType: 'write',
    method: 'PUT',
    path: 'returnrequests',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'cancellation_update_bulk',
    description: 'Change cancellation details in bulk.',
    scopeType: 'write',
    method: 'PUT',
    path: 'cancellation',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'cancellationrequests_create',
    description: 'Create a cancellation request for multiple items.',
    scopeType: 'write',
    method: 'POST',
    path: 'cancellationrequests',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'cancellationrequests_reject',
    description: 'Reject a cancellation request for multiple items.',
    scopeType: 'write',
    method: 'PUT',
    path: 'cancellationrequests',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'cashreceipt_list',
    description: 'List cash receipts.',
    scopeType: 'read',
    method: 'GET',
    path: 'cashreceipt',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'cashreceipt_create',
    description: 'Issue a cash receipt.',
    scopeType: 'write',
    method: 'POST',
    path: 'cashreceipt',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'cashreceipt_update',
    description: 'Update a cash receipt by cashreceipt_no.',
    scopeType: 'write',
    method: 'PUT',
    path: 'cashreceipt/{cashreceipt_no}',
    requiredFields: ['cashreceipt_no'],
    fields: { cashreceipt_no: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'cashreceipt_cancel',
    description: 'Cancel a cash receipt by cashreceipt_no.',
    scopeType: 'write',
    method: 'PUT',
    // cafe24 docs path: `cashreceipt/{cashreceipt_no}/cancellation`
    // (cancellation as suffix, not the cashreceipt id prefix).
    path: 'cashreceipt/{cashreceipt_no}/cancellation',
    requiredFields: ['cashreceipt_no'],
    fields: { cashreceipt_no: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  // Batch 3-F — collectrequests · control · exchange bulk · exchangerequests bulk · fulfillments · labels · orderform_properties
  {
    id: 'collectrequests_update',
    description: 'Update a collect request by request_no.',
    scopeType: 'write',
    method: 'PUT',
    path: 'collectrequests/{request_no}',
    requiredFields: ['request_no'],
    fields: { request_no: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'exchange_update_multiple',
    description: 'Update multiple order exchanges in bulk.',
    scopeType: 'write',
    method: 'PUT',
    // path 는 단수 `exchange` 가 정답 (docs SoT). 복수 자원이지만 Cafe24 가
    // 의도적으로 단수 경로명을 쓴다 — `exchanges` 로 되돌리지 말 것 (plan G-3b).
    path: 'exchange',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'exchangerequests_create_bulk',
    description: 'Create exchange requests in bulk.',
    scopeType: 'write',
    method: 'POST',
    path: 'exchangerequests',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'exchangerequests_reject_multiple',
    description: 'Reject multiple exchange requests in bulk.',
    scopeType: 'write',
    method: 'PUT',
    // cafe24 docs path: `exchangerequests` (no `/reject` suffix — rejection
    // is the only PUT operation on this resource).
    path: 'exchangerequests',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'fulfillments_create',
    description:
      'Create shipping information for multiple orders via fulfillment.',
    scopeType: 'write',
    method: 'POST',
    path: 'fulfillments',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'labels_list',
    description: 'List order labels.',
    scopeType: 'read',
    method: 'GET',
    path: 'labels',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
  },
  {
    id: 'labels_create_multiple',
    description: 'Create multiple order labels in bulk.',
    scopeType: 'write',
    method: 'POST',
    path: 'labels',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orderform_properties_get',
    description: 'Retrieve additional order-form properties.',
    scopeType: 'read',
    method: 'GET',
    path: 'orderform/properties',
    requiredFields: [],
    fields: {},
    responseShape: 'list',
  },
  {
    id: 'orderform_properties_create',
    description: 'Create an additional order-form property.',
    scopeType: 'write',
    method: 'POST',
    path: 'orderform/properties',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orderform_properties_update',
    description: 'Update an additional order-form property by property_no.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orderform/properties/{orderform_property_id}',
    requiredFields: ['orderform_property_id'],
    fields: { orderform_property_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'orderform_properties_delete',
    description: 'Delete an additional order-form property by property_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orderform/properties/{orderform_property_id}',
    requiredFields: ['orderform_property_id'],
    fields: { orderform_property_id: { type: 'string', location: 'path' } },
    responseShape: 'empty',
  },
  // Batch 3-G — shipments bulk · subscription_shipments · unpaidorders
  {
    id: 'shipments_create_multiple',
    description: 'Create shipping information for multiple orders.',
    scopeType: 'write',
    method: 'POST',
    path: 'shipments',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'shipments_update_multiple',
    description: 'Update shipping information for multiple orders.',
    scopeType: 'write',
    method: 'PUT',
    path: 'shipments',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'subscription_shipments_create',
    description: 'Create a subscription shipment.',
    scopeType: 'write',
    method: 'POST',
    path: 'subscription/shipments',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'subscription_shipments_update',
    description: 'Update a subscription shipment by subscription_id.',
    scopeType: 'write',
    method: 'PUT',
    path: 'subscription/shipments/{subscription_id}',
    requiredFields: ['subscription_id'],
    fields: { subscription_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'subscription_shipments_items_update',
    description: 'Update product variants in a subscription shipment.',
    scopeType: 'write',
    method: 'PUT',
    path: 'subscription/shipments/{subscription_id}/items',
    requiredFields: ['subscription_id'],
    fields: { subscription_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'unpaidorders_list',
    description: 'List unpaid orders.',
    scopeType: 'read',
    method: 'GET',
    path: 'unpaidorders',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
];
