import type { Cafe24OperationMetadata } from './types.js';
import {
  CAFE24_DATE_FIELD_SINCE,
  CAFE24_DATE_FIELD_UNTIL,
} from './date-descriptions.js';

export const orderOperations: Cafe24OperationMetadata[] = [
  {
    id: 'order_list',
    label: '주문 목록 조회',
    description:
      'List orders with filters by date range, status, payment method, etc.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders',
    requiredFields: ['shop_no', 'start_date', 'end_date'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      start_date: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_SINCE,
      },
      end_date: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_UNTIL,
      },
      date_type: {
        type: 'enum',
        location: 'query',
        enum: ['order_date', 'pay_date', 'ship_date'],
        default: 'order_date',
      },
      order_status: {
        type: 'string',
        location: 'query',
        description: 'Comma-separated order status codes (e.g. "N00,N10")',
      },
      payment_method: { type: 'string', location: 'query' },
      member_id: { type: 'string', location: 'query' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'order_get',
    label: '주문 단건 조회',
    description: 'Get a single order by order_id.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}',
    requiredFields: ['order_id'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'order_items_list',
    label: '주문 상품 목록 조회',
    description: 'List items in an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/items',
    requiredFields: ['order_id'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'order_shipments_create',
    label: '주문 배송 정보 등록',
    description:
      'Register shipping info (carrier, tracking number) for order items.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/shipments',
    requiredFields: ['order_id', 'shipping_company_code', 'tracking_no'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      shipping_company_code: { type: 'string', location: 'body' },
      tracking_no: { type: 'string', location: 'body' },
      status: {
        type: 'enum',
        location: 'body',
        enum: ['standby', 'shipping', 'shipped'],
        default: 'shipped',
      },
      items: {
        type: 'array',
        location: 'body',
        description: 'Array of `{ order_item_code, ... }`',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'order_buyer_update',
    label: '주문자 정보 수정',
    description: 'Update buyer information on an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/buyer',
    requiredFields: ['order_id'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      name: { type: 'string', location: 'body' },
      phone: { type: 'string', location: 'body' },
      email: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_memos_create',
    label: '주문 메모 작성',
    description: 'Add a memo to an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/memos',
    requiredFields: ['order_id', 'author', 'content'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      author: { type: 'string', location: 'body' },
      content: { type: 'string', location: 'body' },
      fixed: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'F',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'order_count',
    label: '주문 개수 조회',
    description:
      'Retrieve a count of orders matching the supplied filter (status, payment status, date range).',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      status: {
        type: 'string',
        location: 'query',
        description:
          'Order status filter (Cafe24 status codes, comma-separated)',
      },
      payment_status: {
        type: 'string',
        location: 'query',
        description: 'Payment status filter',
      },
      order_date_from: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_SINCE,
      },
      order_date_to: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_UNTIL,
      },
    },
    responseShape: 'single',
  },
  {
    id: 'order_status_update',
    label: '주문 상태 변경',
    description:
      'Update the status of a single order. Path placeholder reuses the codebase-wide `order_id` naming (Cafe24 docs call this `order_no`).',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}',
    requiredFields: ['order_id', 'status'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
      status: {
        type: 'string',
        location: 'body',
        description:
          'New order status code. Allowed values depend on the mall workflow (e.g. N00, N10, N20, ...). See Cafe24 docs for the current status table.',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'order_status_update_multiple',
    label: '주문 상태 일괄 변경',
    description:
      'Update the status of multiple orders at once. Returns HTTP 207 (Multi-Status) when individual orders have differing outcomes.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/status',
    requiredFields: ['order_id', 'status'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      order_id: {
        type: 'array',
        location: 'body',
        description:
          'Array of order ids to update (Cafe24 docs label this `order_no`). Each entry receives the same `status` change.',
      },
      status: {
        type: 'string',
        location: 'body',
        description:
          'New status applied to every order in the batch. See Cafe24 docs for valid status codes.',
      },
    },
    responseShape: 'list',
  },
  // Phase 6a — A/S 자동화 (cancellation / exchange / return / refund)
  {
    id: 'refunds_list',
    label: '환불 목록 조회',
    description: 'List refunds for the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'refunds',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      start_date: { type: 'string', location: 'query' },
      end_date: { type: 'string', location: 'query' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'refunds_get',
    label: '환불 단건 조회',
    description: 'Retrieve a single refund by refund_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'refunds/{refund_no}',
    requiredFields: ['refund_no'],
    fields: {
      refund_no: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'cancellation_get',
    label: '취소 조회',
    description: 'Retrieve an order cancellation by cancellation_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'cancellation/{cancellation_no}',
    requiredFields: ['cancellation_no'],
    fields: {
      cancellation_no: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'cancellation_create_multiple',
    label: '취소 일괄 생성',
    description:
      'Bulk-create order cancellations. Pass `requests` as an array of cancellation request objects; see Cafe24 docs for the per-item schema. HTTP 207 when statuses vary by object.',
    scopeType: 'write',
    method: 'POST',
    path: 'cancellation',
    requiredFields: ['requests'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      requests: {
        type: 'array',
        location: 'body',
        description:
          'Array of cancellation request objects (order_id, items, reason, ...).',
      },
    },
    responseShape: 'list',
  },
  {
    id: 'exchange_get',
    label: '교환 조회',
    description:
      'Retrieve exchange details for an order. Path placeholder reuses the codebase-wide `order_id` (Cafe24 docs label this `order_no`).',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/exchange/{order_id}',
    requiredFields: ['order_id'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'exchange_create_multiple',
    label: '교환 일괄 생성',
    description:
      'Bulk-create exchanges. Pass `requests` as an array — each entry typically carries order_id, exchange_item_no, product_no, variant_code, exchange_reason, exchange_quantity, shipping fees.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/exchanges',
    requiredFields: ['requests'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      requests: {
        type: 'array',
        location: 'body',
        description:
          'Array of exchange request objects. HTTP 207 when statuses vary by object.',
      },
    },
    responseShape: 'list',
  },
  {
    id: 'return_get',
    label: '반품 조회',
    description: 'Retrieve a return by return_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'return/{return_no}',
    requiredFields: ['return_no'],
    fields: {
      return_no: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'return_create_multiple',
    label: '반품 일괄 생성',
    description:
      'Bulk-create order returns. Pass `requests` as an array of return-item objects (order_id, items, return reason, refund method).',
    scopeType: 'write',
    method: 'POST',
    path: 'return',
    requiredFields: ['requests'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      requests: {
        type: 'array',
        location: 'body',
        description:
          'Array of return request objects. HTTP 207 when individual items have differing outcomes.',
      },
    },
    responseShape: 'list',
  },
  // Batch 3-A — autocalculation · buyer · cancellation · completions · exchange · exchangerequests · items (CRUD/labels/options)
  {
    id: 'order_autocalculation_delete',
    label: '주문 자동 계산 해제',
    description: 'Remove auto-calculation setting from an order.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/{order_id}/autocalculation',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'empty',
  },
  {
    id: 'order_buyer_get',
    label: '주문자 정보 조회',
    description: 'Retrieve customer details of an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/buyer',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_buyer_history_list',
    label: '주문자 정보 변경 이력',
    description: 'Retrieve buyer-info change history for an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/buyer/history',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'order_cancellation_create',
    label: '주문 취소 생성',
    description: 'Create a cancellation for an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/cancellation',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_cancellation_update',
    label: '주문 취소 상세 변경',
    description: 'Update cancellation details of an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/cancellation',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_completions_complete',
    label: 'PG 결제 후 주문 완료',
    description: 'Mark an order as completed after PG payment confirmation.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/completions',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_exchange_create',
    label: '주문 교환 생성',
    description: 'Create an exchange request for an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/exchange',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_exchange_update',
    label: '주문 교환 수정',
    description: 'Update an exchange of an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/exchange',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_exchangerequests_reject',
    label: '교환 요청 반려',
    description: 'Reject an exchange request for an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/exchangerequests',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_items_create',
    label: '주문 상품 추가',
    description: 'Add an item to an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/items',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_items_update',
    label: '주문 상품 수정',
    description: 'Update an order item.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/items',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_items_labels_get',
    label: '주문 상품 라벨 조회',
    description: 'Retrieve labels attached to order items.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/items/labels',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_items_labels_create',
    label: '주문 상품 라벨 생성',
    description: 'Create labels for order items.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/items/labels',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_items_labels_update',
    label: '주문 상품 라벨 수정',
    description: 'Update labels for order items.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/items/labels',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_items_labels_delete',
    label: '주문 상품 라벨 삭제',
    description: 'Delete labels for order items.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/{order_id}/items/labels',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'empty',
  },
  {
    id: 'order_items_options_create',
    label: '주문 상품 옵션 생성',
    description: 'Create options for order items.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/items/options',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_items_options_update',
    label: '주문 상품 옵션 수정',
    description: 'Update options for order items.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/items/options',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  // Batch 3-B — memos · payments · paymenttimeline · receivers · refunds · return · shipments
  {
    id: 'order_memos_list',
    label: '주문 메모 목록',
    description: 'List memos for an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/memos',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'order_memos_update',
    label: '주문 메모 수정',
    description: 'Update an order memo.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/memos/{memo_no}',
    requiredFields: ['order_id', 'memo_no'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      memo_no: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_memos_delete',
    label: '주문 메모 삭제',
    description: 'Delete an order memo.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/{order_id}/memos/{memo_no}',
    requiredFields: ['order_id', 'memo_no'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      memo_no: { type: 'string', location: 'path' },
    },
    responseShape: 'empty',
  },
  {
    id: 'order_payments_status_update',
    label: '주문 결제 상태 수정',
    description: 'Update the payment status of an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/payments',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_paymenttimeline_history',
    label: '결제 이력 조회',
    description: 'Retrieve the payment-history timeline of an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/paymenttimeline/history',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'order_paymenttimeline_details',
    label: '결제 상세 조회',
    description: 'Retrieve payment-detail breakdown of an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/paymenttimeline/details',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_receivers_list',
    label: '받는 사람 목록',
    description: 'List recipients attached to an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/receivers',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'order_receivers_update',
    label: '받는 사람 수정',
    description: 'Update recipients attached to an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/receivers',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_receivers_change_shipping',
    label: '받는 사람 배송지 변경',
    description: 'Change shipping information of recipients for an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/receivers/changeshipping',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_receivers_history_list',
    label: '받는 사람 변경 이력',
    description: 'List recipient-change history for an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/receivers/history',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'order_refunds_update',
    label: '주문 환불 수정',
    description: 'Update an order refund.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/refunds',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_return_create',
    label: '주문 반품 생성',
    description: 'Create a return for an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/return',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_return_update',
    label: '주문 반품 수정',
    description: 'Update a return of an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/return',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_shipments_list',
    label: '주문 배송 정보 목록',
    description: 'List shipping information of an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/shipments',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'order_shipments_update',
    label: '주문 배송 정보 수정',
    description: 'Update an order shipment.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/shipments/{shipping_code}',
    requiredFields: ['order_id', 'shipping_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shipping_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_shipments_delete',
    label: '주문 배송 정보 삭제',
    description: 'Delete an order shipment.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/{order_id}/shipments/{shipping_code}',
    requiredFields: ['order_id', 'shipping_code'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shipping_code: { type: 'string', location: 'path' },
    },
    responseShape: 'empty',
  },
  // Batch 3-C — shippingfeecancellation · shortagecancellation · benefits · calculation · coupons · dashboard · inflowgroups
  {
    id: 'order_shippingfeecancellation_get',
    label: '배송비 취소 상세',
    description: 'Retrieve shipping-fee cancellation details of an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/shippingfeecancellation',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_shippingfeecancellation_create',
    label: '배송비 취소 생성',
    description: 'Create a shipping-fee cancellation for an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/shippingfeecancellation',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'order_shortagecancellation_create',
    label: '재고 부족 취소 생성',
    description: 'Create a stock-shortage cancellation for an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/shortagecancellation',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'orders_benefits_list',
    label: '주문 혜택 목록',
    description: 'List benefits applied to an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/benefits',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'orders_calculation_total',
    label: '주문 결제 금액 계산',
    description: 'Calculate the total payment amount for an order.',
    scopeType: 'read',
    method: 'POST',
    path: 'orders/{order_id}/calculation/total',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'orders_coupons_list',
    label: '주문 쿠폰 목록',
    description: 'List coupons applied to an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/coupons',
    requiredFields: ['order_id'],
    fields: { order_id: { type: 'string', location: 'path' } },
    responseShape: 'list',
  },
  {
    id: 'orders_dashboard_list',
    label: '주문 대시보드',
    description: 'Retrieve orders dashboard summary.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/dashboard',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_inflowgroups_list',
    label: '유입 그룹 목록',
    description: 'List traffic-source (inflow) groups.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/inflowgroups',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'orders_inflowgroups_create',
    label: '유입 그룹 생성',
    description: 'Create a traffic-source (inflow) group.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/inflowgroups',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_inflowgroups_update',
    label: '유입 그룹 수정',
    description: 'Update a traffic-source (inflow) group by group_id.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/inflowgroups/{group_id}',
    requiredFields: ['group_id'],
    fields: { group_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'orders_inflowgroups_delete',
    label: '유입 그룹 삭제',
    description: 'Delete a traffic-source (inflow) group by group_id.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/inflowgroups/{group_id}',
    requiredFields: ['group_id'],
    fields: { group_id: { type: 'string', location: 'path' } },
    responseShape: 'empty',
  },
  // Batch 3-D — inflows · orders_memos_list · migrations · paymentamount · saleschannels
  {
    id: 'orders_inflows_list',
    label: '유입 출처 목록',
    description: 'List traffic sources (inflows).',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/inflows',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'orders_inflows_create',
    label: '유입 출처 생성',
    description: 'Create a traffic source (inflow).',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/inflows',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_inflows_update',
    label: '유입 출처 수정',
    description: 'Update a traffic source (inflow) by source_id.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/inflows/{source_id}',
    requiredFields: ['source_id'],
    fields: { source_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'orders_inflows_delete',
    label: '유입 출처 삭제',
    description: 'Delete a traffic source (inflow) by source_id.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/inflows/{source_id}',
    requiredFields: ['source_id'],
    fields: { source_id: { type: 'string', location: 'path' } },
    responseShape: 'empty',
  },
  {
    id: 'orders_memos_list',
    label: '관리자 메모 목록 (전체 주문)',
    description:
      'List admin memos across all orders (no order_id filter). Distinct from `order_memos_list` which lists memos for a single order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/memos',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
  },
  {
    id: 'orders_migrations_get',
    label: '이관 주문 조회',
    description: 'Retrieve migrated orders.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/migrations',
    requiredFields: [],
    fields: {},
    responseShape: 'list',
  },
  {
    id: 'orders_migrations_create',
    label: '이관 주문 생성',
    description: 'Create migration order entries.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/migrations',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_migrations_update',
    label: '이관 주문 수정',
    description: 'Update migration order entries.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/migrations',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_migrations_delete',
    label: '이관 주문 삭제',
    description: 'Delete migration order entries.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/migrations',
    requiredFields: [],
    fields: {},
    responseShape: 'empty',
  },
  {
    id: 'orders_paymentamount_get',
    label: '결제 금액 조회',
    description: 'Retrieve calculated payment amount.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/paymentamount',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_saleschannels_list',
    label: '판매 채널 목록',
    description: 'List sales channels.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/saleschannels',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'orders_saleschannels_create',
    label: '판매 채널 생성',
    description: 'Create a sales channel.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/saleschannels',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orders_saleschannels_update',
    label: '판매 채널 수정',
    description: 'Update a sales channel by channel_id.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/saleschannels/{channel_id}',
    requiredFields: ['channel_id'],
    fields: { channel_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'orders_saleschannels_delete',
    label: '판매 채널 삭제',
    description: 'Delete a sales channel by channel_id.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orders/saleschannels/{channel_id}',
    requiredFields: ['channel_id'],
    fields: { channel_id: { type: 'string', location: 'path' } },
    responseShape: 'empty',
  },
  // Batch 3-E — payments multi · reservations · return · returnrequests · cancellation bulk · cancellationrequests · cashreceipt
  {
    id: 'payments_status_update_multiple',
    label: '결제 상태 일괄 변경',
    description: 'Update payment status for multiple orders in bulk.',
    scopeType: 'write',
    method: 'PUT',
    path: 'payments',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'reservations_get',
    label: '예약 상품 조회',
    description: 'Retrieve a booked (reserved) item by reservation_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'reservations/{reservation_no}',
    requiredFields: ['reservation_no'],
    fields: { reservation_no: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'return_update',
    label: '반품 수정',
    description: 'Update a return record (top-level resource).',
    scopeType: 'write',
    method: 'PUT',
    path: 'return',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'returnrequests_create',
    label: '반품 요청 생성',
    description: 'Create a return request for multiple items.',
    scopeType: 'write',
    method: 'POST',
    path: 'returnrequests',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'returnrequests_reject',
    label: '반품 요청 거부',
    description: 'Reject a return request for multiple items.',
    scopeType: 'write',
    method: 'PUT',
    path: 'returnrequests',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'cancellation_update_bulk',
    label: '취소 상세 일괄 변경',
    description: 'Change cancellation details in bulk.',
    scopeType: 'write',
    method: 'PUT',
    path: 'cancellation',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'cancellationrequests_create',
    label: '취소 요청 생성',
    description: 'Create a cancellation request for multiple items.',
    scopeType: 'write',
    method: 'POST',
    path: 'cancellationrequests',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'cancellationrequests_reject',
    label: '취소 요청 거부',
    description: 'Reject a cancellation request for multiple items.',
    scopeType: 'write',
    method: 'PUT',
    path: 'cancellationrequests',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'cashreceipt_list',
    label: '현금영수증 목록',
    description: 'List cash receipts.',
    scopeType: 'read',
    method: 'GET',
    path: 'cashreceipt',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'cashreceipt_create',
    label: '현금영수증 발행',
    description: 'Issue a cash receipt.',
    scopeType: 'write',
    method: 'POST',
    path: 'cashreceipt',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'cashreceipt_update',
    label: '현금영수증 수정',
    description: 'Update a cash receipt by receipt_no.',
    scopeType: 'write',
    method: 'PUT',
    path: 'cashreceipt/{receipt_no}',
    requiredFields: ['receipt_no'],
    fields: { receipt_no: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'cashreceipt_cancel',
    label: '현금영수증 취소',
    description: 'Cancel a cash receipt by receipt_no.',
    scopeType: 'write',
    method: 'PUT',
    path: 'cashreceipt/cancellation/{receipt_no}',
    requiredFields: ['receipt_no'],
    fields: { receipt_no: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  // Batch 3-F — collectrequests · control · exchange bulk · exchangerequests bulk · fulfillments · labels · orderform_properties
  {
    id: 'collectrequests_update',
    label: '수거 요청 수정',
    description: 'Update a collect request by collect_request_no.',
    scopeType: 'write',
    method: 'PUT',
    path: 'collectrequests/{collect_request_no}',
    requiredFields: ['collect_request_no'],
    fields: { collect_request_no: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'control',
    label: '주문 컨트롤',
    description: 'Apply order-control actions in bulk.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/control',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'exchange_update_multiple',
    label: '교환 일괄 수정',
    description: 'Update multiple order exchanges in bulk.',
    scopeType: 'write',
    method: 'PUT',
    path: 'exchanges',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'exchangerequests_create_bulk',
    label: '교환 요청 일괄 생성',
    description: 'Create exchange requests in bulk.',
    scopeType: 'write',
    method: 'POST',
    path: 'exchangerequests',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'exchangerequests_reject_multiple',
    label: '교환 요청 일괄 거부',
    description: 'Reject multiple exchange requests in bulk.',
    scopeType: 'write',
    method: 'PUT',
    path: 'exchangerequests/reject',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'fulfillments_create',
    label: '풀필먼트 배송 생성',
    description:
      'Create shipping information for multiple orders via fulfillment.',
    scopeType: 'write',
    method: 'POST',
    path: 'fulfillments',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'labels_list',
    label: '주문 라벨 목록',
    description: 'List order labels.',
    scopeType: 'read',
    method: 'GET',
    path: 'labels',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
  },
  {
    id: 'labels_create_multiple',
    label: '주문 라벨 일괄 생성',
    description: 'Create multiple order labels in bulk.',
    scopeType: 'write',
    method: 'POST',
    path: 'labels',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orderform_properties_get',
    label: '주문서 추가 필드 조회',
    description: 'Retrieve additional order-form properties.',
    scopeType: 'read',
    method: 'GET',
    path: 'orderform/properties',
    requiredFields: [],
    fields: {},
    responseShape: 'list',
  },
  {
    id: 'orderform_properties_create',
    label: '주문서 추가 필드 생성',
    description: 'Create an additional order-form property.',
    scopeType: 'write',
    method: 'POST',
    path: 'orderform/properties',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'orderform_properties_update',
    label: '주문서 추가 필드 수정',
    description: 'Update an additional order-form property by property_no.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orderform/properties/{property_no}',
    requiredFields: ['property_no'],
    fields: { property_no: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'orderform_properties_delete',
    label: '주문서 추가 필드 삭제',
    description: 'Delete an additional order-form property by property_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'orderform/properties/{property_no}',
    requiredFields: ['property_no'],
    fields: { property_no: { type: 'string', location: 'path' } },
    responseShape: 'empty',
  },
  // Batch 3-G — shipments bulk · subscription_shipments · unpaidorders
  {
    id: 'shipments_create_multiple',
    label: '배송 일괄 생성',
    description: 'Create shipping information for multiple orders.',
    scopeType: 'write',
    method: 'POST',
    path: 'shipments',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'shipments_update_multiple',
    label: '배송 일괄 수정',
    description: 'Update shipping information for multiple orders.',
    scopeType: 'write',
    method: 'PUT',
    path: 'shipments',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'subscription_shipments_get',
    label: '정기배송 조회',
    description: 'Retrieve a subscription shipment by subscription_id.',
    scopeType: 'read',
    method: 'GET',
    path: 'subscription/shipments/{subscription_id}',
    requiredFields: ['subscription_id'],
    fields: { subscription_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'subscription_shipments_create',
    label: '정기배송 생성',
    description: 'Create a subscription shipment.',
    scopeType: 'write',
    method: 'POST',
    path: 'subscription/shipments',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'subscription_shipments_update',
    label: '정기배송 수정',
    description: 'Update a subscription shipment by subscription_id.',
    scopeType: 'write',
    method: 'PUT',
    path: 'subscription/shipments/{subscription_id}',
    requiredFields: ['subscription_id'],
    fields: { subscription_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'subscription_shipments_items_update',
    label: '정기배송 상품 옵션 수정',
    description: 'Update product variants in a subscription shipment.',
    scopeType: 'write',
    method: 'PUT',
    path: 'subscription/shipments/{subscription_id}/items',
    requiredFields: ['subscription_id'],
    fields: { subscription_id: { type: 'string', location: 'path' } },
    responseShape: 'single',
  },
  {
    id: 'unpaidorders_list',
    label: '미결제 주문 목록',
    description: 'List unpaid orders.',
    scopeType: 'read',
    method: 'GET',
    path: 'unpaidorders',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
];
