/**
 * Cafe24 Admin API — planned (yet-to-be-implemented) operations.
 *
 * SoT for these rows lives in `spec/conventions/cafe24-api-catalog/<resource>.md`
 * as `status: planned`. This file is the backend mirror that ships through
 * `GET /nodes/definitions` so the frontend Operation select can show
 * 'planned' items as disabled + '지원 예정' badge.
 *
 * Drift is caught by `catalog-sync.spec.ts` — adding/removing a planned row
 * in the catalog MD requires the same change here.
 */

import type { Cafe24Resource } from './types.js';

export interface Cafe24PlannedOperationEntry {
  id: string;
  label: string;
  paginated?: boolean;
}

export const CAFE24_PLANNED_BY_RESOURCE: Record<
  Cafe24Resource,
  readonly Cafe24PlannedOperationEntry[]
> = {
  store: [
    { id: 'points_setting_get', label: '적립금 설정 조회' },
    { id: 'points_setting_update', label: '적립금 설정 수정' },
    { id: 'policy_get', label: '상점 프로필 조회' },
    { id: 'policy_update', label: '상점 프로필 수정' },
    { id: 'privacy_boards_get', label: '게시판 개인정보 정책 조회' },
    { id: 'privacy_boards_update', label: '게시판 개인정보 정책 수정' },
    { id: 'privacy_join_get', label: '회원가입 개인정보 정책 조회' },
    { id: 'privacy_join_update', label: '회원가입 개인정보 정책 수정' },
    { id: 'privacy_orders_get', label: '주문 개인정보 정책 조회' },
    { id: 'privacy_orders_update', label: '주문 개인정보 정책 수정' },
    { id: 'products_display_setting_list', label: '상품 진열 설정 목록' },
    { id: 'products_display_setting_update', label: '상품 진열 설정 수정' },
    {
      id: 'products_properties_setting_get',
      label: '상품 상세 추가 설정 조회',
    },
    {
      id: 'products_properties_setting_update',
      label: '상품 상세 추가 설정 수정',
    },
    { id: 'products_setting_get', label: '상품 설정 조회' },
    { id: 'redirects_list', label: '리다이렉트 목록', paginated: true },
    { id: 'redirects_create', label: '리다이렉트 생성' },
    { id: 'redirects_update', label: '리다이렉트 수정' },
    { id: 'redirects_delete', label: '리다이렉트 삭제' },
    { id: 'restocknotification_setting_get', label: '재입고 알림 설정 조회' },
    {
      id: 'restocknotification_setting_update',
      label: '재입고 알림 설정 수정',
    },
    { id: 'seo_setting_get', label: 'SEO 설정 조회' },
    { id: 'seo_setting_update', label: 'SEO 설정 수정' },
    { id: 'shippingmanager_get', label: '배송 매니저 활성화 정보' },
    { id: 'sms_setting_get', label: 'SMS 설정 조회' },
    { id: 'sms_setting_update', label: 'SMS 설정 수정' },
    { id: 'socials_apple_get', label: 'Apple 로그인 연동 상세' },
    { id: 'socials_apple_settings_get', label: 'Apple 로그인 연동 설정' },
    { id: 'socials_kakaosync_get', label: '카카오 싱크 상세' },
    { id: 'socials_kakaosync_update', label: '카카오 싱크 수정' },
    { id: 'socials_naverlogin_get', label: '네이버 로그인 상세' },
    { id: 'socials_naverlogin_update', label: '네이버 로그인 수정' },
    { id: 'socials_navershopping_get', label: '네이버 쇼핑 설정' },
    { id: 'store_accounts_list', label: '상점 계좌 목록' },
    { id: 'store_dropshipping_get', label: '위탁배송 설정 조회' },
    { id: 'store_dropshipping_manage', label: '위탁배송 설정 관리' },
    { id: 'store_setting_get', label: '상점 보안 설정 조회' },
    { id: 'store_setting_update', label: '상점 보안 설정 수정' },
    {
      id: 'subscription_shipments_setting_list',
      label: '정기배송 상품 목록',
      paginated: true,
    },
    {
      id: 'subscription_shipments_setting_create_rule',
      label: '정기배송 결제 규칙 생성',
    },
    {
      id: 'subscription_shipments_setting_update',
      label: '정기배송 상품 수정',
    },
    {
      id: 'subscription_shipments_setting_delete',
      label: '정기배송 상품 삭제',
    },
    { id: 'taxmanager_get', label: '세금 매니저 활성화 정보' },
    { id: 'users_list', label: '운영자 사용자 목록', paginated: true },
    { id: 'users_get', label: '운영자 사용자 상세' },
  ],
  product: [
    { id: 'product_variants_get', label: '상품 품목 단건 조회' },
    { id: 'product_variants_update', label: '상품 품목 수정' },
    { id: 'product_variants_update_multiple', label: '상품 품목 일괄 수정' },
    { id: 'product_variants_delete', label: '상품 품목 삭제' },
    { id: 'product_variants_inventory_get', label: '상품 품목 재고 조회' },
    { id: 'product_additionalimages_create', label: '추가 이미지 등록' },
    { id: 'product_additionalimages_update', label: '추가 이미지 수정' },
    { id: 'product_additionalimages_delete', label: '추가 이미지 삭제' },
    { id: 'product_images_upload', label: '상품 이미지 업로드' },
    { id: 'product_images_delete', label: '상품 이미지 삭제' },
    { id: 'product_approve_get', label: '상품 승인 상태 조회' },
    { id: 'product_approve_create', label: '상품 승인 요청' },
    { id: 'product_approve_update', label: '상품 승인 상태 변경' },
    { id: 'product_customproperties_get', label: '상품 사용자 정의 속성 조회' },
    {
      id: 'product_customproperties_update',
      label: '상품 사용자 정의 속성 수정',
    },
    {
      id: 'product_customproperties_delete',
      label: '상품 사용자 정의 속성 삭제',
    },
    {
      id: 'product_decorationimages_list',
      label: '상품 꾸미기 이미지 목록',
      paginated: true,
    },
    { id: 'product_decorationimages_set', label: '상품 꾸미기 이미지 설정' },
    { id: 'product_decorationimages_update', label: '상품 꾸미기 이미지 수정' },
    { id: 'product_decorationimages_delete', label: '상품 꾸미기 이미지 삭제' },
    { id: 'product_discountprice_get', label: '상품 할인가 조회' },
    { id: 'product_hits_count', label: '상품 조회수 카운트' },
    { id: 'product_icons_list', label: '상품 아이콘 목록', paginated: true },
    { id: 'product_icons_set', label: '상품 아이콘 설정' },
    { id: 'product_icons_update', label: '상품 아이콘 수정' },
    { id: 'product_icons_delete', label: '상품 아이콘 삭제' },
    { id: 'product_memos_list', label: '상품 메모 목록', paginated: true },
    { id: 'product_memos_get', label: '상품 메모 단건 조회' },
    { id: 'product_memos_create', label: '상품 메모 생성' },
    { id: 'product_memos_update', label: '상품 메모 수정' },
    { id: 'product_memos_delete', label: '상품 메모 삭제' },
    { id: 'product_tags_list', label: '상품 태그 목록', paginated: true },
    { id: 'product_tags_count', label: '상품 태그 개수' },
    { id: 'product_tags_create', label: '상품 태그 생성' },
    { id: 'product_tags_delete', label: '상품 태그 삭제' },
    { id: 'bundleproducts_list', label: '묶음 상품 목록', paginated: true },
    { id: 'bundleproducts_get', label: '묶음 상품 단건 조회' },
    { id: 'bundleproducts_create', label: '묶음 상품 생성' },
    { id: 'bundleproducts_update', label: '묶음 상품 수정' },
    { id: 'bundleproducts_delete', label: '묶음 상품 삭제' },
    { id: 'categories_products_count', label: '카테고리 내 상품 개수' },
    { id: 'categories_products_add', label: '카테고리에 상품 추가' },
    { id: 'categories_products_update', label: '카테고리 상품 수정' },
    { id: 'categories_products_delete', label: '카테고리 상품 삭제' },
    {
      id: 'mains_products_list',
      label: '메인 카테고리 상품 목록',
      paginated: true,
    },
    { id: 'mains_products_count', label: '메인 카테고리 상품 개수' },
    { id: 'mains_products_set', label: '메인 카테고리 상품 설정' },
    {
      id: 'mains_products_update_sorting',
      label: '메인 카테고리 상품 정렬 수정',
    },
    { id: 'mains_products_delete', label: '메인 카테고리 상품 삭제' },
  ],
  order: [
    { id: 'order_autocalculation_delete', label: '주문 자동 계산 해제' },
    { id: 'order_buyer_get', label: '주문자 정보 조회' },
    { id: 'order_buyer_history_list', label: '주문자 정보 변경 이력' },
    { id: 'order_cancellation_create', label: '주문 취소 생성' },
    { id: 'order_cancellation_update', label: '주문 취소 상세 변경' },
    { id: 'order_completions_complete', label: 'PG 결제 후 주문 완료' },
    { id: 'order_exchange_create', label: '주문 교환 생성' },
    { id: 'order_exchange_update', label: '주문 교환 수정' },
    { id: 'order_exchangerequests_reject', label: '교환 요청 반려' },
    { id: 'order_items_create', label: '주문 상품 추가' },
    { id: 'order_items_update', label: '주문 상품 수정' },
    { id: 'order_items_labels_get', label: '주문 상품 라벨 조회' },
    { id: 'order_items_labels_create', label: '주문 상품 라벨 생성' },
    { id: 'order_items_labels_update', label: '주문 상품 라벨 수정' },
    { id: 'order_items_labels_delete', label: '주문 상품 라벨 삭제' },
    { id: 'order_items_options_create', label: '주문 상품 옵션 생성' },
    { id: 'order_items_options_update', label: '주문 상품 옵션 수정' },
    { id: 'order_memos_list', label: '주문 메모 목록' },
    { id: 'order_memos_update', label: '주문 메모 수정' },
    { id: 'order_memos_delete', label: '주문 메모 삭제' },
    { id: 'order_payments_status_update', label: '주문 결제 상태 수정' },
    { id: 'order_paymenttimeline_history', label: '결제 이력 조회' },
    { id: 'order_paymenttimeline_details', label: '결제 상세 조회' },
    { id: 'order_receivers_list', label: '받는 사람 목록' },
    { id: 'order_receivers_update', label: '받는 사람 수정' },
    { id: 'order_receivers_change_shipping', label: '받는 사람 배송지 변경' },
    { id: 'order_receivers_history_list', label: '받는 사람 변경 이력' },
    { id: 'order_refunds_update', label: '주문 환불 수정' },
    { id: 'order_return_create', label: '주문 반품 생성' },
    { id: 'order_return_update', label: '주문 반품 수정' },
    { id: 'order_shipments_list', label: '주문 배송 정보 목록' },
    { id: 'order_shipments_update', label: '주문 배송 정보 수정' },
    { id: 'order_shipments_delete', label: '주문 배송 정보 삭제' },
    { id: 'order_shippingfeecancellation_get', label: '배송비 취소 상세' },
    { id: 'order_shippingfeecancellation_create', label: '배송비 취소 생성' },
    { id: 'order_shortagecancellation_create', label: '재고 부족 취소 생성' },
    { id: 'orders_benefits_list', label: '주문 혜택 목록' },
    { id: 'orders_calculation_total', label: '주문 결제 금액 계산' },
    { id: 'orders_coupons_list', label: '주문 쿠폰 목록' },
    { id: 'orders_dashboard_list', label: '주문 대시보드' },
    {
      id: 'orders_inflowgroups_list',
      label: '유입 그룹 목록',
      paginated: true,
    },
    { id: 'orders_inflowgroups_create', label: '유입 그룹 생성' },
    { id: 'orders_inflowgroups_update', label: '유입 그룹 수정' },
    { id: 'orders_inflowgroups_delete', label: '유입 그룹 삭제' },
    { id: 'orders_inflows_list', label: '유입 출처 목록', paginated: true },
    { id: 'orders_inflows_create', label: '유입 출처 생성' },
    { id: 'orders_inflows_update', label: '유입 출처 수정' },
    { id: 'orders_inflows_delete', label: '유입 출처 삭제' },
    { id: 'orders_memos_list', label: '관리자 메모 목록' },
    { id: 'orders_migrations_get', label: '이관 주문 조회' },
    { id: 'orders_migrations_create', label: '이관 주문 생성' },
    { id: 'orders_migrations_update', label: '이관 주문 수정' },
    { id: 'orders_migrations_delete', label: '이관 주문 삭제' },
    { id: 'orders_paymentamount_get', label: '결제 금액 조회' },
    {
      id: 'orders_saleschannels_list',
      label: '판매 채널 목록',
      paginated: true,
    },
    { id: 'orders_saleschannels_create', label: '판매 채널 생성' },
    { id: 'orders_saleschannels_update', label: '판매 채널 수정' },
    { id: 'orders_saleschannels_delete', label: '판매 채널 삭제' },
    { id: 'payments_status_update_multiple', label: '결제 상태 일괄 변경' },
    { id: 'reservations_get', label: '예약 상품 조회' },
    { id: 'return_update', label: '반품 수정' },
    { id: 'returnrequests_create', label: '반품 요청 생성' },
    { id: 'returnrequests_reject', label: '반품 요청 거부' },
    { id: 'cancellation_update_bulk', label: '취소 상세 일괄 변경' },
    { id: 'cancellationrequests_create', label: '취소 요청 생성' },
    { id: 'cancellationrequests_reject', label: '취소 요청 거부' },
    { id: 'cashreceipt_list', label: '현금영수증 목록', paginated: true },
    { id: 'cashreceipt_create', label: '현금영수증 발행' },
    { id: 'cashreceipt_update', label: '현금영수증 수정' },
    { id: 'cashreceipt_cancel', label: '현금영수증 취소' },
    { id: 'collectrequests_update', label: '수거 요청 수정' },
    { id: 'control', label: '주문 컨트롤' },
    { id: 'exchange_update_multiple', label: '교환 일괄 수정' },
    { id: 'exchangerequests_create_bulk', label: '교환 요청 일괄 생성' },
    { id: 'exchangerequests_reject_multiple', label: '교환 요청 일괄 거부' },
    { id: 'fulfillments_create', label: '풀필먼트 배송 생성' },
    { id: 'labels_list', label: '주문 라벨 목록' },
    { id: 'labels_create_multiple', label: '주문 라벨 일괄 생성' },
    { id: 'orderform_properties_get', label: '주문서 추가 필드 조회' },
    { id: 'orderform_properties_create', label: '주문서 추가 필드 생성' },
    { id: 'orderform_properties_update', label: '주문서 추가 필드 수정' },
    { id: 'orderform_properties_delete', label: '주문서 추가 필드 삭제' },
    { id: 'shipments_create_multiple', label: '배송 일괄 생성' },
    { id: 'shipments_update_multiple', label: '배송 일괄 수정' },
    { id: 'subscription_shipments_get', label: '정기배송 조회' },
    { id: 'subscription_shipments_create', label: '정기배송 생성' },
    { id: 'subscription_shipments_update', label: '정기배송 수정' },
    {
      id: 'subscription_shipments_items_update',
      label: '정기배송 상품 옵션 수정',
    },
    { id: 'unpaidorders_list', label: '미결제 주문 목록', paginated: true },
  ],
  customer: [],
  community: [],
  design: [],
  promotion: [],
  application: [],
  category: [],
  collection: [],
  supply: [],
  shipping: [],
  salesreport: [],
  personal: [],
  privacy: [],
  mileage: [],
  notification: [],
  translation: [],
};
