import type { Cafe24OperationMetadata } from './types.js';

export const productOperations: Cafe24OperationMetadata[] = [
  {
    id: 'product_list',
    label: '상품 목록 조회',
    description:
      'List products in the mall. Supports filtering by category, display status, date range, price range.',
    scopeType: 'read',
    method: 'GET',
    path: 'products',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        description: 'Multi-shop number (default 1)',
        default: 1,
      },
      category_no: {
        type: 'number',
        location: 'query',
        description: 'Filter by category number',
      },
      display: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Display on/off (T=on, F=off)',
      },
      selling: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Selling on/off',
      },
      since: {
        type: 'string',
        location: 'query',
        description:
          'ISO8601 datetime (KST, UTC+9) — created_after. Cafe24 interprets naive ISO as KST.',
      },
      until: {
        type: 'string',
        location: 'query',
        description:
          'ISO8601 datetime (KST, UTC+9) — created_before. Cafe24 interprets naive ISO as KST.',
      },
      product_name: {
        type: 'string',
        location: 'query',
        description: 'Filter by product name (partial match)',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'product_get',
    label: '상품 단건 조회',
    description: 'Get a single product by product_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'product_create',
    label: '상품 생성',
    description:
      'Create a new product. Required fields vary by mall settings; refer to Cafe24 docs for the full field list.',
    scopeType: 'write',
    method: 'POST',
    path: 'products',
    requiredFields: ['product_name', 'price', 'supply_price'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      product_name: { type: 'string', location: 'body' },
      price: {
        type: 'string',
        location: 'body',
        description: 'Decimal string (KRW)',
      },
      supply_price: { type: 'string', location: 'body' },
      display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'T',
      },
      selling: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'T',
      },
      description: { type: 'string', location: 'body' },
      category_no: { type: 'array', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_update',
    label: '상품 수정',
    description:
      'Update a product (name, price, display, selling, description, ...).',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      product_name: { type: 'string', location: 'body' },
      price: { type: 'string', location: 'body' },
      display: { type: 'enum', location: 'body', enum: ['T', 'F'] },
      selling: { type: 'enum', location: 'body', enum: ['T', 'F'] },
      description: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_delete',
    label: '상품 삭제',
    description: 'Delete a product by product_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/{product_no}',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_variants_list',
    label: '상품 품목(옵션) 목록 조회',
    description: 'List variants (option combinations) for a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/variants',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'product_variants_inventory_update',
    label: '상품 품목 재고 수정',
    description: 'Update inventory quantity for a specific variant.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/variants/{variant_code}/inventories',
    requiredFields: ['product_no', 'variant_code', 'quantity'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      variant_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      quantity: { type: 'number', location: 'body' },
      use_inventory: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'B', 'C'],
        description: 'Inventory control mode',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'product_count',
    label: '상품 개수 조회',
    description:
      'Retrieve the total count of products matching the supplied filters. Cafe24 docs surface count-specific URL as the sibling `/count` path of the list endpoint, mirroring `order_count`.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      category_no: {
        type: 'number',
        location: 'query',
        description: 'Filter by category number',
      },
      display: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Display on/off (T=on, F=off)',
      },
      selling: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Selling on/off',
      },
      product_name: {
        type: 'string',
        location: 'query',
        description: 'Filter by product name (partial match)',
      },
      since: {
        type: 'string',
        location: 'query',
        description:
          'ISO8601 datetime (KST, UTC+9) — created_after. Cafe24 interprets naive ISO as KST.',
      },
      until: {
        type: 'string',
        location: 'query',
        description:
          'ISO8601 datetime (KST, UTC+9) — created_before. Cafe24 interprets naive ISO as KST.',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'product_options_list',
    label: '상품 옵션 목록 조회',
    description: 'List the option set defined on a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/options',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'product_options_create',
    label: '상품 옵션 생성',
    description:
      'Create a new option on a product (e.g. size, color). `option_values` is the array of selectable values.',
    scopeType: 'write',
    method: 'POST',
    path: 'products/{product_no}/options',
    requiredFields: [
      'product_no',
      'option_name',
      'option_type',
      'option_values',
    ],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
      option_name: { type: 'string', location: 'body' },
      option_type: {
        type: 'string',
        location: 'body',
        description: 'Option widget type (e.g. text, select)',
      },
      option_values: {
        type: 'array',
        location: 'body',
        description: 'Array of selectable option values',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'product_options_update',
    label: '상품 옵션 수정',
    description:
      'Update an existing product option identified by `option_no` (body).',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/options',
    requiredFields: ['product_no', 'option_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
      option_no: { type: 'number', location: 'body' },
      option_name: { type: 'string', location: 'body' },
      option_type: { type: 'string', location: 'body' },
      option_value: { type: 'string', location: 'body' },
      use_option: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Activation status',
      },
      required_option: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Whether selection is mandatory',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'product_options_delete',
    label: '상품 옵션 삭제',
    description: 'Delete a specific product option by `option_no` (path).',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/{product_no}/options/{option_no}',
    requiredFields: ['product_no', 'option_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      option_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_seo_get',
    label: '상품 SEO 설정 조회',
    description:
      "Retrieve a product's SEO meta settings (title / description / keywords / URL path).",
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/seo',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'product_seo_update',
    label: '상품 SEO 설정 수정',
    description:
      "Update a product's SEO meta settings. All body fields are optional — provide only the ones to change.",
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/seo',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
      meta_title: { type: 'string', location: 'body' },
      meta_description: { type: 'string', location: 'body' },
      meta_keyword: { type: 'string', location: 'body' },
      url_path: { type: 'string', location: 'body' },
      seo_title: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  // Batch 2-A — product_variants (5) · product_additionalimages (3) · product_images (2)
  {
    id: 'product_variants_get',
    label: '상품 품목 단건 조회',
    description: 'Retrieve a single product variant.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/variants/{variant_code}',
    requiredFields: ['product_no', 'variant_code'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      variant_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_variants_update',
    label: '상품 품목 수정',
    description: 'Update a single product variant.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/variants/{variant_code}',
    requiredFields: ['product_no', 'variant_code'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      variant_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_variants_update_multiple',
    label: '상품 품목 일괄 수정',
    description: 'Update multiple variants of a product in one call.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/variants',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'list',
  },
  {
    id: 'product_variants_delete',
    label: '상품 품목 삭제',
    description: 'Delete a product variant.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/{product_no}/variants/{variant_code}',
    requiredFields: ['product_no', 'variant_code'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      variant_code: { type: 'string', location: 'path' },
    },
    responseShape: 'empty',
  },
  {
    id: 'product_variants_inventory_get',
    label: '상품 품목 재고 조회',
    description: 'Retrieve inventory details for a product variant.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/variants/{variant_code}/inventories',
    requiredFields: ['product_no', 'variant_code'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      variant_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_additionalimages_create',
    label: '추가 이미지 등록',
    description: 'Register an additional product image.',
    scopeType: 'write',
    method: 'POST',
    path: 'products/{product_no}/additionalimages',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_additionalimages_update',
    label: '추가 이미지 수정',
    description: 'Update additional product images.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/additionalimages',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_additionalimages_delete',
    label: '추가 이미지 삭제',
    description: 'Delete additional product images.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/{product_no}/additionalimages',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'empty',
  },
  {
    id: 'product_images_upload',
    label: '상품 이미지 업로드',
    description: 'Upload product image files.',
    scopeType: 'write',
    method: 'POST',
    path: 'products/images',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'product_images_delete',
    label: '상품 이미지 삭제',
    description: 'Delete product image files.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/images',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'empty',
  },
  // Batch 2-B — product_approve (3) · customproperties (3) · decorationimages (4)
  {
    id: 'product_approve_get',
    label: '상품 승인 상태 조회',
    description: 'Retrieve approval status for a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/approve',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_approve_create',
    label: '상품 승인 요청',
    description: 'Create an approval request for a product.',
    scopeType: 'write',
    method: 'POST',
    path: 'products/{product_no}/approve',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_approve_update',
    label: '상품 승인 상태 변경',
    description: 'Update the approval status of a product.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/approve',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_customproperties_get',
    label: '상품 사용자 정의 속성 조회',
    description: 'Retrieve user-defined custom properties for a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/customproperties',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_customproperties_update',
    label: '상품 사용자 정의 속성 수정',
    description: 'Update user-defined custom properties for a product.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/customproperties',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_customproperties_delete',
    label: '상품 사용자 정의 속성 삭제',
    description: 'Delete user-defined custom properties for a product.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/{product_no}/customproperties',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'empty',
  },
  {
    id: 'product_decorationimages_list',
    label: '상품 꾸미기 이미지 목록',
    description: 'List decoration images attached to a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/decorationimages',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'product_decorationimages_set',
    label: '상품 꾸미기 이미지 설정',
    description: 'Set (create) a decoration image for a product.',
    scopeType: 'write',
    method: 'POST',
    path: 'products/{product_no}/decorationimages',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_decorationimages_update',
    label: '상품 꾸미기 이미지 수정',
    description: 'Update a decoration image of a product.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/decorationimages',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_decorationimages_delete',
    label: '상품 꾸미기 이미지 삭제',
    description: 'Delete a decoration image of a product.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/{product_no}/decorationimages',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'empty',
  },
  // Batch 2-C — product_discountprice · hits · icons (4) · memos (5)
  {
    id: 'product_discountprice_get',
    label: '상품 할인가 조회',
    description: 'Retrieve the discounted price for a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/discountprice',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_hits_count',
    label: '상품 조회수 카운트',
    description: 'Retrieve view-count statistics for a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/hits',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_icons_list',
    label: '상품 아이콘 목록',
    description: 'List icons attached to a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/icons',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'product_icons_set',
    label: '상품 아이콘 설정',
    description: 'Set (create) an icon for a product.',
    scopeType: 'write',
    method: 'POST',
    path: 'products/{product_no}/icons',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_icons_update',
    label: '상품 아이콘 수정',
    description: 'Update icons of a product.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/icons',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_icons_delete',
    label: '상품 아이콘 삭제',
    description: 'Delete an icon of a product by icon_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/{product_no}/icons/{icon_no}',
    requiredFields: ['product_no', 'icon_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      icon_no: { type: 'string', location: 'path' },
    },
    responseShape: 'empty',
  },
  {
    id: 'product_memos_list',
    label: '상품 메모 목록',
    description: 'List memos attached to a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/memos',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'product_memos_get',
    label: '상품 메모 단건 조회',
    description: 'Retrieve a single product memo by memo_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/memos/{memo_no}',
    requiredFields: ['product_no', 'memo_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      memo_no: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_memos_create',
    label: '상품 메모 생성',
    description: 'Create a memo for a product.',
    scopeType: 'write',
    method: 'POST',
    path: 'products/{product_no}/memos',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_memos_update',
    label: '상품 메모 수정',
    description: 'Update a product memo by memo_no.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/memos/{memo_no}',
    requiredFields: ['product_no', 'memo_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      memo_no: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_memos_delete',
    label: '상품 메모 삭제',
    description: 'Delete a product memo by memo_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/{product_no}/memos/{memo_no}',
    requiredFields: ['product_no', 'memo_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      memo_no: { type: 'string', location: 'path' },
    },
    responseShape: 'empty',
  },
  // Batch 2-D — product_tags (4) · bundleproducts (5) · categories_products (4)
  {
    id: 'product_tags_list',
    label: '상품 태그 목록',
    description: 'List tags attached to a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/tags',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'product_tags_count',
    label: '상품 태그 개수',
    description: 'Count tags attached to a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/tags/count',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_tags_create',
    label: '상품 태그 생성',
    description: 'Create one or more tags for a product.',
    scopeType: 'write',
    method: 'POST',
    path: 'products/{product_no}/tags',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_tags_delete',
    label: '상품 태그 삭제',
    description: 'Delete a product tag by tag_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/{product_no}/tags/{tag_no}',
    requiredFields: ['product_no', 'tag_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      tag_no: { type: 'string', location: 'path' },
    },
    responseShape: 'empty',
  },
  {
    id: 'bundleproducts_list',
    label: '묶음 상품 목록',
    description: 'List bundle products.',
    scopeType: 'read',
    method: 'GET',
    path: 'bundleproducts',
    requiredFields: [],
    fields: {
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'bundleproducts_get',
    label: '묶음 상품 단건 조회',
    description: 'Retrieve a single bundle product by product_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'bundleproducts/{product_no}',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'bundleproducts_create',
    label: '묶음 상품 생성',
    description: 'Create a bundle product.',
    scopeType: 'write',
    method: 'POST',
    path: 'bundleproducts',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'bundleproducts_update',
    label: '묶음 상품 수정',
    description: 'Update a bundle product.',
    scopeType: 'write',
    method: 'PUT',
    path: 'bundleproducts/{product_no}',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'bundleproducts_delete',
    label: '묶음 상품 삭제',
    description: 'Delete a bundle product.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'bundleproducts/{product_no}',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'empty',
  },
  {
    id: 'categories_products_count',
    label: '카테고리 내 상품 개수',
    description: 'Count products belonging to a category.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/{category_no}/products/count',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'categories_products_add',
    label: '카테고리에 상품 추가',
    description: 'Add products to a category.',
    scopeType: 'write',
    method: 'POST',
    path: 'categories/{category_no}/products',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'categories_products_update',
    label: '카테고리 상품 수정',
    description: 'Update products attached to a category.',
    scopeType: 'write',
    method: 'PUT',
    path: 'categories/{category_no}/products',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'categories_products_delete',
    label: '카테고리 상품 삭제',
    description: 'Delete products from a category.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'categories/{category_no}/products',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
    },
    responseShape: 'empty',
  },
];
