import type { Cafe24OperationMetadata } from './types.js';

export const productOperations: Cafe24OperationMetadata[] = [
  {
    id: 'product_list',
    label: '상품 목록 조회',
    description:
      'List products in the mall. Supports filtering by category, display status, date range, price range.',
    scopeType: 'read',
    method: 'GET',
    path: 'products',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        description: 'Multi-shop number (default 1)',
        default: 1,
      },
      category_no: {
        type: 'number',
        location: 'query',
        description: 'Filter by category number',
      },
      display: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Display on/off (T=on, F=off)',
      },
      selling: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Selling on/off',
      },
      since: {
        type: 'string',
        location: 'query',
        description:
          'ISO8601 datetime (KST, UTC+9) — created_after. Naive ISO 도 Cafe24 가 KST 로 해석',
      },
      until: {
        type: 'string',
        location: 'query',
        description:
          'ISO8601 datetime (KST, UTC+9) — created_before. Naive ISO 도 Cafe24 가 KST 로 해석',
      },
      product_name: {
        type: 'string',
        location: 'query',
        description: 'Filter by product name (partial match)',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'product_get',
    label: '상품 단건 조회',
    description: 'Get a single product by product_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'product_create',
    label: '상품 생성',
    description:
      'Create a new product. Required fields vary by mall settings; refer to Cafe24 docs for the full field list.',
    scopeType: 'write',
    method: 'POST',
    path: 'products',
    requiredFields: ['product_name', 'price', 'supply_price'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      product_name: { type: 'string', location: 'body' },
      price: {
        type: 'string',
        location: 'body',
        description: 'Decimal string (KRW)',
      },
      supply_price: { type: 'string', location: 'body' },
      display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'T',
      },
      selling: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'T',
      },
      description: { type: 'string', location: 'body' },
      category_no: { type: 'array', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_update',
    label: '상품 수정',
    description:
      'Update a product (name, price, display, selling, description, ...).',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      product_name: { type: 'string', location: 'body' },
      price: { type: 'string', location: 'body' },
      display: { type: 'enum', location: 'body', enum: ['T', 'F'] },
      selling: { type: 'enum', location: 'body', enum: ['T', 'F'] },
      description: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_delete',
    label: '상품 삭제',
    description: 'Delete a product by product_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/{product_no}',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_variants_list',
    label: '상품 품목(옵션) 목록 조회',
    description: 'List variants (option combinations) for a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/variants',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'product_variants_inventory_update',
    label: '상품 품목 재고 수정',
    description: 'Update inventory quantity for a specific variant.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/variants/{variant_code}/inventories',
    requiredFields: ['product_no', 'variant_code', 'quantity'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      variant_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      quantity: { type: 'number', location: 'body' },
      use_inventory: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'B', 'C'],
        description: 'Inventory control mode',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'product_count',
    label: '상품 개수 조회',
    description:
      'Retrieve the total count of products matching the supplied filters. Cafe24 docs surface count-specific URL as the sibling `/count` path of the list endpoint, mirroring `order_count`.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      category_no: {
        type: 'number',
        location: 'query',
        description: 'Filter by category number',
      },
      display: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Display on/off (T=on, F=off)',
      },
      selling: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Selling on/off',
      },
      product_name: {
        type: 'string',
        location: 'query',
        description: 'Filter by product name (partial match)',
      },
      since: {
        type: 'string',
        location: 'query',
        description:
          'ISO8601 datetime (KST, UTC+9) — created_after. Naive ISO 도 Cafe24 가 KST 로 해석',
      },
      until: {
        type: 'string',
        location: 'query',
        description:
          'ISO8601 datetime (KST, UTC+9) — created_before. Naive ISO 도 Cafe24 가 KST 로 해석',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'product_options_list',
    label: '상품 옵션 목록 조회',
    description: 'List the option set defined on a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/options',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'product_options_create',
    label: '상품 옵션 생성',
    description:
      'Create a new option on a product (e.g. size, color). `option_values` is the array of selectable values.',
    scopeType: 'write',
    method: 'POST',
    path: 'products/{product_no}/options',
    requiredFields: [
      'product_no',
      'option_name',
      'option_type',
      'option_values',
    ],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
      option_name: { type: 'string', location: 'body' },
      option_type: {
        type: 'string',
        location: 'body',
        description: 'Option widget type (e.g. text, select)',
      },
      option_values: {
        type: 'array',
        location: 'body',
        description: 'Array of selectable option values',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'product_options_update',
    label: '상품 옵션 수정',
    description:
      'Update an existing product option identified by `option_no` (body).',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/options',
    requiredFields: ['product_no', 'option_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
      option_no: { type: 'number', location: 'body' },
      option_name: { type: 'string', location: 'body' },
      option_type: { type: 'string', location: 'body' },
      option_value: { type: 'string', location: 'body' },
      use_option: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Activation status',
      },
      required_option: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Whether selection is mandatory',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'product_options_delete',
    label: '상품 옵션 삭제',
    description: 'Delete a specific product option by `option_no` (path).',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/{product_no}/options/{option_no}',
    requiredFields: ['product_no', 'option_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      option_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_seo_get',
    label: '상품 SEO 설정 조회',
    description:
      "Retrieve a product's SEO meta settings (title / description / keywords / URL path).",
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/seo',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'product_seo_update',
    label: '상품 SEO 설정 수정',
    description:
      "Update a product's SEO meta settings. All body fields are optional — provide only the ones to change.",
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/seo',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
      meta_title: { type: 'string', location: 'body' },
      meta_description: { type: 'string', location: 'body' },
      meta_keyword: { type: 'string', location: 'body' },
      url_path: { type: 'string', location: 'body' },
      seo_title: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
];
