import type { Cafe24OperationMetadata } from './types.js';
import {
  CAFE24_DATETIME_FIELD_START,
  CAFE24_DATETIME_FIELD_END,
} from './date-descriptions.js';

export const promotionOperations: Cafe24OperationMetadata[] = [
  {
    id: 'coupon_list',
    label: '쿠폰 목록 조회',
    description: 'List coupons available in the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      coupon_type: { type: 'string', location: 'query' },
      issue_type: {
        type: 'enum',
        location: 'query',
        enum: ['M', 'D', 'O', 'A', 'R'],
        description:
          'M=manual, D=download, O=auto-give, A=action, R=re-engagement',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  // ⚠ coupon_get / coupon_delete — cafe24 admin docs (Latest 2026-03-01)
  // 는 `GET/DELETE coupons/{coupon_no}` 를 노출하지 않는다 (PUT 만 — 즉
  // `coupon_manage`). 본 row 들은 seed 이며 cafe24 wire 상 실제 동작 여부
  // 미확인. 운영 검증 / 제거 결정은 `cafe24-backlog-residual.md §G-2` 트랙.
  {
    id: 'coupon_get',
    label: '쿠폰 단건 조회',
    description:
      'Get a single coupon by coupon_no. ⚠ Not documented in cafe24 admin docs (Latest 2026-03-01); kept for backwards compatibility pending production verification.',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons/{coupon_no}',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'coupon_create',
    label: '쿠폰 생성',
    description: 'Create a new coupon.',
    scopeType: 'write',
    method: 'POST',
    path: 'coupons',
    requiredFields: ['coupon_name', 'benefit_type', 'benefit_amount'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      coupon_name: { type: 'string', location: 'body' },
      benefit_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'B', 'C', 'D'],
        description: 'A=discount price, B=discount %, C=shipping, D=points',
      },
      benefit_amount: { type: 'string', location: 'body' },
      issue_type: {
        type: 'enum',
        location: 'body',
        enum: ['M', 'D', 'O', 'A', 'R'],
      },
      issued_count: { type: 'number', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'coupon_issue',
    label: '쿠폰 발급',
    description: 'Issue a coupon to specified members.',
    scopeType: 'write',
    method: 'POST',
    path: 'coupons/{coupon_no}/issues',
    requiredFields: ['coupon_no', 'issued_member_scope'],
    fields: {
      coupon_no: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      issued_member_scope: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'M', 'G'],
        description: 'A=all, M=specific members, G=group',
      },
      member_ids: { type: 'array', location: 'body' },
      group_no: { type: 'number', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'coupon_delete',
    label: '쿠폰 삭제',
    description:
      'Delete a coupon by coupon_no. ⚠ Not documented in cafe24 admin docs (Latest 2026-03-01); kept for backwards compatibility pending production verification.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'coupons/{coupon_no}',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'coupon_count',
    label: '쿠폰 개수 조회',
    description:
      'Retrieve the total count of coupons. Sibling of coupon_list (paginated).',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'coupon_issues_list',
    label: '발급 쿠폰 목록 조회',
    description:
      'List the issuance records of a coupon (who received it, when).',
    scopeType: 'read',
    method: 'GET',
    // cafe24 docs path: `coupons/{coupon_no}/issues` (coupon-scoped, not
    // `coupons/issues` with query param).
    path: 'coupons/{coupon_no}/issues',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'coupon_issuance_customers_list',
    label: '쿠폰 발급 대상 회원 목록',
    description:
      'List customers eligible for conditional issuance of a coupon.',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons/{coupon_no}/issuancecustomers',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'customers_coupons_list',
    label: '회원별 쿠폰 목록',
    description:
      'List the coupons a customer holds. Uses the codebase-wide `member_id` path placeholder (Cafe24 docs call this `customer_no`).',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/coupons',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'customers_coupons_count',
    label: '회원별 쿠폰 개수',
    description: 'Retrieve the count of coupons a customer holds.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/coupons/count',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'serialcoupons_list',
    label: '시리얼 쿠폰 코드 조회',
    description:
      'Retrieve the generated serial coupon codes for a coupon (paginated by limit/offset).',
    scopeType: 'read',
    method: 'GET',
    path: 'serialcoupons',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'number', location: 'query' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'serialcoupons_generate',
    label: '시리얼 쿠폰 코드 생성',
    description:
      'Generate a batch of serial coupon codes. `coupon_no` + `quantity` in body.',
    scopeType: 'write',
    method: 'POST',
    // cafe24 docs path: `serialcoupons` (POST — coupon_no goes in body, not
    // path. anchor `generate-coupon-code`).
    path: 'serialcoupons',
    requiredFields: ['coupon_no', 'quantity'],
    fields: {
      coupon_no: { type: 'number', location: 'body' },
      quantity: { type: 'number', location: 'body' },
      prefix: { type: 'string', location: 'body' },
      suffix: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'serialcoupons_delete',
    label: '시리얼 쿠폰 코드 삭제',
    description:
      'Delete serial coupon codes for a coupon. (Specific code filtering via query/body per cafe24 docs.)',
    scopeType: 'write',
    method: 'DELETE',
    // cafe24 docs path: `serialcoupons/{coupon_no}` (no `/{code}` path
    // segment — specific-code targeting goes through body/query).
    path: 'serialcoupons/{coupon_no}',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'serialcoupons_issues_get',
    label: '시리얼 쿠폰 발급 코드 조회',
    description: 'List the issued/used codes for a serial coupon.',
    scopeType: 'read',
    method: 'GET',
    path: 'serialcoupons/{coupon_no}/issues',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'number', location: 'path' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'serialcoupons_issues_register',
    label: '시리얼 쿠폰 발급 코드 등록',
    description: 'Register a specific code into the serial coupon issued set.',
    scopeType: 'write',
    method: 'POST',
    path: 'serialcoupons/{coupon_no}/issues',
    requiredFields: ['coupon_no', 'code'],
    fields: {
      coupon_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      code: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  // Phase 6c — benefits CRUD + customerevents + customers_coupons_delete
  {
    id: 'benefits_list',
    label: '회원 혜택 목록',
    description: 'List the customer-benefit campaigns configured on the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'benefits',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'benefits_count',
    label: '회원 혜택 개수',
    description: 'Retrieve the count of configured customer benefits.',
    scopeType: 'read',
    method: 'GET',
    path: 'benefits/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'benefits_get',
    label: '회원 혜택 단건 조회',
    description: 'Retrieve a single customer benefit by benefit_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'benefits/{benefit_no}',
    requiredFields: ['benefit_no'],
    fields: {
      benefit_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'benefits_create',
    label: '회원 혜택 생성',
    description:
      'Create a customer-benefit campaign. Required: benefit_name, benefit_type, start_date, end_date, benefit_scope.',
    scopeType: 'write',
    method: 'POST',
    path: 'benefits',
    requiredFields: [
      'benefit_name',
      'benefit_type',
      'start_date',
      'end_date',
      'benefit_scope',
    ],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      benefit_name: { type: 'string', location: 'body' },
      benefit_type: {
        type: 'string',
        location: 'body',
        description:
          'Benefit type (e.g. period_discount, repurchase_discount, bulk_purchase_discount)',
      },
      start_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_START,
      },
      end_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_END,
      },
      benefit_scope: {
        type: 'string',
        location: 'body',
        description:
          'Scope (all products / specific category / specific products)',
      },
      benefit_description: { type: 'string', location: 'body' },
      discount_amount: { type: 'number', location: 'body' },
      discount_rate: { type: 'number', location: 'body' },
      minimum_purchase_amount: { type: 'number', location: 'body' },
      maximum_discount_amount: { type: 'number', location: 'body' },
      member_group_no: { type: 'number', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'benefits_update',
    label: '회원 혜택 수정',
    description:
      'Update a customer-benefit campaign by benefit_no. Body fields are partial — provide only the ones to change.',
    scopeType: 'write',
    method: 'PUT',
    path: 'benefits/{benefit_no}',
    requiredFields: ['benefit_no'],
    fields: {
      benefit_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      benefit_name: { type: 'string', location: 'body' },
      benefit_description: { type: 'string', location: 'body' },
      start_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_START,
      },
      end_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_END,
      },
      discount_amount: { type: 'number', location: 'body' },
      discount_rate: { type: 'number', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'benefits_delete',
    label: '회원 혜택 삭제',
    description: 'Delete a customer-benefit campaign by benefit_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'benefits/{benefit_no}',
    requiredFields: ['benefit_no'],
    fields: {
      benefit_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'customerevents_get',
    label: '회원 정보 이벤트 조회',
    description: 'Retrieve the current member-information-update event status.',
    scopeType: 'read',
    method: 'GET',
    path: 'customerevents',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customerevents_create',
    label: '회원 정보 이벤트 생성',
    description:
      'Create a member-information-modification campaign event. Refer to Cafe24 docs for the full body schema (event period, reward, target tier, ...).',
    scopeType: 'write',
    method: 'POST',
    path: 'customerevents',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      start_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_START,
      },
      end_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_END,
      },
      event_name: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'customerevents_update_status',
    label: '회원 정보 이벤트 상태 수정',
    description:
      'Update the run-status of the member-information-update event.',
    scopeType: 'write',
    method: 'PUT',
    path: 'customerevents',
    requiredFields: ['status'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      status: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Run flag (T=running, F=paused)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'customers_coupons_delete',
    label: '회원 쿠폰 삭제',
    description:
      'Remove a coupon from a customer. Uses codebase `member_id` placeholder (Cafe24 docs: customer_no).',
    scopeType: 'write',
    method: 'DELETE',
    path: 'customers/{member_id}/coupons/{coupon_no}',
    requiredFields: ['member_id', 'coupon_no'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      coupon_no: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  // Phase 7a — discountcodes CRUD + commonevents CRUD
  {
    id: 'discountcodes_list',
    label: '할인 코드 목록',
    description: 'List discount codes for the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'discountcodes',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'discountcodes_get',
    label: '할인 코드 단건 조회',
    description: 'Retrieve a discount code by discount_code_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'discountcodes/{discount_code_no}',
    requiredFields: ['discount_code_no'],
    fields: {
      discount_code_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'discountcodes_create',
    label: '할인 코드 생성',
    description:
      'Create a discount code. Body fields are partial — refer to Cafe24 docs for the discount type / amount schema.',
    scopeType: 'write',
    method: 'POST',
    path: 'discountcodes',
    requiredFields: ['discount_code'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      discount_code: { type: 'string', location: 'body' },
      discount_name: { type: 'string', location: 'body' },
      discount_type: {
        type: 'string',
        location: 'body',
        description: 'Discount type (e.g. amount, rate)',
      },
      discount_amount: { type: 'number', location: 'body' },
      discount_rate: { type: 'number', location: 'body' },
      start_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_START,
      },
      end_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_END,
      },
    },
    responseShape: 'single',
  },
  {
    id: 'discountcodes_update',
    label: '할인 코드 수정',
    description: 'Update a discount code by discount_code_no (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'discountcodes/{discount_code_no}',
    requiredFields: ['discount_code_no'],
    fields: {
      discount_code_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      discount_name: { type: 'string', location: 'body' },
      discount_amount: { type: 'number', location: 'body' },
      discount_rate: { type: 'number', location: 'body' },
      start_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_START,
      },
      end_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_END,
      },
    },
    responseShape: 'single',
  },
  {
    id: 'discountcodes_delete',
    label: '할인 코드 삭제',
    description: 'Delete a discount code by discount_code_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'discountcodes/{discount_code_no}',
    requiredFields: ['discount_code_no'],
    fields: {
      discount_code_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'commonevents_list',
    label: '전체 이벤트 목록',
    description: 'List storewide promotions / events.',
    scopeType: 'read',
    method: 'GET',
    path: 'commonevents',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'commonevents_create',
    label: '전체 이벤트 생성',
    description:
      'Create a storewide promotion. Body fields are partial — see Cafe24 docs.',
    scopeType: 'write',
    method: 'POST',
    path: 'commonevents',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      event_name: { type: 'string', location: 'body' },
      start_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_START,
      },
      end_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_END,
      },
    },
    responseShape: 'single',
  },
  {
    id: 'commonevents_update',
    label: '전체 이벤트 수정',
    description: 'Update a storewide promotion by event_no.',
    scopeType: 'write',
    method: 'PUT',
    path: 'commonevents/{event_no}',
    requiredFields: ['event_no'],
    fields: {
      event_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      event_name: { type: 'string', location: 'body' },
      start_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_START,
      },
      end_date: {
        type: 'string',
        location: 'body',
        description: CAFE24_DATETIME_FIELD_END,
      },
    },
    responseShape: 'single',
  },
  {
    id: 'commonevents_delete',
    label: '전체 이벤트 삭제',
    description: 'Delete a storewide promotion by event_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'commonevents/{event_no}',
    requiredFields: ['event_no'],
    fields: {
      event_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  // Phase 8b — Promotion 완성 (coupon_manage)
  {
    id: 'coupon_manage',
    label: '쿠폰 관리 (사용/중지)',
    description: 'Manage a coupon — pause or resume it via `use_coupon` enum.',
    scopeType: 'write',
    method: 'PUT',
    path: 'coupons/{coupon_no}',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      use_coupon: { type: 'enum', location: 'body', enum: ['T', 'F'] },
    },
    responseShape: 'single',
  },
];
