import type { Cafe24OperationMetadata } from './types.js';
import {
  CAFE24_DATE_FIELD_CREATED_START,
  CAFE24_DATE_FIELD_CREATED_END,
} from './date-descriptions.js';

/**
 * Cafe24 `promotion` resource metadata.
 *
 * G-1-remaining (plan `cafe24-backlog-residual.md` §G-1-remaining): field-set 을
 * 공식 docs 카탈로그(`spec/conventions/cafe24-api-catalog/promotion/*.md` 의 각
 * operation `요청 파라미터` 표)와 **전량 미러**했다. 필드명은 docs Parameter 를
 * 그대로 사용한다 — 핸들러가 field key 를 query/body 파라미터명으로 그대로 전송하므로
 * (`cafe24.handler.ts` buildRequest), docs 명이 아닌 alias 는 Cafe24 가 인식하지 못한다.
 *
 * 규칙:
 * - `offset`/`limit` 은 field 로 넣지 않는다 — paginated op 는 핸들러 pagination 층이 주입.
 * - `requiredFields` 는 기존 계약 ∩ 신규 fields keys 로 보존한다 (metadata.spec subset 불변식).
 * - date/time 필드 description 은 §5.2 (KST / YYYY-MM-DD 명시).
 * - coupon 발급/사용 일시(issue/available datetime)는 inline (KST, UTC+9) 리터럴 사용.
 */
export const promotionOperations: Cafe24OperationMetadata[] = [
  {
    id: 'coupon_list',
    description: 'List coupons available in the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      coupon_no: { type: 'string', location: 'query' },
      coupon_type: {
        type: 'enum',
        location: 'query',
        enum: ['O', 'S'],
        description: 'O=online coupon, S=offline serial coupon',
      },
      coupon_name: { type: 'string', location: 'query' },
      benefit_type: {
        type: 'string',
        location: 'query',
        description:
          'Benefit type (comma-separated). A/B/C/D/E/I/H/J/F/G codes',
      },
      issue_type: {
        type: 'string',
        location: 'query',
        description:
          'Issue type (comma-separated). M=target-assign, A=conditional-auto, D=download, R=recurring-auto',
      },
      issue_sub_type: {
        type: 'string',
        location: 'query',
        description: 'Issue sub-type code',
      },
      issued_flag: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Has issuance history (T/F)',
      },
      created_start_date: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_CREATED_START,
      },
      created_end_date: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_CREATED_END,
      },
      deleted: {
        type: 'string',
        location: 'query',
        description: 'Deleted flag (comma-separated). T=deleted, F=not deleted',
      },
      pause_begin_date: {
        type: 'string',
        location: 'query',
        description: 'Issuance-pause range start (YYYY-MM-DD, KST)',
      },
      pause_end_date: {
        type: 'string',
        location: 'query',
        description: 'Issuance-pause range end (YYYY-MM-DD, KST)',
      },
      issue_order_path: {
        type: 'enum',
        location: 'query',
        enum: ['W', 'M', 'P'],
        description: 'Order path W=PC, M=mobile, P=brand-app',
      },
      issue_order_type: {
        type: 'enum',
        location: 'query',
        enum: ['P', 'O'],
        description: 'Issue unit P=product, O=order-sheet',
      },
      issue_reserved: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Auto-issuance reservation used (T/F)',
      },
      available_period_type: {
        type: 'string',
        location: 'query',
        description:
          'Usage-period type (comma-separated). F=fixed, R=from-issue, M=until-month-end',
      },
      available_datetime: {
        type: 'string',
        location: 'query',
        description:
          'Coupons issuable on this date (YYYY-MM-DD, KST); valid only when available_period_type=F',
      },
      available_site: {
        type: 'enum',
        location: 'query',
        enum: ['W', 'M', 'P'],
        description: 'Usage scope W=web, M=mobile, P=brand-app',
      },
      available_scope: {
        type: 'enum',
        location: 'query',
        enum: ['P', 'O'],
        description: 'Apply scope P=product, O=order-sheet',
      },
      available_price_type: {
        type: 'enum',
        location: 'query',
        enum: ['U', 'O', 'P'],
        description: 'Price-basis U=none, O=order-amount, P=product-amount',
      },
      available_order_price_type: {
        type: 'enum',
        location: 'query',
        enum: ['U', 'I'],
        description: 'Price detail U=all-products, I=coupon-products',
      },
    },
    responseShape: 'list',
    paginated: true,
    constraints: [
      { kind: 'allOrNone', fields: ['created_start_date', 'created_end_date'] },
    ],
  },
  {
    id: 'coupon_create',
    description: 'Create a new coupon.',
    scopeType: 'write',
    method: 'POST',
    path: 'coupons',
    requiredFields: [
      'coupon_name',
      'benefit_type',
      'issue_type',
      'available_period_type',
      'available_site',
      'available_coupon_count_by_order',
    ],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      coupon_name: { type: 'string', location: 'body' },
      benefit_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'B', 'C', 'D', 'E', 'I', 'H', 'J', 'F'],
        description: 'Benefit type A=amount, B=rate, C=points, D=point-rate, …',
      },
      issue_type: {
        type: 'enum',
        location: 'body',
        enum: ['M', 'A', 'D', 'R'],
        description:
          'Issue type M=target-assign, A=conditional-auto, D=download, R=recurring-auto',
      },
      issue_sub_type: {
        type: 'string',
        location: 'body',
        description: 'Issue sub-type code',
      },
      available_period_type: {
        type: 'enum',
        location: 'body',
        enum: ['F', 'R', 'M'],
        description:
          'Usage-period type F=fixed, R=from-issue, M=until-month-end',
      },
      available_site: {
        type: 'enum',
        location: 'body',
        enum: ['W', 'M', 'P'],
        description: 'Usage scope W=web, M=mobile, P=brand-app',
      },
      available_scope: {
        type: 'enum',
        location: 'body',
        enum: ['P', 'O'],
        default: 'O',
        description: 'Apply scope P=product, O=order-sheet',
      },
      available_product: {
        type: 'enum',
        location: 'body',
        enum: ['U', 'I', 'E'],
        default: 'U',
        description: 'Product select U=none, I=include, E=exclude',
      },
      available_category: {
        type: 'enum',
        location: 'body',
        enum: ['U', 'I', 'E'],
        default: 'U',
        description: 'Category select U=none, I=include, E=exclude',
      },
      available_amount_type: {
        type: 'enum',
        location: 'body',
        enum: ['E', 'I'],
        default: 'E',
        description: 'Calc basis E=before-discount, I=after-discount',
      },
      available_coupon_count_by_order: {
        type: 'number',
        location: 'body',
        description: 'Max same-coupon uses per order',
      },
      available_begin_datetime: {
        type: 'string',
        location: 'body',
        description:
          'Usage start datetime (KST, UTC+9); required when available_period_type=F',
      },
      available_end_datetime: {
        type: 'string',
        location: 'body',
        description:
          'Usage end datetime (KST, UTC+9); required when available_period_type=F',
      },
      available_day_from_issued: {
        type: 'number',
        location: 'body',
        description: 'Usable days from issue; required when period_type=R',
      },
      issue_member_join: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Issue on member join (T/F)',
      },
      issue_member_join_recommend: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Issue to recommender on join (T/F)',
      },
      issue_member_join_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'O', 'S', 'E', 'N'],
        description: 'Join-issue target consent condition',
      },
      issue_anniversary_type: {
        type: 'enum',
        location: 'body',
        enum: ['B', 'W'],
        description: 'Anniversary type B=birthday, W=wedding',
      },
      issue_on_anniversary: {
        type: 'enum',
        location: 'body',
        enum: ['S', 'P'],
        description: 'S=same-day, P=pre-issue',
      },
      issue_anniversary_pre_issue_day: {
        type: 'number',
        location: 'body',
        description: 'Pre-issue days; required when issue_on_anniversary=P',
      },
      issue_review_count: {
        type: 'number',
        location: 'body',
        description: 'Required review count; required when issue_sub_type=P',
      },
      issue_review_has_image: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Review must include image (T/F)',
      },
      issue_limit: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Issuance count limited (T/F)',
      },
      same_user_reissue: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description:
          'Same-user reissue allowed; required when issue_limit=T (T/F)',
      },
      issue_reserved: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'F',
        description: 'Auto-issuance reservation used (T/F)',
      },
      issue_reserved_date: {
        type: 'string',
        location: 'body',
        description:
          'Auto-issuance reserved datetime (KST, UTC+9); required when issue_reserved=T',
      },
      issue_no_purchase_period: {
        type: 'number',
        location: 'body',
        description: 'No-purchase period in months (1-12)',
      },
      show_product_detail: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Show on product detail page (T/F)',
      },
      include_regional_shipping_rate: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Include regional shipping rate (T/F)',
      },
      include_foreign_delivery: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Include foreign delivery (T/F)',
      },
      available_product_list: { type: 'array', location: 'body' },
      available_category_list: { type: 'array', location: 'body' },
      available_price_type: {
        type: 'enum',
        location: 'body',
        enum: ['U', 'O', 'P'],
        default: 'U',
        description: 'Price-basis U=none, O=order-amount, P=product-amount',
      },
      available_order_price_type: {
        type: 'enum',
        location: 'body',
        enum: ['U', 'I'],
        description: 'Price detail U=all-products, I=coupon-products',
      },
      available_min_price: {
        type: 'string',
        location: 'body',
        description: 'Min usable purchase amount (decimal string, KRW)',
      },
      issue_max_count: {
        type: 'number',
        location: 'body',
        description: 'Max issuance count',
      },
      issue_max_count_by_user: {
        type: 'number',
        location: 'body',
        description: 'Max reissue count per same user',
      },
      issue_order_path: {
        type: 'enum',
        location: 'body',
        enum: ['W', 'M', 'P'],
        description: 'Order path W=web, M=mobile, P=brand-app',
      },
      issue_order_date: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Order-period setting T=set, F=not-set',
      },
      issue_order_start_date: {
        type: 'string',
        location: 'body',
        description: 'Issuable order start datetime (KST, UTC+9)',
      },
      issue_order_end_date: {
        type: 'string',
        location: 'body',
        description: 'Issuable order end datetime (KST, UTC+9)',
      },
      issue_member_group_no: { type: 'number', location: 'body' },
      issue_member_group_name: { type: 'string', location: 'body' },
      discount_amount: { type: 'object', location: 'body' },
      discount_rate: { type: 'object', location: 'body' },
      issue_order_amount_type: {
        type: 'enum',
        location: 'body',
        enum: ['O', 'S'],
        description: 'Issue amount basis O=purchase, S=actual-payment',
      },
      issue_order_amount_limit: {
        type: 'enum',
        location: 'body',
        enum: ['U', 'L', 'S'],
        description: 'Amount limit U=none, L=min, S=range',
      },
      issue_order_amount_min: {
        type: 'string',
        location: 'body',
        description: 'Min issuable purchase amount (decimal string, KRW)',
      },
      issue_order_amount_max: {
        type: 'string',
        location: 'body',
        description: 'Max issuable purchase amount (decimal string, KRW)',
      },
      issue_count_per_once: {
        type: 'number',
        location: 'body',
        description: 'Issue quantity per issuance (1-10)',
      },
      issue_order_type: {
        type: 'enum',
        location: 'body',
        enum: ['O', 'P'],
        description: 'Issue unit O=order-sheet, P=product',
      },
      issue_order_available_product: {
        type: 'enum',
        location: 'body',
        enum: ['U', 'I', 'E'],
        description: 'Target product U=none, I=include, E=exclude',
      },
      issue_order_available_product_list: { type: 'array', location: 'body' },
      issue_order_available_category: {
        type: 'enum',
        location: 'body',
        enum: ['U', 'I', 'E'],
        description: 'Target category U=none, I=include, E=exclude',
      },
      issue_order_available_category_list: { type: 'array', location: 'body' },
      issue_quntity_type: {
        type: 'enum',
        location: 'body',
        enum: ['P', 'O'],
        description: 'Quantity basis P=product-qty, O=order-qty',
      },
      issue_quantity_min: {
        type: 'number',
        location: 'body',
        description: 'Min purchase quantity for issuance',
      },
      available_payment_method: {
        type: 'string',
        location: 'body',
        description: 'Usable payment methods (all/R/E/C/A/H/M/…)',
      },
      use_notification_when_login: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Issue alarm on login (T/F)',
      },
      send_sms_for_issue: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Send SMS on issue (T/F)',
      },
      send_email_for_issue: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Send email on issue (T/F)',
      },
      exclude_unsubscribed: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Exclude email-unsubscribed members (T/F)',
      },
      recurring_issuance: { type: 'object', location: 'body' },
      additional_targets: {
        type: 'enum',
        location: 'body',
        enum: ['P'],
        description: 'Extra-issue service target P=brand-app',
      },
      additional_conditions: {
        type: 'enum',
        location: 'body',
        enum: ['I', 'P'],
        description: 'Extra-issue condition I=install, P=push-on',
      },
    },
    responseShape: 'single',
    constraints: [
      {
        kind: 'impliesValue',
        if: 'issue_limit',
        value: 'T',
        then: ['same_user_reissue'],
      },
      {
        kind: 'impliesValue',
        if: 'issue_on_anniversary',
        value: 'P',
        then: ['issue_anniversary_pre_issue_day'],
      },
      {
        kind: 'impliesValue',
        if: 'issue_reserved',
        value: 'T',
        then: ['issue_reserved_date'],
      },
    ],
  },
  {
    id: 'coupon_issue',
    description: 'Issue a coupon to specified members.',
    scopeType: 'write',
    method: 'POST',
    path: 'coupons/{coupon_no}/issues',
    requiredFields: ['coupon_no', 'issued_member_scope'],
    fields: {
      coupon_no: { type: 'string', location: 'path' },
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      issued_member_scope: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'G', 'M'],
        description: 'A=all members, G=member group, M=specific member',
      },
      group_no: { type: 'number', location: 'body' },
      member_id: { type: 'string', location: 'body' },
      send_sms_for_issue: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'F',
        description: 'Send SMS on issue (T/F)',
      },
      allow_duplication: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F', 'S'],
        default: 'F',
        description: 'Duplicate-issue setting T=allow, F=deny, S=deny-no-check',
      },
      single_issue_per_once: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'T',
        description: 'Issue single per once T=one, F=configured-qty',
      },
      issue_count_per_once: {
        type: 'number',
        location: 'body',
        default: 2,
        description: 'Issue quantity when multiple (2-10)',
      },
      issued_place_type: {
        type: 'enum',
        location: 'body',
        enum: ['W', 'M', 'P'],
        description: 'Issue place W=web, M=mobile, P=brand-app',
      },
      issued_by_action_type: {
        type: 'enum',
        location: 'body',
        enum: ['INSTALLATION', 'ACCEPTING_PUSH'],
        description: 'App-install issue timing',
      },
      issued_by_event_type: {
        type: 'string',
        location: 'body',
        description: 'Issue reason event code (C/U/B/R/Z/…)',
      },
      request_admin_id: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'coupon_count',
    description:
      'Retrieve the total count of coupons. Sibling of coupon_list (paginated).',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons/count',
    requiredFields: [],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      coupon_no: { type: 'string', location: 'query' },
      coupon_type: {
        type: 'enum',
        location: 'query',
        enum: ['O', 'S'],
        description: 'O=online coupon, S=offline serial coupon',
      },
      coupon_name: { type: 'string', location: 'query' },
      benefit_type: {
        type: 'string',
        location: 'query',
        description: 'Benefit type (comma-separated)',
      },
      issue_type: {
        type: 'string',
        location: 'query',
        description: 'Issue type (comma-separated)',
      },
      issue_sub_type: {
        type: 'string',
        location: 'query',
        description: 'Issue sub-type code',
      },
      issued_flag: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Has issuance history (T/F)',
      },
      created_start_date: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_CREATED_START,
      },
      created_end_date: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_CREATED_END,
      },
      deleted: {
        type: 'string',
        location: 'query',
        description: 'Deleted flag (comma-separated). T=deleted, F=not deleted',
      },
      pause_begin_date: {
        type: 'string',
        location: 'query',
        description: 'Issuance-pause range start (YYYY-MM-DD, KST)',
      },
      pause_end_date: {
        type: 'string',
        location: 'query',
        description: 'Issuance-pause range end (YYYY-MM-DD, KST)',
      },
      issue_order_path: {
        type: 'enum',
        location: 'query',
        enum: ['W', 'M', 'P'],
        description: 'Order path W=PC, M=mobile, P=brand-app',
      },
      issue_order_type: {
        type: 'enum',
        location: 'query',
        enum: ['P', 'O'],
        description: 'Issue unit P=product, O=order-sheet',
      },
      issue_reserved: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Auto-issuance reservation used (T/F)',
      },
      available_period_type: {
        type: 'string',
        location: 'query',
        description: 'Usage-period type (comma-separated). F/R/M',
      },
      available_datetime: {
        type: 'string',
        location: 'query',
        description:
          'Coupons issuable on this date (YYYY-MM-DD, KST); valid only when available_period_type=F',
      },
      available_site: {
        type: 'enum',
        location: 'query',
        enum: ['W', 'M', 'P'],
        description: 'Usage scope W=web, M=mobile, P=brand-app',
      },
      available_scope: {
        type: 'enum',
        location: 'query',
        enum: ['P', 'O'],
        description: 'Apply scope P=product, O=order-sheet',
      },
      available_price_type: {
        type: 'enum',
        location: 'query',
        enum: ['U', 'O', 'P'],
        description: 'Price-basis U=none, O=order-amount, P=product-amount',
      },
      available_order_price_type: {
        type: 'enum',
        location: 'query',
        enum: ['U', 'I'],
        description: 'Price detail U=all-products, I=coupon-products',
      },
    },
    responseShape: 'single',
    constraints: [
      { kind: 'allOrNone', fields: ['created_start_date', 'created_end_date'] },
    ],
  },
  {
    id: 'coupon_issues_list',
    description:
      'List the issuance records of a coupon (who received it, when).',
    scopeType: 'read',
    method: 'GET',
    // cafe24 docs path: `coupons/{coupon_no}/issues` (coupon-scoped, not
    // `coupons/issues` with query param).
    path: 'coupons/{coupon_no}/issues',
    requiredFields: ['coupon_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      coupon_no: { type: 'number', location: 'path' },
      member_id: { type: 'string', location: 'query' },
      group_no: { type: 'number', location: 'query' },
      issued_date: {
        type: 'string',
        location: 'query',
        description: 'Coupon issued date (YYYY-MM-DD, KST)',
      },
      issued_start_date: {
        type: 'string',
        location: 'query',
        description: 'Search start date (YYYY-MM-DD, KST)',
      },
      issued_end_date: {
        type: 'string',
        location: 'query',
        description: 'Search end date (YYYY-MM-DD, KST)',
      },
      used_coupon: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Coupon used flag T=used, F=unused',
      },
      since_issue_no: {
        type: 'string',
        location: 'query',
        description: 'Search after this issue_no (excludes offset use)',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'coupon_issuance_customers_list',
    description:
      'List customers eligible for conditional issuance of a coupon.',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons/{coupon_no}/issuancecustomers',
    requiredFields: ['coupon_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      coupon_no: { type: 'number', location: 'path' },
      member_id: { type: 'string', location: 'query' },
      group_no: { type: 'number', location: 'query' },
      since_member_id: {
        type: 'string',
        location: 'query',
        description: 'Search after this coupon member ID',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'customers_coupons_list',
    description:
      'List the coupons a customer holds. Uses the codebase-wide `member_id` path placeholder (Cafe24 docs call this `customer_no`).',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/coupons',
    requiredFields: ['member_id'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      member_id: { type: 'string', location: 'path' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'customers_coupons_count',
    description: 'Retrieve the count of coupons a customer holds.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/coupons/count',
    requiredFields: ['member_id'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      member_id: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'serialcoupons_list',
    description:
      'Retrieve the generated serial coupon codes for a coupon (paginated by limit/offset).',
    scopeType: 'read',
    method: 'GET',
    path: 'serialcoupons',
    requiredFields: ['coupon_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      coupon_no: { type: 'number', location: 'query' },
      coupon_name: { type: 'string', location: 'query' },
      benefit_type: {
        type: 'string',
        location: 'query',
        description: 'Benefit type (comma-separated). A/B/C/D/E/I/H/J/F/G',
      },
      issued_flag: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Issued coupon flag T=has-history, F=none',
      },
      created_start_date: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_CREATED_START,
      },
      created_end_date: {
        type: 'string',
        location: 'query',
        description: CAFE24_DATE_FIELD_CREATED_END,
      },
      deleted: {
        type: 'string',
        location: 'query',
        default: 'F',
        description: 'Deleted flag (comma-separated). T=deleted, F=not deleted',
      },
      issue_order_path: {
        type: 'enum',
        location: 'query',
        enum: ['W', 'M', 'P'],
        description: 'Order path W=web, M=mobile, P=brand-app',
      },
      issue_order_type: {
        type: 'enum',
        location: 'query',
        enum: ['P', 'O'],
        description: 'Issue unit P=product, O=order-sheet',
      },
      issue_reserved: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Auto-issuance reservation used (T/F)',
      },
      available_period_type: {
        type: 'string',
        location: 'query',
        description: 'Usage-period type (comma-separated). F/R/M',
      },
      available_datetime: {
        type: 'string',
        location: 'query',
        description:
          'Issuable on this date (YYYY-MM-DD, KST); valid only when available_period_type=F',
      },
      available_site: {
        type: 'enum',
        location: 'query',
        enum: ['W', 'M', 'P'],
        description: 'Usage scope W=web, M=mobile, P=brand-app',
      },
      available_scope: {
        type: 'enum',
        location: 'query',
        enum: ['P', 'O'],
        description: 'Apply scope P=product, O=order-sheet',
      },
      available_price_type: {
        type: 'enum',
        location: 'query',
        enum: ['U', 'O', 'P'],
        description: 'Price-basis U=none, O=order-amount, P=product-amount',
      },
      available_order_price_type: {
        type: 'enum',
        location: 'query',
        enum: ['U', 'I'],
        description: 'Price detail U=all-products, I=coupon-products',
      },
    },
    responseShape: 'list',
    paginated: true,
    constraints: [
      { kind: 'allOrNone', fields: ['created_start_date', 'created_end_date'] },
    ],
  },
  {
    id: 'serialcoupons_generate',
    description:
      'Generate a batch of serial coupon codes. `coupon_no` + `quantity` in body.',
    scopeType: 'write',
    // cafe24 docs path: `serialcoupons` (POST — coupon_no goes in body, not
    // path. anchor `generate-coupon-code`).
    method: 'POST',
    path: 'serialcoupons',
    requiredFields: [
      'coupon_name',
      'benefit_type',
      'available_period_type',
      'available_site',
      'available_scope',
      'available_product',
      'available_category',
      'available_amount_type',
      'available_coupon_count_by_order',
      'serial_generate_method',
      'serial_code_type',
    ],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      coupon_name: { type: 'string', location: 'body' },
      benefit_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'B'],
        description: 'Benefit type A=amount, B=rate',
      },
      available_period_type: {
        type: 'enum',
        location: 'body',
        enum: ['F', 'R', 'M'],
        description:
          'Usage-period type F=fixed, R=from-issue, M=until-month-end',
      },
      available_begin_datetime: {
        type: 'string',
        location: 'body',
        description: 'Usage start datetime (KST, UTC+9)',
      },
      available_end_datetime: {
        type: 'string',
        location: 'body',
        description: 'Usage end datetime (KST, UTC+9)',
      },
      available_day_from_issued: {
        type: 'number',
        location: 'body',
        description: 'Usable days from issue (1-999)',
      },
      available_site: {
        type: 'enum',
        location: 'body',
        enum: ['W', 'M'],
        description: 'Usage scope W=web, M=mobile',
      },
      available_scope: {
        type: 'enum',
        location: 'body',
        enum: ['P', 'O'],
        description: 'Apply scope P=product, O=order-sheet',
      },
      available_product: {
        type: 'enum',
        location: 'body',
        enum: ['U', 'I', 'E'],
        description: 'Product select U=none, I=include, E=exclude',
      },
      available_product_list: { type: 'array', location: 'body' },
      available_category: {
        type: 'enum',
        location: 'body',
        enum: ['U', 'I', 'E'],
        description: 'Category select U=none, I=include, E=exclude',
      },
      available_category_list: { type: 'array', location: 'body' },
      available_amount_type: {
        type: 'enum',
        location: 'body',
        enum: ['E', 'I'],
        description: 'Calc basis E=before-discount, I=after-discount',
      },
      available_coupon_count_by_order: {
        type: 'number',
        location: 'body',
        description: 'Max same-coupon uses per order (1-999)',
      },
      available_price_type: {
        type: 'enum',
        location: 'body',
        enum: ['U', 'O', 'P'],
        default: 'U',
        description: 'Price-basis U=none, O=order-amount, P=product-amount',
      },
      available_order_price_type: {
        type: 'enum',
        location: 'body',
        enum: ['U', 'I'],
        description: 'Price detail U=all-products, I=coupon-products',
      },
      available_min_price: {
        type: 'string',
        location: 'body',
        description: 'Min usable purchase amount (decimal string, KRW)',
      },
      discount_amount: { type: 'object', location: 'body' },
      discount_rate: { type: 'object', location: 'body' },
      serial_generate_method: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'M'],
        description: 'Serial generation A=auto, M=manual',
      },
      serial_code_type: {
        type: 'enum',
        location: 'body',
        enum: ['R', 'S'],
        description: 'Serial code type R=different-codes, S=same-code',
      },
      serial_generate_auto: { type: 'object', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'serialcoupons_delete',
    description:
      'Delete serial coupon codes for a coupon. (Specific code filtering via query/body per cafe24 docs.)',
    scopeType: 'write',
    method: 'DELETE',
    // cafe24 docs path: `serialcoupons/{coupon_no}` (no `/{code}` path
    // segment — specific-code targeting goes through body/query).
    path: 'serialcoupons/{coupon_no}',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'serialcoupons_issues_get',
    description: 'List the issued/used codes for a serial coupon.',
    scopeType: 'read',
    method: 'GET',
    path: 'serialcoupons/{coupon_no}/issues',
    requiredFields: ['coupon_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      coupon_no: { type: 'number', location: 'path' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'serialcoupons_issues_register',
    description: 'Register a specific code into the serial coupon issued set.',
    scopeType: 'write',
    method: 'POST',
    path: 'serialcoupons/{coupon_no}/issues',
    requiredFields: ['coupon_no', 'serial_code_list'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      coupon_no: { type: 'number', location: 'path' },
      serial_code_list: {
        type: 'array',
        location: 'body',
        description: 'Serial number list (max 10000)',
      },
    },
    responseShape: 'single',
  },
  // Phase 6c — benefits CRUD + customerevents + customers_coupons_delete
  {
    id: 'benefits_list',
    description: 'List the customer-benefit campaigns configured on the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'benefits',
    requiredFields: [],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      use_benefit: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'In-progress flag T=active, F=inactive',
      },
      benefit_name: { type: 'string', location: 'query' },
      benefit_type: {
        type: 'string',
        location: 'query',
        description:
          'Benefit detail type DP/DR/DQ/DM/DN/DV=discount, PG/PB=gift',
      },
      period_type: {
        type: 'enum',
        location: 'query',
        enum: ['R', 'S', 'E'],
        description: 'Period type R=register, S=start, E=end',
      },
      benefit_start_date: {
        type: 'string',
        location: 'query',
        description: 'Search start date (YYYY-MM-DD, KST)',
      },
      benefit_end_date: {
        type: 'string',
        location: 'query',
        description: 'Search end date (YYYY-MM-DD, KST)',
      },
      platform_types: {
        type: 'string',
        location: 'query',
        description:
          'Usage scope (comma-separated). P=PC, M=mobile, A=brand-app',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'benefits_count',
    description: 'Retrieve the count of configured customer benefits.',
    scopeType: 'read',
    method: 'GET',
    path: 'benefits/count',
    requiredFields: [],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      use_benefit: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'In-progress flag T=active, F=inactive',
      },
      benefit_name: { type: 'string', location: 'query' },
      benefit_type: {
        type: 'string',
        location: 'query',
        description:
          'Benefit detail type DP/DR/DQ/DM/DN/DV=discount, PG/PB=gift',
      },
      period_type: {
        type: 'enum',
        location: 'query',
        enum: ['R', 'S', 'E'],
        description: 'Period type R=register, S=start, E=end',
      },
      benefit_start_date: {
        type: 'string',
        location: 'query',
        description: 'Search start date (YYYY-MM-DD, KST)',
      },
      benefit_end_date: {
        type: 'string',
        location: 'query',
        description: 'Search end date (YYYY-MM-DD, KST)',
      },
      platform_types: {
        type: 'string',
        location: 'query',
        description:
          'Usage scope (comma-separated). P=PC, M=mobile, A=brand-app',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'benefits_get',
    description: 'Retrieve a single customer benefit by benefit_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'benefits/{benefit_no}',
    requiredFields: ['benefit_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      benefit_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'benefits_create',
    description:
      'Create a customer-benefit campaign. Required: benefit_name, benefit_type, benefit_scope.',
    scopeType: 'write',
    method: 'POST',
    path: 'benefits',
    requiredFields: [
      'benefit_name',
      'benefit_type',
      'use_benefit',
      'benefit_division',
      'platform_types',
    ],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      use_benefit: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'In-progress flag T=active, F=inactive',
      },
      benefit_name: { type: 'string', location: 'body' },
      benefit_division: {
        type: 'enum',
        location: 'body',
        enum: ['D', 'P'],
        description: 'Benefit type D=discount, P=gift',
      },
      benefit_type: {
        type: 'enum',
        location: 'body',
        enum: ['DP', 'DR', 'DQ', 'DM', 'DN', 'DV', 'PG', 'PB'],
        description: 'Benefit detail type (period/repurchase/bulk/…)',
      },
      use_benefit_period: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Set benefit period (T requires start/end dates)',
      },
      benefit_start_date: {
        type: 'string',
        location: 'body',
        description: 'Benefit start datetime (KST, UTC+9)',
      },
      benefit_end_date: {
        type: 'string',
        location: 'body',
        description: 'Benefit end datetime (KST, UTC+9)',
      },
      platform_types: {
        type: 'string',
        location: 'body',
        description: 'Usage scope. P=PC, M=mobile, A=brand-app',
      },
      use_group_binding: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'N', 'M'],
        description: 'Participation A=member+guest, N=guest, M=member',
      },
      customer_group_list: { type: 'array', location: 'body' },
      product_binding_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'P', 'E', 'C'],
        description: 'Product scope A=all, P=specific, E=exclude, C=category',
      },
      use_except_category: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Exclude category from benefit (T/F)',
      },
      available_coupon: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Coupon stacking T=allow-all, F=deny-all',
      },
      period_sale: { type: 'object', location: 'body' },
      repurchase_sale: { type: 'object', location: 'body' },
      bulk_purchase_sale: { type: 'object', location: 'body' },
      member_sale: { type: 'object', location: 'body' },
      gift: { type: 'object', location: 'body' },
      new_product_sale: { type: 'object', location: 'body' },
      shipping_fee_sale: { type: 'object', location: 'body' },
      gift_product_bundle: { type: 'object', location: 'body' },
      icon_url: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
    constraints: [
      {
        kind: 'impliesValue',
        if: 'use_benefit_period',
        value: 'T',
        then: ['benefit_start_date', 'benefit_end_date'],
      },
    ],
  },
  {
    id: 'benefits_update',
    description:
      'Update a customer-benefit campaign by benefit_no. Body fields are partial — provide only the ones to change.',
    scopeType: 'write',
    method: 'PUT',
    path: 'benefits/{benefit_no}',
    requiredFields: ['benefit_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      benefit_no: { type: 'number', location: 'path' },
      use_benefit: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'In-progress flag T=active, F=inactive',
      },
      benefit_name: { type: 'string', location: 'body' },
      use_benefit_period: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Set benefit period (T/F)',
      },
      benefit_start_date: {
        type: 'string',
        location: 'body',
        description:
          'Benefit start datetime (KST, UTC+9); requires use_benefit_period declared',
      },
      benefit_end_date: {
        type: 'string',
        location: 'body',
        description:
          'Benefit end datetime (KST, UTC+9); requires use_benefit_period declared',
      },
      platform_types: {
        type: 'string',
        location: 'body',
        description: 'Usage scope. P=PC, M=mobile, A=brand-app',
      },
      use_group_binding: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'N', 'M'],
        description: 'Participation A=member+guest, N=guest, M=member',
      },
      customer_group_list: { type: 'array', location: 'body' },
      product_binding_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'P', 'E', 'C'],
        description: 'Product scope A=all, P=specific, E=exclude, C=category',
      },
      use_except_category: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Exclude category from benefit (T/F)',
      },
      available_coupon: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Coupon stacking T=allow-all, F=deny-all',
      },
      period_sale: { type: 'object', location: 'body' },
      gift: { type: 'object', location: 'body' },
      gift_product_bundle: { type: 'object', location: 'body' },
      new_product_sale: { type: 'object', location: 'body' },
      shipping_fee_sale: { type: 'object', location: 'body' },
      icon_url: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'benefits_delete',
    description: 'Delete a customer-benefit campaign by benefit_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'benefits/{benefit_no}',
    requiredFields: ['benefit_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      benefit_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'customerevents_get',
    description: 'Retrieve the current member-information-update event status.',
    scopeType: 'read',
    method: 'GET',
    path: 'customerevents',
    requiredFields: [],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      name: { type: 'string', location: 'query' },
      search_date: {
        type: 'enum',
        location: 'query',
        enum: ['created_date', 'start_date', 'end_date'],
        default: 'created_date',
        description: 'Search basis date field',
      },
      start_date: {
        type: 'string',
        location: 'query',
        description: 'Search start date (YYYY-MM-DD, KST)',
      },
      end_date: {
        type: 'string',
        location: 'query',
        description: 'Search end date (YYYY-MM-DD, KST)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'customerevents_create',
    description:
      'Create a member-information-modification campaign event. Required: type, name.',
    scopeType: 'write',
    method: 'POST',
    path: 'customerevents',
    requiredFields: ['type', 'name'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      type: {
        type: 'enum',
        location: 'body',
        enum: ['E', 'P', 'L'],
        description: 'Event type E=info-update, P=password, L=lifetime',
      },
      name: { type: 'string', location: 'body' },
      description: { type: 'string', location: 'body' },
      start_date: {
        type: 'string',
        location: 'body',
        description: 'Event start datetime (KST, UTC+9)',
      },
      end_date: {
        type: 'string',
        location: 'body',
        description: 'Event end datetime (KST, UTC+9)',
      },
      items: {
        type: 'array',
        location: 'body',
        description: 'Event items (zipcode/address/cellphone/…) max 6',
      },
      reward_condition: {
        type: 'enum',
        location: 'body',
        enum: ['O', 'A'],
        description: 'Reward condition O=any-one, A=all',
      },
      agree_restriction: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Consent-change restriction used (T/F)',
      },
      agree_restriction_period: {
        type: 'string',
        location: 'body',
        description: 'Restriction period 1/3/6/12 months or -1=unlimited',
      },
      auto_reward: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Auto reward used (T/F)',
      },
      use_point: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Auto-reward points used (T/F)',
      },
      point_amount: {
        type: 'string',
        location: 'body',
        description: 'Auto-reward point amount (decimal string, KRW)',
      },
      use_coupon: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Auto-reward coupon used (T/F)',
      },
      coupon_no: { type: 'string', location: 'body' },
      popup_notification: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Lifetime-conversion popup used (T/F)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'customerevents_update_status',
    description:
      'Update the run-status of the member-information-update event.',
    scopeType: 'write',
    method: 'PUT',
    path: 'customerevents',
    requiredFields: ['status', 'no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      no: { type: 'number', location: 'body' },
      status: {
        type: 'enum',
        location: 'body',
        enum: ['S', 'D'],
        description: 'Event status S=end, D=delete',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'customers_coupons_delete',
    description:
      'Remove a coupon from a customer. Uses codebase `member_id` placeholder (Cafe24 docs: customer_no).',
    scopeType: 'write',
    method: 'DELETE',
    path: 'customers/{member_id}/coupons/{coupon_no}',
    requiredFields: ['member_id', 'coupon_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      member_id: { type: 'string', location: 'path' },
      coupon_no: { type: 'string', location: 'path' },
      issue_no: { type: 'string', location: 'query' },
    },
    responseShape: 'single',
  },
  // Phase 7a — discountcodes CRUD + commonevents CRUD
  {
    id: 'discountcodes_list',
    description: 'List discount codes for the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'discountcodes',
    requiredFields: [],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      discount_code_name: { type: 'string', location: 'query' },
      discount_code: { type: 'string', location: 'query' },
      search_date_type: {
        type: 'enum',
        location: 'query',
        enum: ['available_start_date', 'available_end_date', 'created_date'],
        description: 'Search basis date field',
      },
      start_date: {
        type: 'string',
        location: 'query',
        description: 'Search start date (YYYY-MM-DD, KST)',
      },
      end_date: {
        type: 'string',
        location: 'query',
        description: 'Search end date (YYYY-MM-DD, KST)',
      },
      sort: {
        type: 'string',
        location: 'query',
        default: 'created_date',
        description:
          'Sort key (discount_code_name/discount_code/created_date/…)',
      },
      order: {
        type: 'enum',
        location: 'query',
        enum: ['asc', 'desc'],
        default: 'desc',
        description: 'Sort order asc/desc',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'discountcodes_get',
    description: 'Retrieve a discount code by discount_code_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'discountcodes/{discount_code_no}',
    requiredFields: ['discount_code_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      discount_code_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'discountcodes_create',
    description:
      'Create a discount code. Body fields are partial — refer to Cafe24 docs for the discount type / amount schema.',
    scopeType: 'write',
    method: 'POST',
    path: 'discountcodes',
    requiredFields: [
      'discount_code',
      'discount_code_name',
      'discount_value',
      'discount_truncation_unit',
      'discount_max_price',
      'available_start_date',
      'available_end_date',
    ],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      discount_code: { type: 'string', location: 'body' },
      discount_code_name: { type: 'string', location: 'body' },
      discount_value: {
        type: 'number',
        location: 'body',
        description: 'Discount value (1-99)',
      },
      discount_truncation_unit: {
        type: 'enum',
        location: 'body',
        enum: ['C', 'B', 'F', 'O', 'T', 'M', 'H'],
        description: 'Truncation unit C/B/F/O/T/M/H',
      },
      discount_max_price: {
        type: 'string',
        location: 'body',
        description: 'Max benefit amount (decimal string, KRW)',
      },
      available_start_date: {
        type: 'string',
        location: 'body',
        description: 'Start date (YYYY-MM-DD, KST)',
      },
      available_end_date: {
        type: 'string',
        location: 'body',
        description: 'End date (YYYY-MM-DD, KST)',
      },
      available_product_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'P', 'C'],
        default: 'A',
        description: 'Apply scope A=all, P=product, C=category',
      },
      available_product: { type: 'array', location: 'body' },
      available_category: { type: 'array', location: 'body' },
      available_min_price: {
        type: 'string',
        location: 'body',
        default: 0,
        description: 'Min order amount (decimal string, KRW)',
      },
      available_issue_count: {
        type: 'number',
        location: 'body',
        default: 0,
        description: 'Max issuance count',
      },
      available_user: {
        type: 'enum',
        location: 'body',
        enum: ['M', 'A'],
        default: 'A',
        description: 'Usable target M=member, A=all',
      },
      max_usage_per_user: {
        type: 'number',
        location: 'body',
        default: 0,
        description: 'Max uses per member',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'discountcodes_update',
    description: 'Update a discount code by discount_code_no (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'discountcodes/{discount_code_no}',
    requiredFields: ['discount_code_no', 'discount_code_name'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      discount_code_no: { type: 'number', location: 'path' },
      discount_code: { type: 'string', location: 'body' },
      discount_code_name: { type: 'string', location: 'body' },
      discount_value: {
        type: 'number',
        location: 'body',
        description: 'Discount value (1-99)',
      },
      discount_truncation_unit: {
        type: 'enum',
        location: 'body',
        enum: ['C', 'B', 'F', 'O', 'T', 'M', 'H'],
        description: 'Truncation unit C/B/F/O/T/M/H',
      },
      discount_max_price: {
        type: 'string',
        location: 'body',
        description: 'Max benefit amount (decimal string, KRW)',
      },
      available_start_date: {
        type: 'string',
        location: 'body',
        description: 'Start date (YYYY-MM-DD, KST)',
      },
      available_end_date: {
        type: 'string',
        location: 'body',
        description: 'End date (YYYY-MM-DD, KST)',
      },
      available_product_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'P', 'C'],
        description: 'Apply scope A=all, P=product, C=category',
      },
      available_product: { type: 'array', location: 'body' },
      available_category: { type: 'array', location: 'body' },
      available_min_price: {
        type: 'string',
        location: 'body',
        description: 'Min order amount (decimal string, KRW)',
      },
      available_issue_count: {
        type: 'number',
        location: 'body',
        description: 'Max issuance count',
      },
      available_user: {
        type: 'enum',
        location: 'body',
        enum: ['M', 'A'],
        description: 'Usable target M=member, A=all',
      },
      max_usage_per_user: {
        type: 'number',
        location: 'body',
        description: 'Max uses per member',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'discountcodes_delete',
    description: 'Delete a discount code by discount_code_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'discountcodes/{discount_code_no}',
    requiredFields: ['discount_code_no'],
    fields: {
      discount_code_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'commonevents_list',
    description: 'List storewide promotions / events.',
    scopeType: 'read',
    method: 'GET',
    path: 'commonevents',
    requiredFields: [],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'commonevents_create',
    description:
      'Create a storewide promotion. Body fields are partial — see Cafe24 docs.',
    scopeType: 'write',
    method: 'POST',
    path: 'commonevents',
    requiredFields: ['name'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      name: { type: 'string', location: 'body' },
      status: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'T',
        description: 'Event status T=running, F=stopped',
      },
      category_no: {
        type: 'number',
        location: 'body',
        default: 0,
        description: 'Category number (0=all)',
      },
      display_position: {
        type: 'enum',
        location: 'body',
        enum: ['top_detail', 'side_image'],
        default: 'top_detail',
        description: 'Display position top_detail/side_image',
      },
      content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'commonevents_update',
    description: 'Update a storewide promotion by event_no.',
    scopeType: 'write',
    method: 'PUT',
    path: 'commonevents/{event_no}',
    requiredFields: ['event_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      event_no: { type: 'number', location: 'path' },
      name: { type: 'string', location: 'body' },
      status: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Event status T=running, F=stopped',
      },
      category_no: {
        type: 'number',
        location: 'body',
        description: 'Category number (0=all)',
      },
      display_position: {
        type: 'enum',
        location: 'body',
        enum: ['top_detail', 'side_image'],
        description: 'Display position top_detail/side_image',
      },
      content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'commonevents_delete',
    description: 'Delete a storewide promotion by event_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'commonevents/{event_no}',
    requiredFields: ['event_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      event_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  // Phase 8b — Promotion 완성 (coupon_manage)
  {
    id: 'coupon_manage',
    description: 'Manage a coupon — pause or resume it via `status` enum.',
    scopeType: 'write',
    method: 'PUT',
    path: 'coupons/{coupon_no}',
    requiredFields: ['coupon_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'body',
        default: 1,
        description: 'Multi-shop number (default 1)',
      },
      coupon_no: { type: 'string', location: 'path' },
      status: {
        type: 'string',
        location: 'body',
        description: 'Status change: pause / restart (null to delete)',
      },
      deleted: {
        type: 'enum',
        location: 'body',
        enum: ['D'],
        description: 'Deleted flag D=delete',
      },
      immediate_issue_pause: {
        type: 'enum',
        location: 'body',
        enum: ['I'],
        description: 'Immediate issue pause (send status=pause)',
      },
      immediate_issue_restart: {
        type: 'enum',
        location: 'body',
        enum: ['I'],
        description: 'Immediate issue restart (send status=restart)',
      },
    },
    responseShape: 'single',
  },
];
