import type { Cafe24OperationMetadata } from './types.js';

export const shippingOperations: Cafe24OperationMetadata[] = [
  {
    id: 'carriers_list',
    description: 'Retrieve a list of shipping carriers.',
    scopeType: 'read',
    method: 'GET',
    path: 'carriers',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  // Phase 6d — shipping baseline
  {
    id: 'carriers_get',
    description: 'Retrieve a single shipping carrier by carrier_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'carriers/{carrier_no}',
    requiredFields: ['carrier_no'],
    fields: {
      carrier_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  // Phase 7e — Shipping 완성 (carriers CRUD + regionalsurcharges + settings + shippingorigins)
  {
    id: 'carriers_create',
    description: 'Register a new shipping carrier.',
    scopeType: 'write',
    method: 'POST',
    path: 'carriers',
    requiredFields: ['carrier_name'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      carrier_name: { type: 'string', location: 'body' },
      tracking_url: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'carriers_update',
    description: 'Update a shipping carrier by carrier_no.',
    scopeType: 'write',
    method: 'PUT',
    path: 'carriers/{carrier_no}',
    requiredFields: ['carrier_no'],
    fields: {
      carrier_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      carrier_name: { type: 'string', location: 'body' },
      tracking_url: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'carriers_delete',
    description: 'Delete a shipping carrier by carrier_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'carriers/{carrier_no}',
    requiredFields: ['carrier_no'],
    fields: {
      carrier_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'regionalsurcharges_get',
    description: 'Retrieve the regional shipping zone surcharges.',
    scopeType: 'read',
    method: 'GET',
    path: 'regionalsurcharges',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'regionalsurcharges_update',
    description: 'Update the regional shipping zone surcharges (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'regionalsurcharges',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shipping_settings_get',
    description: 'Retrieve the store-level shipping & return settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'shipping',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shipping_settings_update',
    description: 'Update the store-level shipping & return settings (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'shipping',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shipping_additionalfees_countries',
    description:
      'List countries with applicable additional handling fees for international shipping.',
    scopeType: 'read',
    method: 'GET',
    // cafe24 docs path: `shipping/additionalfees` (no `/countries` suffix).
    path: 'shipping/additionalfees',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'shippingorigins_list',
    description: 'List configured shipping origins.',
    scopeType: 'read',
    method: 'GET',
    path: 'shippingorigins',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'shippingorigins_get',
    description: 'Retrieve a shipping origin by origin_code.',
    scopeType: 'read',
    method: 'GET',
    path: 'shippingorigins/{origin_code}',
    requiredFields: ['origin_code'],
    fields: {
      origin_code: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shippingorigins_create',
    description: 'Register a new shipping origin.',
    scopeType: 'write',
    method: 'POST',
    path: 'shippingorigins',
    requiredFields: ['origin_name', 'address1'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      origin_name: { type: 'string', location: 'body' },
      zipcode: { type: 'string', location: 'body' },
      address1: { type: 'string', location: 'body' },
      address2: { type: 'string', location: 'body' },
      phone: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'shippingorigins_update',
    description: 'Update a shipping origin by origin_code (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'shippingorigins/{origin_code}',
    requiredFields: ['origin_code'],
    fields: {
      origin_code: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      origin_name: { type: 'string', location: 'body' },
      zipcode: { type: 'string', location: 'body' },
      address1: { type: 'string', location: 'body' },
      address2: { type: 'string', location: 'body' },
      phone: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'shippingorigins_delete',
    description: 'Delete a shipping origin by origin_code.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'shippingorigins/{origin_code}',
    requiredFields: ['origin_code'],
    fields: {
      origin_code: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
];
