import type { Cafe24OperationMetadata } from './types.js';

export const shippingOperations: Cafe24OperationMetadata[] = [
  {
    id: 'shipping_companies_list',
    label: '배송사 목록 조회',
    description: 'List shipping companies (carriers).',
    scopeType: 'read',
    method: 'GET',
    path: 'shippingcompanies',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  // Phase 6d — shipping baseline
  {
    id: 'carriers_get',
    label: '배송사 단건 조회',
    description: 'Retrieve a single shipping carrier by carrier_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'carriers/{carrier_no}',
    requiredFields: ['carrier_no'],
    fields: {
      carrier_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  // Phase 7e — Shipping 완성 (carriers CRUD + regionalsurcharges + settings + shippingorigins)
  {
    id: 'carriers_create',
    label: '배송사 등록',
    description: 'Register a new shipping carrier.',
    scopeType: 'write',
    method: 'POST',
    path: 'carriers',
    requiredFields: ['carrier_name'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      carrier_name: { type: 'string', location: 'body' },
      tracking_url: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'carriers_update',
    label: '배송사 수정',
    description: 'Update a shipping carrier by carrier_no.',
    scopeType: 'write',
    method: 'PUT',
    path: 'carriers/{carrier_no}',
    requiredFields: ['carrier_no'],
    fields: {
      carrier_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      carrier_name: { type: 'string', location: 'body' },
      tracking_url: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'carriers_delete',
    label: '배송사 삭제',
    description: 'Delete a shipping carrier by carrier_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'carriers/{carrier_no}',
    requiredFields: ['carrier_no'],
    fields: {
      carrier_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'regionalsurcharges_get',
    label: '지역별 배송비 조회',
    description: 'Retrieve the regional shipping zone surcharges.',
    scopeType: 'read',
    method: 'GET',
    path: 'regionalsurcharges',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'regionalsurcharges_update',
    label: '지역별 배송비 수정',
    description: 'Update the regional shipping zone surcharges (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'regionalsurcharges',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shipping_settings_get',
    label: '배송·반품 설정 조회',
    description: 'Retrieve the store-level shipping & return settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'shipping',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shipping_settings_update',
    label: '배송·반품 설정 수정',
    description: 'Update the store-level shipping & return settings (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'shipping',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shipping_additionalfees_countries',
    label: '국제 배송 추가비 국가 목록',
    description:
      'List countries with applicable additional handling fees for international shipping.',
    scopeType: 'read',
    method: 'GET',
    path: 'shipping/additionalfees/countries',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'shippingorigins_list',
    label: '출고지 목록',
    description: 'List configured shipping origins.',
    scopeType: 'read',
    method: 'GET',
    path: 'shippingorigins',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'shippingorigins_get',
    label: '출고지 단건 조회',
    description: 'Retrieve a shipping origin by origin_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'shippingorigins/{origin_no}',
    requiredFields: ['origin_no'],
    fields: {
      origin_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shippingorigins_create',
    label: '출고지 등록',
    description: 'Register a new shipping origin.',
    scopeType: 'write',
    method: 'POST',
    path: 'shippingorigins',
    requiredFields: ['origin_name', 'address1'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      origin_name: { type: 'string', location: 'body' },
      zipcode: { type: 'string', location: 'body' },
      address1: { type: 'string', location: 'body' },
      address2: { type: 'string', location: 'body' },
      phone: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'shippingorigins_update',
    label: '출고지 수정',
    description: 'Update a shipping origin by origin_no (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'shippingorigins/{origin_no}',
    requiredFields: ['origin_no'],
    fields: {
      origin_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      origin_name: { type: 'string', location: 'body' },
      zipcode: { type: 'string', location: 'body' },
      address1: { type: 'string', location: 'body' },
      address2: { type: 'string', location: 'body' },
      phone: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'shippingorigins_delete',
    label: '출고지 삭제',
    description: 'Delete a shipping origin by origin_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'shippingorigins/{origin_no}',
    requiredFields: ['origin_no'],
    fields: {
      origin_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
];
