import type { Cafe24OperationMetadata } from './types.js';
import { RESTRICTED_APPROVAL } from './restricted-approval.js';

export const storeOperations: Cafe24OperationMetadata[] = [
  {
    id: 'store_get',
    label: '상점 정보 조회',
    description: 'Get the mall (store) information.',
    scopeType: 'read',
    method: 'GET',
    path: 'store',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shops_list',
    label: '멀티쇼핑몰 목록 조회',
    description: 'List shops in a multi-shop mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'shops',
    requiredFields: [],
    fields: {},
    responseShape: 'list',
  },
  // Phase 6b — 결제 설정 (paymentmethods / paymentgateway)
  {
    id: 'paymentmethods_list',
    label: '결제수단 목록',
    description: 'List available payment methods.',
    scopeType: 'read',
    method: 'GET',
    path: 'paymentmethods',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'paymentmethods_paymentproviders_list',
    label: '결제수단별 제공사 목록',
    description: 'List the providers (PG) registered per payment method.',
    scopeType: 'read',
    method: 'GET',
    path: 'paymentmethods/paymentproviders',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'paymentgateway_paymentmethods_list',
    label: '결제대행사 결제수단 목록',
    description:
      'List the payment methods attached to the registered payment gateways.',
    scopeType: 'read',
    method: 'GET',
    path: 'paymentgateway/paymentmethods',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  {
    id: 'paymentgateway_create',
    label: '결제대행사 생성',
    description:
      'Register a new payment gateway (PG). `pg_code` + `pg_name` required.',
    scopeType: 'write',
    method: 'POST',
    path: 'paymentgateway',
    requiredFields: ['pg_code', 'pg_name'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      pg_code: { type: 'string', location: 'body' },
      pg_name: { type: 'string', location: 'body' },
      use_yn: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Enable flag (T=on, F=off)',
      },
      authentication_key: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  {
    id: 'paymentgateway_update',
    label: '결제대행사 수정',
    description: 'Update an existing payment gateway by paymentgateway_id.',
    scopeType: 'write',
    method: 'PUT',
    path: 'paymentgateway/{paymentgateway_id}',
    requiredFields: ['paymentgateway_id'],
    fields: {
      paymentgateway_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      pg_name: { type: 'string', location: 'body' },
      use_yn: { type: 'enum', location: 'body', enum: ['T', 'F'] },
      authentication_key: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  {
    id: 'paymentgateway_delete',
    label: '결제대행사 삭제',
    description: 'Remove a registered payment gateway by paymentgateway_id.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'paymentgateway/{paymentgateway_id}',
    requiredFields: ['paymentgateway_id'],
    fields: {
      paymentgateway_id: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  // Batch 1-A — shops·activitylogs·dashboard·financials·menus
  {
    id: 'shops_get',
    label: '멀티쇼핑몰 단건 조회',
    description: 'Retrieve a single shop within a multi-shop mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'shops/{shop_no}',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'activitylogs_list',
    label: '액션 로그 목록',
    description:
      'List operator activity logs within a date range. Requires Cafe24 partner approval.',
    scopeType: 'read',
    method: 'GET',
    path: 'activitylogs',
    requiredFields: ['start_date', 'end_date'],
    fields: {
      start_date: { type: 'string', location: 'query' },
      end_date: { type: 'string', location: 'query' },
      manager_type: {
        type: 'enum',
        location: 'query',
        enum: ['P', 'A', 'S'],
        description: 'Operator type filter (P/A/S)',
      },
      manager_id: { type: 'string', location: 'query' },
      mode: {
        type: 'enum',
        location: 'query',
        enum: ['P', 'M', 'S'],
      },
      type: { type: 'string', location: 'query' },
      content: { type: 'string', location: 'query' },
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
    restrictedApproval: RESTRICTED_APPROVAL.store_activitylogs,
  },
  {
    id: 'activitylogs_get',
    label: '액션 로그 단건 조회',
    description:
      'Retrieve a single action log entry by process_no. Requires Cafe24 partner approval.',
    scopeType: 'read',
    method: 'GET',
    path: 'activitylogs/{process_no}',
    requiredFields: ['process_no'],
    fields: {
      process_no: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_activitylogs,
  },
  {
    id: 'dashboard_get',
    label: '대시보드 조회',
    description: 'Retrieve aggregated dashboard information for the store.',
    scopeType: 'read',
    method: 'GET',
    path: 'dashboard',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'financials_paymentgateway_get',
    label: '결제대행사 계약 정보 조회',
    description:
      'Retrieve a list of payment gateway contract details. Requires Cafe24 partner approval (PG settings group).',
    scopeType: 'read',
    method: 'GET',
    path: 'financials/paymentgateway',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  {
    id: 'financials_store_get',
    label: '상점 거래 정보 조회',
    description: 'Retrieve transaction information of the store.',
    scopeType: 'read',
    method: 'GET',
    path: 'financials/store',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'menus_get',
    label: '메뉴 조회',
    description:
      'Retrieve admin menu structure of the mall. Requires Cafe24 partner approval.',
    scopeType: 'read',
    method: 'GET',
    path: 'menus',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    restrictedApproval: RESTRICTED_APPROVAL.store_menus,
  },
  // Batch 1-B — automessages·benefits·boards_setting·carts_setting
  {
    id: 'automessages_arguments_get',
    label: '자동 메시지 변수 목록',
    description: 'List available variables for automated messages.',
    scopeType: 'read',
    method: 'GET',
    path: 'automessages/arguments',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'automessages_setting_get',
    label: '자동 메시지 설정 조회',
    description: 'Retrieve the automated message settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'automessages/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'automessages_setting_update',
    label: '자동 메시지 설정 수정',
    description: 'Update automated message settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'automessages/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      send_method: {
        type: 'string',
        location: 'body',
        description: 'Delivery channel (e.g. sms/email).',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'benefits_setting_get',
    label: '혜택 설정 조회',
    description: 'Retrieve incentive (benefit) settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'benefits/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'benefits_setting_update',
    label: '혜택 설정 수정',
    description: 'Update incentive (benefit) settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'benefits/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'boards_setting_get',
    label: '게시판 설정 조회 (store)',
    description: 'Retrieve mall-wide board settings (store scope).',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'boards_setting_update',
    label: '게시판 설정 수정 (store)',
    description: 'Update mall-wide board settings (store scope).',
    scopeType: 'write',
    method: 'PUT',
    path: 'boards/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'carts_setting_get',
    label: '장바구니 설정 조회',
    description: 'Retrieve shopping-cart settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'carts/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'carts_setting_update',
    label: '장바구니 설정 수정',
    description: 'Update shopping-cart settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'carts/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  // Batch 1-C — categories_properties·coupons·currency·customers setting
  {
    id: 'categories_properties_setting_get',
    label: '카테고리 진열 추가 설정 조회',
    description:
      'Retrieve additional display settings for products in category lists.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/properties/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'categories_properties_setting_update',
    label: '카테고리 진열 추가 설정 수정',
    description:
      'Update additional display settings for products in category lists.',
    scopeType: 'write',
    method: 'PUT',
    path: 'categories/properties/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'coupons_setting_get',
    label: '쿠폰 설정 조회',
    description: 'Retrieve coupon settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'coupons_setting_update',
    label: '쿠폰 설정 수정',
    description: 'Update coupon settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'coupons/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'currency_get',
    label: '통화 설정 조회',
    description: 'Retrieve currency settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'currency',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'currency_update',
    label: '통화 수정',
    description: 'Update a currency.',
    scopeType: 'write',
    method: 'PUT',
    path: 'currency',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customers_setting_get',
    label: '회원 관련 설정 조회',
    description: 'Retrieve member-related settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customers_setting_update',
    label: '회원 관련 설정 수정',
    description: 'Update member-related settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'customers/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  // Batch 1-D — images·information·kakaoalimtalk·kakaopay setting
  {
    id: 'images_setting_get',
    label: '상품 이미지 크기 설정 조회',
    description: 'Retrieve product image size settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'images/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'images_setting_update',
    label: '상품 이미지 크기 설정 수정',
    description: 'Update product image size settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'images/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'information_get',
    label: '상점 정책 조회',
    description: 'Retrieve store policies (terms, privacy, etc.).',
    scopeType: 'read',
    method: 'GET',
    path: 'information',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'information_update',
    label: '상점 정책 수정',
    description: 'Update store policies.',
    scopeType: 'write',
    method: 'PUT',
    path: 'information',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'kakaoalimtalk_profile_get',
    label: '카카오 채널 발신자 프로필 키 조회',
    description: 'Retrieve the Kakao channel sender profile key.',
    scopeType: 'read',
    method: 'GET',
    path: 'kakaoalimtalk/profile',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'kakaoalimtalk_setting_get',
    label: '카카오 알림톡 설정 조회',
    description: 'Retrieve KakaoTalk notification settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'kakaoalimtalk/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'kakaoalimtalk_setting_update',
    label: '카카오 알림톡 설정 수정',
    description: 'Update KakaoTalk notification settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'kakaoalimtalk/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'kakaopay_setting_get',
    label: '카카오페이 주문 설정 조회',
    description:
      'Retrieve KakaoPay order settings. Requires Cafe24 partner approval.',
    scopeType: 'read',
    method: 'GET',
    path: 'kakaopay/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_kakaopay_setting,
  },
  {
    id: 'kakaopay_setting_update',
    label: '카카오페이 주문 설정 수정',
    description:
      'Update KakaoPay order settings. Requires Cafe24 partner approval.',
    scopeType: 'write',
    method: 'PUT',
    path: 'kakaopay/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_kakaopay_setting,
  },
  // Batch 1-E — mains_properties·mobile·naverpay·orderform setting
  {
    id: 'mains_properties_setting_get',
    label: '메인 진열 추가 설정 조회',
    description:
      'Retrieve additional display settings for products on the main screen.',
    scopeType: 'read',
    method: 'GET',
    path: 'mains/properties/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'mains_properties_setting_update',
    label: '메인 진열 추가 설정 수정',
    description:
      'Update additional display settings for products on the main screen.',
    scopeType: 'write',
    method: 'PUT',
    path: 'mains/properties/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'mobile_setting_get',
    label: '모바일 설정 조회',
    description: 'Retrieve mobile-storefront settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'mobile/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'mobile_setting_update',
    label: '모바일 설정 수정',
    description: 'Update mobile-storefront settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'mobile/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'naverpay_setting_get',
    label: '네이버페이 설정 조회',
    description:
      'Retrieve Naver Pay settings. Requires Cafe24 partner approval.',
    scopeType: 'read',
    method: 'GET',
    path: 'naverpay/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_naverpay_setting,
  },
  {
    id: 'naverpay_setting_create',
    label: '네이버페이 설정 생성',
    description: 'Create Naver Pay settings. Requires Cafe24 partner approval.',
    scopeType: 'write',
    method: 'POST',
    path: 'naverpay/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_naverpay_setting,
  },
  {
    id: 'naverpay_setting_update',
    label: '네이버페이 설정 수정',
    description: 'Update Naver Pay settings. Requires Cafe24 partner approval.',
    scopeType: 'write',
    method: 'PUT',
    path: 'naverpay/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_naverpay_setting,
  },
  {
    id: 'orderform_setting_get',
    label: '주문서 양식 설정 조회',
    description: 'Retrieve order form settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'orderform/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'orderform_setting_update',
    label: '주문서 양식 설정 수정',
    description: 'Update order form settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orderform/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  // Batch 1-F — orders·payment setting · paymentgateway_paymentmethods CUD · paymentmethods_paymentproviders_update_display · paymentservices_get
  {
    id: 'orders_setting_get',
    label: '주문 설정 조회',
    description: 'Retrieve order settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'orders_setting_update',
    label: '주문 설정 수정',
    description: 'Update order settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'orders_status_get',
    label: '주문 상태 표기 조회',
    description: 'Retrieve order-status display configuration (labels).',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/status',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'orders_status_update',
    label: '주문 상태 표기 수정',
    description: 'Update order-status display configuration (labels).',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/status',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'payment_setting_get',
    label: '결제 설정 조회',
    description: 'Retrieve payment settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'payment/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'payment_setting_update',
    label: '결제 설정 수정',
    description: 'Update payment settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'payment/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'paymentgateway_paymentmethods_create',
    label: '결제대행사 결제수단 생성',
    description:
      'Create a payment method for an existing payment gateway. Requires Cafe24 partner approval.',
    scopeType: 'write',
    method: 'POST',
    path: 'paymentgateway/{paymentgateway_id}/paymentmethods',
    requiredFields: ['paymentgateway_id'],
    fields: {
      paymentgateway_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  {
    id: 'paymentgateway_paymentmethods_update',
    label: '결제대행사 결제수단 수정',
    description:
      'Update a specific payment method of a payment gateway. Requires Cafe24 partner approval.',
    scopeType: 'write',
    method: 'PUT',
    path: 'paymentgateway/{paymentgateway_id}/paymentmethods/{paymentmethod_id}',
    requiredFields: ['paymentgateway_id', 'paymentmethod_id'],
    fields: {
      paymentgateway_id: { type: 'string', location: 'path' },
      paymentmethod_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  {
    id: 'paymentgateway_paymentmethods_delete',
    label: '결제대행사 결제수단 삭제',
    description:
      'Delete a specific payment method of a payment gateway. Requires Cafe24 partner approval.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'paymentgateway/{paymentgateway_id}/paymentmethods/{paymentmethod_id}',
    requiredFields: ['paymentgateway_id', 'paymentmethod_id'],
    fields: {
      paymentgateway_id: { type: 'string', location: 'path' },
      paymentmethod_id: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  {
    id: 'paymentmethods_paymentproviders_update_display',
    label: '결제수단 노출 상태 수정',
    description: 'Update the display (visibility) status of a payment method.',
    scopeType: 'write',
    method: 'PUT',
    path: 'paymentmethods/paymentproviders/{payment_method_id}',
    requiredFields: ['payment_method_id'],
    fields: {
      payment_method_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'paymentservices_get',
    label: 'PG 설정 목록 조회',
    description: 'Retrieve a list of registered PG (payment service) settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'paymentservices',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  // Batch 1-G — points·policy (privacy_* 6건은 본 PR §비-Scope, follow-up)
  {
    id: 'points_setting_get',
    label: '적립금 설정 조회',
    description: 'Retrieve mileage (points) settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'points/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'points_setting_update',
    label: '적립금 설정 수정',
    description: 'Update mileage (points) settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'points/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'policy_get',
    label: '상점 프로필 조회',
    description: 'Retrieve store profile (business policy/contact).',
    scopeType: 'read',
    method: 'GET',
    path: 'policy',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'policy_update',
    label: '상점 프로필 수정',
    description: 'Update store profile (business policy/contact).',
    scopeType: 'write',
    method: 'PUT',
    path: 'policy',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  // Batch 1-H — products_display·products_properties·products_setting · redirects · restocknotification
  {
    id: 'products_display_setting_list',
    label: '상품 진열 설정 목록',
    description: 'List product-display settings entries.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/display/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'products_display_setting_update',
    label: '상품 진열 설정 수정',
    description: 'Update a product-display settings entry.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/display/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'products_properties_setting_get',
    label: '상품 상세 추가 설정 조회',
    description: 'Retrieve additional settings for product detail pages.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/properties/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'products_properties_setting_update',
    label: '상품 상세 추가 설정 수정',
    description: 'Update additional settings for product detail pages.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/properties/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'products_setting_get',
    label: '상품 설정 조회',
    description: 'Retrieve product settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'redirects_list',
    label: '리다이렉트 목록',
    description: 'List URL redirects defined on the storefront.',
    scopeType: 'read',
    method: 'GET',
    path: 'redirects',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'redirects_create',
    label: '리다이렉트 생성',
    description: 'Create a URL redirect.',
    scopeType: 'write',
    method: 'POST',
    path: 'redirects',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'redirects_update',
    label: '리다이렉트 수정',
    description: 'Update an existing URL redirect.',
    scopeType: 'write',
    method: 'PUT',
    path: 'redirects/{redirect_no}',
    requiredFields: ['redirect_no'],
    fields: {
      redirect_no: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'redirects_delete',
    label: '리다이렉트 삭제',
    description: 'Delete a URL redirect by redirect_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'redirects/{redirect_no}',
    requiredFields: ['redirect_no'],
    fields: {
      redirect_no: { type: 'string', location: 'path' },
    },
    responseShape: 'empty',
  },
  {
    id: 'restocknotification_setting_get',
    label: '재입고 알림 설정 조회',
    description: 'Retrieve restock-notification settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'restocknotification/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'restocknotification_setting_update',
    label: '재입고 알림 설정 수정',
    description: 'Update restock-notification settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'restocknotification/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  // Batch 1-I — seo · shippingmanager · sms · socials (apple/kakao/naver)
  {
    id: 'seo_setting_get',
    label: 'SEO 설정 조회',
    description: 'Retrieve SEO settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'seo/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'seo_setting_update',
    label: 'SEO 설정 수정',
    description: 'Update SEO settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'seo/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shippingmanager_get',
    label: '배송 매니저 활성화 정보',
    description:
      'Retrieve activation information for the shipping manager add-on.',
    scopeType: 'read',
    method: 'GET',
    path: 'shippingmanager',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'sms_setting_get',
    label: 'SMS 설정 조회',
    description: 'Retrieve SMS settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'sms/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'sms_setting_update',
    label: 'SMS 설정 수정',
    description: 'Update SMS settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'sms/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'socials_apple_get',
    label: 'Apple 로그인 연동 상세',
    description: 'Retrieve Apple login integration details.',
    scopeType: 'read',
    method: 'GET',
    path: 'socials/apple',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'socials_apple_settings_get',
    label: 'Apple 로그인 연동 설정',
    description: 'Retrieve Apple login integration settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'socials/apple/settings',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'socials_kakaosync_get',
    label: '카카오 싱크 상세',
    description: 'Retrieve KakaoSync integration details.',
    scopeType: 'read',
    method: 'GET',
    path: 'socials/kakaosync',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'socials_kakaosync_update',
    label: '카카오 싱크 수정',
    description: 'Update KakaoSync integration settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'socials/kakaosync',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'socials_naverlogin_get',
    label: '네이버 로그인 상세',
    description: 'Retrieve Naver login integration details.',
    scopeType: 'read',
    method: 'GET',
    path: 'socials/naverlogin',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'socials_naverlogin_update',
    label: '네이버 로그인 수정',
    description: 'Update Naver login integration settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'socials/naverlogin',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'socials_navershopping_get',
    label: '네이버 쇼핑 설정',
    description: 'Retrieve Naver Shopping integration settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'socials/navershopping',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  // Batch 1-J — store_accounts · dropshipping · store_setting · subscription · taxmanager · users
  {
    id: 'store_accounts_list',
    label: '상점 계좌 목록',
    description: 'List the bank accounts registered to the store.',
    scopeType: 'read',
    method: 'GET',
    path: 'store/accounts',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'store_dropshipping_get',
    label: '위탁배송 설정 조회',
    description: 'Retrieve dropshipping settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'store/dropshipping',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'store_dropshipping_manage',
    label: '위탁배송 설정 관리',
    description: 'Manage dropshipping settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'store/dropshipping',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'store_setting_get',
    label: '상점 보안 설정 조회',
    description: 'Retrieve store security settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'store/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'store_setting_update',
    label: '상점 보안 설정 수정',
    description: 'Update store security settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'store/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'subscription_shipments_setting_list',
    label: '정기배송 상품 목록',
    description: 'List subscription shipping products.',
    scopeType: 'read',
    method: 'GET',
    path: 'subscription/shipments/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'subscription_shipments_setting_create_rule',
    label: '정기배송 결제 규칙 생성',
    description: 'Create a subscription payment rule.',
    scopeType: 'write',
    method: 'POST',
    path: 'subscription/shipments/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'subscription_shipments_setting_update',
    label: '정기배송 상품 수정',
    description: 'Update subscription shipping products.',
    scopeType: 'write',
    method: 'PUT',
    path: 'subscription/shipments/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'subscription_shipments_setting_delete',
    label: '정기배송 상품 삭제',
    description: 'Delete subscription shipping products.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'subscription/shipments/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'empty',
  },
  {
    id: 'taxmanager_get',
    label: '세금 매니저 활성화 정보',
    description: 'Retrieve activation information for the tax manager add-on.',
    scopeType: 'read',
    method: 'GET',
    path: 'taxmanager',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'users_list',
    label: '운영자 사용자 목록',
    description: 'List admin users with optional filters.',
    scopeType: 'read',
    method: 'GET',
    path: 'users',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'users_get',
    label: '운영자 사용자 상세',
    description: 'Retrieve a single admin user by user_id.',
    scopeType: 'read',
    method: 'GET',
    path: 'users/{user_id}',
    requiredFields: ['user_id'],
    fields: {
      user_id: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
];
