import type { Cafe24OperationMetadata } from './types.js';
import { RESTRICTED_APPROVAL } from './restricted-approval.js';

export const storeOperations: Cafe24OperationMetadata[] = [
  {
    id: 'store_get',
    label: '상점 정보 조회',
    description: 'Get the mall (store) information.',
    scopeType: 'read',
    method: 'GET',
    path: 'store',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shops_list',
    label: '멀티쇼핑몰 목록 조회',
    description: 'List shops in a multi-shop mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'shops',
    requiredFields: [],
    fields: {},
    responseShape: 'list',
  },
  // Phase 6b — 결제 설정 (paymentmethods / paymentgateway)
  {
    id: 'paymentmethods_list',
    label: '결제수단 목록',
    description: 'List available payment methods.',
    scopeType: 'read',
    method: 'GET',
    path: 'paymentmethods',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'paymentmethods_paymentproviders_list',
    label: '결제수단별 제공사 목록',
    description: 'List the providers (PG) registered per payment method.',
    scopeType: 'read',
    method: 'GET',
    path: 'paymentmethods/paymentproviders',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'paymentgateway_paymentmethods_list',
    label: '결제대행사 결제수단 목록',
    description:
      'List the payment methods attached to the registered payment gateways.',
    scopeType: 'read',
    method: 'GET',
    path: 'paymentgateway/paymentmethods',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  {
    id: 'paymentgateway_create',
    label: '결제대행사 생성',
    description:
      'Register a new payment gateway (PG). `pg_code` + `pg_name` required.',
    scopeType: 'write',
    method: 'POST',
    path: 'paymentgateway',
    requiredFields: ['pg_code', 'pg_name'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      pg_code: { type: 'string', location: 'body' },
      pg_name: { type: 'string', location: 'body' },
      use_yn: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Enable flag (T=on, F=off)',
      },
      authentication_key: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  {
    id: 'paymentgateway_update',
    label: '결제대행사 수정',
    description: 'Update an existing payment gateway by paymentgateway_id.',
    scopeType: 'write',
    method: 'PUT',
    path: 'paymentgateway/{paymentgateway_id}',
    requiredFields: ['paymentgateway_id'],
    fields: {
      paymentgateway_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      pg_name: { type: 'string', location: 'body' },
      use_yn: { type: 'enum', location: 'body', enum: ['T', 'F'] },
      authentication_key: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  {
    id: 'paymentgateway_delete',
    label: '결제대행사 삭제',
    description: 'Remove a registered payment gateway by paymentgateway_id.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'paymentgateway/{paymentgateway_id}',
    requiredFields: ['paymentgateway_id'],
    fields: {
      paymentgateway_id: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  // Batch 1-A — shops·activitylogs·dashboard·financials·menus
  {
    id: 'shops_get',
    label: '멀티쇼핑몰 단건 조회',
    description: 'Retrieve a single shop within a multi-shop mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'shops/{shop_no}',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'activitylogs_list',
    label: '액션 로그 목록',
    description:
      'List operator activity logs within a date range. Requires Cafe24 partner approval.',
    scopeType: 'read',
    method: 'GET',
    path: 'activitylogs',
    requiredFields: ['start_date', 'end_date'],
    fields: {
      start_date: { type: 'string', location: 'query' },
      end_date: { type: 'string', location: 'query' },
      manager_type: {
        type: 'enum',
        location: 'query',
        enum: ['P', 'A', 'S'],
        description: 'Operator type filter (P/A/S)',
      },
      manager_id: { type: 'string', location: 'query' },
      mode: {
        type: 'enum',
        location: 'query',
        enum: ['P', 'M', 'S'],
      },
      type: { type: 'string', location: 'query' },
      content: { type: 'string', location: 'query' },
      offset: { type: 'number', location: 'query', default: 0 },
      limit: { type: 'number', location: 'query', default: 10 },
    },
    responseShape: 'list',
    paginated: true,
    restrictedApproval: RESTRICTED_APPROVAL.store_activitylogs,
  },
  {
    id: 'activitylogs_get',
    label: '액션 로그 단건 조회',
    description:
      'Retrieve a single action log entry by process_no. Requires Cafe24 partner approval.',
    scopeType: 'read',
    method: 'GET',
    path: 'activitylogs/{process_no}',
    requiredFields: ['process_no'],
    fields: {
      process_no: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
    restrictedApproval: RESTRICTED_APPROVAL.store_activitylogs,
  },
  {
    id: 'dashboard_get',
    label: '대시보드 조회',
    description: 'Retrieve aggregated dashboard information for the store.',
    scopeType: 'read',
    method: 'GET',
    path: 'dashboard',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'financials_paymentgateway_get',
    label: '결제대행사 계약 정보 조회',
    description:
      'Retrieve a list of payment gateway contract details. Requires Cafe24 partner approval (PG settings group).',
    scopeType: 'read',
    method: 'GET',
    path: 'financials/paymentgateway',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
    restrictedApproval: RESTRICTED_APPROVAL.store_pg_settings,
  },
  {
    id: 'financials_store_get',
    label: '상점 거래 정보 조회',
    description: 'Retrieve transaction information of the store.',
    scopeType: 'read',
    method: 'GET',
    path: 'financials/store',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'menus_get',
    label: '메뉴 조회',
    description:
      'Retrieve admin menu structure of the mall. Requires Cafe24 partner approval.',
    scopeType: 'read',
    method: 'GET',
    path: 'menus',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    restrictedApproval: RESTRICTED_APPROVAL.store_menus,
  },
  // Batch 1-B — automessages·benefits·boards_setting·carts_setting
  {
    id: 'automessages_arguments_get',
    label: '자동 메시지 변수 목록',
    description: 'List available variables for automated messages.',
    scopeType: 'read',
    method: 'GET',
    path: 'automessages/arguments',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'automessages_setting_get',
    label: '자동 메시지 설정 조회',
    description: 'Retrieve the automated message settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'automessages/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'automessages_setting_update',
    label: '자동 메시지 설정 수정',
    description: 'Update automated message settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'automessages/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      send_method: {
        type: 'string',
        location: 'body',
        description: 'Delivery channel (e.g. sms/email).',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'benefits_setting_get',
    label: '혜택 설정 조회',
    description: 'Retrieve incentive (benefit) settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'benefits/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'benefits_setting_update',
    label: '혜택 설정 수정',
    description: 'Update incentive (benefit) settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'benefits/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'boards_setting_get',
    label: '게시판 설정 조회 (store)',
    description: 'Retrieve mall-wide board settings (store scope).',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'boards_setting_update',
    label: '게시판 설정 수정 (store)',
    description: 'Update mall-wide board settings (store scope).',
    scopeType: 'write',
    method: 'PUT',
    path: 'boards/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'carts_setting_get',
    label: '장바구니 설정 조회',
    description: 'Retrieve shopping-cart settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'carts/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'carts_setting_update',
    label: '장바구니 설정 수정',
    description: 'Update shopping-cart settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'carts/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  // Batch 1-C — categories_properties·coupons·currency·customers setting
  {
    id: 'categories_properties_setting_get',
    label: '카테고리 진열 추가 설정 조회',
    description: 'Retrieve additional display settings for products in category lists.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/properties/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'categories_properties_setting_update',
    label: '카테고리 진열 추가 설정 수정',
    description: 'Update additional display settings for products in category lists.',
    scopeType: 'write',
    method: 'PUT',
    path: 'categories/properties/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'coupons_setting_get',
    label: '쿠폰 설정 조회',
    description: 'Retrieve coupon settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'coupons_setting_update',
    label: '쿠폰 설정 수정',
    description: 'Update coupon settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'coupons/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'currency_get',
    label: '통화 설정 조회',
    description: 'Retrieve currency settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'currency',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'currency_update',
    label: '통화 수정',
    description: 'Update a currency.',
    scopeType: 'write',
    method: 'PUT',
    path: 'currency',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customers_setting_get',
    label: '회원 관련 설정 조회',
    description: 'Retrieve member-related settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customers_setting_update',
    label: '회원 관련 설정 수정',
    description: 'Update member-related settings.',
    scopeType: 'write',
    method: 'PUT',
    path: 'customers/setting',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
];
