import type { MakeshopOperationMetadata } from './types.js';

export const shopOperations: MakeshopOperationMetadata[] = [
  {
    id: 'get-authority',
    description:
      '상점 권한을 조회합니다. 해당 상점에 등록된 경우 Shopkey 없이 조회가 가능합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'authority',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-bank_account',
    description: '상점에 등록된 무통장 계좌 정보를 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'bank_account',
    requiredFields: [],
    fields: {},
    responseShape: 'list',
  },
  {
    id: 'get-cart_free_config',
    description: '카트프리 설정값을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'cart_free_config',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-cart_free_config-update',
    description: '카트프리 설정을 변경합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'cart_free_config/update',
    requiredFields: ['use'],
    fields: {
      use: {
        type: 'string',
        location: 'query',
        description: '카트프리 사용여부 (Y : 사용함, N : 사용안함)',
      },
      select_product: {
        type: 'string',
        location: 'query',
        description:
          '상품 선택 (ALL : 전체, CATEGORY : 카테고리 상품, PRODUCT : 상품 선택)',
      },
      price_range_set: {
        type: 'string',
        location: 'query',
        description: '가격 범위 지정 (ALL : 전체 상품, RANGE : 범위 설정)',
      },
      price_range_start: {
        type: 'string',
        location: 'query',
        description: '무료배송기준 (-)범위 금액',
      },
      price_range_end: {
        type: 'string',
        location: 'query',
        description: '무료배송기준 (+)범위 금액',
      },
      product_sort: {
        type: 'string',
        location: 'query',
        description: '상품정렬 (BEST : 판매순, NEW : 신상품순)',
      },
      codes: {
        type: 'array',
        location: 'query',
        description:
          '분류 코드 (ex.codes[0][cate1]=001,codes[0][cate2]=001,codes[0][cate3]=001)',
      },
      uids: {
        type: 'array',
        location: 'query',
        description: '다중 상품 번호 (ex.uids[]=10000000,uids[]=10000001)',
      },
      versions: {
        type: 'array',
        location: 'query',
        description: '버전 선택 (ex.versions[]=PC,versions[]=MOBILE)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'get-crm_board_config',
    description: '1:1 문의 게시판 설정을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'crm_board_config',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-delivery_company',
    description: '상점의 택배사 정보를 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'delivery_company',
    requiredFields: [],
    fields: {},
    responseShape: 'list',
  },
  {
    id: 'get-information',
    description:
      '상점의 기본 정보를 조회합니다. 상점에 설정된 배송 정보를 포함하고 있습니다. 상점 메인 노출 정보를 포함하고 있습니다. 조회시 검색 조건을 지원하지 않습니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'information',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-kakaopay',
    description: '카카오페이 바로구매 설정값을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'kakaopay',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-main_display_code',
    description:
      '메인 화면 상품 진열에 설정된 항목을 조회합니다. (구)메인상품 상품 진열 관리 사용 상점은 지원되지 않습니다. [상품 > 진열 > 메인 진열 설정]에서 신버전으로 변경시 이용 가능합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'main_display_code',
    requiredFields: [],
    fields: {},
    responseShape: 'list',
  },
  {
    id: 'get-naverpay',
    description: '네이버페이 설정값을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'naverpay',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-order_config',
    description: '주문서 2.0 관련 설정값을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'order_config',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-page_min_image_size',
    description: '메인, 상품화면의 최소 이미지 크기를 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'page_min_image_size',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-page_seo',
    description:
      '상점의 페이지 SEO 정보를 조회할 수 있습니다. page_type 은 필수 입력값 입니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'page_seo',
    requiredFields: ['page_type'],
    fields: {
      page_type: {
        type: 'string',
        location: 'query',
        description: '페이지 타입 (페이지 API 참고)',
      },
      code: {
        type: 'string',
        location: 'query',
        description: '코드 (게시판, 상품분류인 경우)',
      },
      num1: {
        type: 'string',
        location: 'query',
        description: '게시판 SEO 조회 시 (게시글 번호)',
      },
      cat1: {
        type: 'string',
        location: 'query',
        description: '대분류 (상품분류 SEO 조회 시)',
      },
      cat2: {
        type: 'string',
        location: 'query',
        description: '중분류 (상품분류 SEO 조회 시)',
      },
      cat3: {
        type: 'string',
        location: 'query',
        description: '소분류 (상품분류 SEO 조회 시)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'get-payco',
    description: '페이코 바로구매 설정값을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'payco',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-privacy',
    description: '회원 약관 내역 추가 사항을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'privacy',
    requiredFields: [],
    fields: {
      limit: {
        type: 'string',
        location: 'query',
        description: '검색 한도 (MAX: 5000 (default))',
      },
      page: {
        type: 'string',
        location: 'query',
        description: '검색할 페이지 (default: 1)',
      },
      privacy_uid: {
        type: 'string',
        location: 'query',
        description: '회원 약관 등록 ID',
      },
      purpose: { type: 'string', location: 'query', description: '사용 목적' },
      recipient: {
        type: 'string',
        location: 'query',
        description: '정보 수집자',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'get-product_neogift',
    description: '고급형 사은품 이벤트 설정을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'product_neogift',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-provider_sub_admin',
    description: '공급자 부운영자 조회',
    scopeType: 'read',
    method: 'GET',
    path: 'provider_sub_admin',
    requiredFields: ['provider_id'],
    fields: {
      provider_id: {
        type: 'string',
        location: 'query',
        description: '공급자ID',
      },
    },
    responseShape: 'list',
  },
  {
    id: 'get-smart_coupon_config',
    description:
      '스마트 쿠폰 설정 정보를 조회합니다. 스마트 쿠폰 이용가능 상점만 조회 가능합니다. (이용 불가 상점의 경우, 9008 에러코드가 반환됩니다.)',
    scopeType: 'read',
    method: 'GET',
    path: 'smart_coupon_config',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-smart_reserve_config',
    description:
      '스마트 적립금 설정 정보를 조회합니다. 스마트 적립금 이용가능 상점만 조회 가능합니다. (이용 불가 상점의 경우, 9008 에러코드가 반환됩니다.)',
    scopeType: 'read',
    method: 'GET',
    path: 'smart_reserve_config',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-sms_config',
    description: 'SMS 서비스 설정 정보를 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'sms_config',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-social_apple',
    description: '간편가입 Apple 연동 설정값을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'social_apple',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-social_facebook',
    description: '간편가입 Facebook 연동 설정값을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'social_facebook',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-social_kakao',
    description: '간편가입 카카오 연동 설정값을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'social_kakao',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-social_naver',
    description: '간편가입 네이버 연동 설정값을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'social_naver',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'get-sub_admin',
    description: '부운영자의 정보 및 권한을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'sub_admin',
    requiredFields: [],
    fields: {
      sub_admin_id: {
        type: 'string',
        location: 'query',
        description: '부운영자 ID',
      },
      fields: { type: 'string', location: 'query', description: '조회필드' },
    },
    responseShape: 'list',
  },
  {
    id: 'get-subs_config',
    description: '정기배송/구독 관련 설정값을 조회합니다.',
    scopeType: 'read',
    method: 'GET',
    path: 'subs_config',
    requiredFields: [],
    fields: {},
    responseShape: 'single',
  },
  {
    id: 'post-kakaopay',
    description: '상점에 카카오페이 바로구매 결제방식을 등록합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'kakaopay',
    requiredFields: [
      'checkout',
      'pc_button_type',
      'mobile_button_type',
      'direct_order',
    ],
    fields: {
      checkout: {
        type: 'string',
        location: 'body',
        description: '바로구매 사용여부 (Y : 사용함, N : 사용안함)',
      },
      pc_button_type: {
        type: 'string',
        location: 'body',
        description: 'PC 버튼 디자인 타입 (A1,B1,C1)',
      },
      mobile_button_type: {
        type: 'string',
        location: 'body',
        description: 'MOBILE 버튼 디자인 타입 (A1,B1,C1)',
      },
      direct_order: {
        type: 'string',
        location: 'body',
        description:
          '바로구매 시 장바구니 옵션 처리 (Y : 사용함, N : 사용안함)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'post-naverpay',
    description: '상점에 네이버페이 결제방식을 등록합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'naverpay',
    requiredFields: [
      'enabled',
      'mobile_enabled',
      'naverpay_id',
      'auth_key',
      'button_key',
      'pc_button_type',
      'mobile_button_type',
      'order_target',
      'order_linkage',
      'product_stock_linkage',
      'review_linkage',
      'cts_linkage',
      'return_delicom',
    ],
    fields: {
      enabled: {
        type: 'string',
        location: 'body',
        description: '사용여부 (Y : 사용함, N : 사용안함)',
      },
      mobile_enabled: {
        type: 'string',
        location: 'body',
        description: '모바일 사용여부 (Y : 사용함, N : 사용안함)',
      },
      naverpay_id: {
        type: 'string',
        location: 'body',
        description: '네이버페이 아이디',
      },
      auth_key: { type: 'string', location: 'body', description: '인증키' },
      button_key: { type: 'string', location: 'body', description: '버튼키' },
      pc_button_type: {
        type: 'string',
        location: 'body',
        description:
          'PC 버튼 디자인 타입 (A_1,B_1,C_1,C_2,C_3,D_1,D_2,D_3,E_1,E_2,E_3)',
      },
      mobile_button_type: {
        type: 'string',
        location: 'body',
        description: 'MOBILE 버튼 디자인 타입 (MA_1,MA_2,MB_1,MB_2)',
      },
      except_cate: {
        type: 'string',
        location: 'body',
        description: '구매 제외 분류',
      },
      except_uid: {
        type: 'string',
        location: 'body',
        description: '구매 제외 상품 번호',
      },
      order_target: {
        type: 'string',
        location: 'body',
        description: '버튼키 (SELF : 현재창, BLANK : 새창 (기본값 : SELF))',
      },
      order_linkage: {
        type: 'string',
        location: 'body',
        description: '주문내역 연동 (Y : 사용함, N : 사용안함)',
      },
      product_stock_linkage: {
        type: 'string',
        location: 'body',
        description: '상품 재고 연동 (Y : 사용함, N : 사용안함)',
      },
      review_linkage: {
        type: 'string',
        location: 'body',
        description: '상품 리뷰 연동 (Y : 사용함, N : 사용안함)',
      },
      cts_linkage: {
        type: 'string',
        location: 'body',
        description: 'CTS 연동 (Y : 사용함, N : 사용안함)',
      },
      return_delicom: {
        type: 'string',
        location: 'body',
        description:
          '반품 택배사 코드 (API문서 상점정보>상점설정정보>택배사조회)',
      },
      return_deli_price: {
        type: 'string',
        location: 'body',
        description: '착불 배송료 (기본값 0)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'post-page_min_image_size',
    description: '메인, 상품화면의 최소 이미지 크기를 설정합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'page_min_image_size',
    requiredFields: ['min_image_size'],
    fields: {
      min_image_size: {
        type: 'string',
        location: 'body',
        description: '상품 이미지 최소 사이즈',
      },
      allow_height_use: {
        type: 'string',
        location: 'body',
        description: '허용 세로 픽셀 사용여부 (Y : 사용함, N : 사용안함)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'post-page_seo',
    description: '페이지 검색엔진 최적화(SEO) 설정을 등록합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'page_seo',
    requiredFields: ['enabled', 'kakao_type', 'api_key', 'page_type'],
    fields: {
      enabled: { type: 'string', location: 'query', description: 'ex.Y' },
      kakao_type: {
        type: 'string',
        location: 'query',
        description: 'ex.login',
      },
      api_key: { type: 'string', location: 'query' },
      page_type: {
        type: 'string',
        location: 'body',
        description: '페이지타입',
      },
      code: {
        type: 'string',
        location: 'body',
        description: '코드 (게시판, 상품분류인 경우 입력)',
      },
      title: { type: 'string', location: 'body', description: '페이지명' },
      description: { type: 'string', location: 'body', description: '설명' },
      keywords: { type: 'string', location: 'body', description: '키워드' },
    },
    responseShape: 'single',
  },
  {
    id: 'post-payco',
    description: '상점에 페이코 바로구매 결제방식을 등록합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'payco',
    requiredFields: [
      'checkout',
      'pc_button_type',
      'mobile_button_type',
      'direct_order',
    ],
    fields: {
      checkout: {
        type: 'string',
        location: 'body',
        description: '바로구매 사용여부 (Y : 사용함, N : 사용안함)',
      },
      pc_button_type: {
        type: 'string',
        location: 'body',
        description: 'PC 버튼 디자인 타입 (A1,B1,C1)',
      },
      mobile_button_type: {
        type: 'string',
        location: 'body',
        description: 'MOBILE 버튼 디자인 타입 (A1,B1,C1)',
      },
      except_cate: {
        type: 'array',
        location: 'body',
        description: '구매 제외 분류',
      },
      except_uid: {
        type: 'array',
        location: 'body',
        description: '구매 제외 상품 번호',
      },
      direct_order: {
        type: 'string',
        location: 'body',
        description:
          '바로구매 시 장바구니 옵션 처리 (Y : 사용함, N : 사용안함)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'post-product_neogift',
    description: '고급형 사은품 이벤트 설정값을 변경합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'product_neogift',
    requiredFields: [],
    fields: {
      use: {
        type: 'string',
        location: 'body',
        description: '사은품 이벤트 사용여부 (Y : 사용함, N : 사용안함)',
      },
      provide_type: {
        type: 'string',
        location: 'body',
        description:
          '사은품 제공 금액 기준 (origin : 상품할인 후 상품 금액, sale_emoney : 최종 결제 금액 + 예치금, sale_money : 최종 결제 금액)',
      },
      except_free: {
        type: 'string',
        location: 'body',
        description:
          '최종금액 0원 사은품 미제공 여부 (Y : 제공안함, N : 제공함',
      },
      except_delivery_price: {
        type: 'string',
        location: 'body',
        description: '배송비 사은품 제외 (Y : 제외함, N : 제외안함)',
      },
      price_provide_type: {
        type: 'string',
        location: 'body',
        description:
          '금액별 사은품 제공 방법 (point : 사은품 포인트, product : N개 선택)',
      },
      gift_pages: {
        type: 'string',
        location: 'body',
        description:
          '사은품 선택 화면 노출 (order_pay : 주문서 작성, pop_order_complate : 주문완료(자동), button_order_complate : 주문완료(버튼), button_order_list : 주',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'post-provider_sub_admin-create',
    description: '공급자 부운영자 계정을 등록합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'provider_sub_admin/create',
    requiredFields: ['provider_id', 'sub_admin_id', 'password', 'access_auths'],
    fields: {
      provider_id: {
        type: 'string',
        location: 'body',
        description: '공급자 ID',
      },
      sub_admin_id: {
        type: 'string',
        location: 'body',
        description: '공급자 ID',
      },
      password: { type: 'string', location: 'body', description: '비밀번호' },
      name: { type: 'string', location: 'body', description: '부운영자명' },
      access_auths: {
        type: 'object',
        location: 'body',
        description: '메뉴접근 권한',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'post-provider_sub_admin-delete',
    description: '공급자 부운영자 계정을 삭제합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'provider_sub_admin/delete',
    requiredFields: ['provider_id', 'sub_admin_id'],
    fields: {
      provider_id: {
        type: 'string',
        location: 'body',
        description: '공급자 ID',
      },
      sub_admin_id: {
        type: 'string',
        location: 'body',
        description: '공급자 ID',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'post-provider_sub_admin-update',
    description: '공급자 부운영자 계정정보를 수정합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'provider_sub_admin/update',
    requiredFields: ['provider_id', 'sub_admin_id'],
    fields: {
      provider_id: {
        type: 'string',
        location: 'body',
        description: '공급자 ID',
      },
      sub_admin_id: {
        type: 'string',
        location: 'body',
        description: '공급자 ID',
      },
      password: { type: 'string', location: 'body', description: '비밀번호' },
      name: { type: 'string', location: 'body', description: '부운영자명' },
      access_auths: {
        type: 'object',
        location: 'body',
        description: '메뉴접근 권한',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'post-social_apple',
    description: 'Apple과 연동하여, 간편가입 기능을 제공합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'social_apple',
    requiredFields: ['enabled'],
    fields: {
      enabled: {
        type: 'string',
        location: 'body',
        description: 'social apple 사용여부 (Y : 사용함, N : 사용안함)',
      },
      client_id: {
        type: 'string',
        location: 'body',
        description: '클라이언트 아이디',
      },
      team_id: { type: 'string', location: 'body', description: '팀 아이디' },
      key_id: { type: 'string', location: 'body', description: 'Key 아이디' },
      filename: {
        type: 'string',
        location: 'body',
        description: 'Private key 파일명. 예) AuthKey_2YD6PC1234.p8',
      },
      file_content: {
        type: 'string',
        location: 'body',
        description:
          'Private key 파일 내용. 예) MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdw...',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'post-social_facebook',
    description: 'Facebook과 연동하여, 간편가입 기능을 제공합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'social_facebook',
    requiredFields: ['enabled'],
    fields: {
      enabled: {
        type: 'string',
        location: 'body',
        description: 'social facebook 사용여부 (Y : 사용함, N : 사용안함)',
      },
      app_id: { type: 'string', location: 'body', description: '앱 아이디' },
      app_secret: {
        type: 'string',
        location: 'body',
        description: '앱 시크릿 코드',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'post-social_kakao',
    description:
      '카카오와 연동하여, 간편가입 기능을 제공합니다. 카카오와 먼저 연동을 한 후 openapi 연동을 해야합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'social_kakao',
    requiredFields: ['enabled'],
    fields: {
      enabled: {
        type: 'string',
        location: 'body',
        description: 'social kakao 사용여부 (Y : 사용함, N : 사용안함)',
      },
      kakao_type: {
        type: 'string',
        location: 'body',
        description: '연동 방식 (login : 카카오 로그인, sync : 카카오 싱크)',
      },
      api_key: {
        type: 'string',
        location: 'body',
        description: 'rest api key',
      },
      js_key: {
        type: 'string',
        location: 'body',
        description: 'javascript Key',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'post-social_naver',
    description: '네이버와 연동하여, 간편가입 기능을 제공합니다.',
    scopeType: 'write',
    method: 'POST',
    path: 'social_naver',
    requiredFields: ['enabled'],
    fields: {
      enabled: {
        type: 'string',
        location: 'body',
        description: 'social naver 사용여부',
      },
      client_id: { type: 'string', location: 'body', description: 'Client ID' },
      client_secret: {
        type: 'string',
        location: 'body',
        description: 'Client Secret',
      },
      category: { type: 'string', location: 'body', description: '카테고리' },
    },
    responseShape: 'single',
  },
];
