import type { Cafe24OperationMetadata } from './types.js';

export const categoryOperations: Cafe24OperationMetadata[] = [
  {
    id: 'category_list',
    label: '카테고리 목록 조회',
    description: 'List product categories in the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      parent_category_no: { type: 'number', location: 'query' },
      display: { type: 'enum', location: 'query', enum: ['T', 'F'] },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'category_get',
    label: '카테고리 단건 조회',
    description: 'Get a single category by category_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/{category_no}',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'category_create',
    label: '카테고리 생성',
    description: 'Create a new category.',
    scopeType: 'write',
    method: 'POST',
    path: 'categories',
    requiredFields: ['category_name'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      parent_category_no: { type: 'number', location: 'body' },
      category_name: { type: 'string', location: 'body' },
      category_depth: { type: 'number', location: 'body' },
      display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'T',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'category_update',
    label: '카테고리 수정',
    description: 'Update a category.',
    scopeType: 'write',
    method: 'PUT',
    path: 'categories/{category_no}',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      category_name: { type: 'string', location: 'body' },
      display: { type: 'enum', location: 'body', enum: ['T', 'F'] },
    },
    responseShape: 'single',
  },
  {
    id: 'category_delete',
    label: '카테고리 삭제',
    description: 'Delete a category by category_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'categories/{category_no}',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'category_products_list',
    label: '카테고리별 상품 목록 조회',
    description: 'List products belonging to a category.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/{category_no}/products',
    requiredFields: ['category_no'],
    fields: {
      category_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
      display_group: {
        type: 'enum',
        location: 'query',
        enum: ['1', '2', '3'],
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  // Phase 6d — category baselines
  {
    id: 'category_count',
    label: '카테고리 개수 조회',
    description: 'Retrieve the count of product categories.',
    scopeType: 'read',
    method: 'GET',
    path: 'categories/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'mains_list',
    label: '메인 카테고리 목록',
    description: 'List the main categories pinned to the storefront home.',
    scopeType: 'read',
    method: 'GET',
    path: 'mains',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'autodisplay_list',
    label: '자동 진열 목록',
    description: 'List automated category display layouts.',
    scopeType: 'read',
    method: 'GET',
    path: 'autodisplay',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
];
