import type { Cafe24OperationMetadata } from './types.js';

export const collectionOperations: Cafe24OperationMetadata[] = [
  {
    id: 'brands_list',
    label: '브랜드 목록 조회',
    description: 'List brands in the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'brands',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'manufacturers_list',
    label: '제조사 목록 조회',
    description: 'List manufacturers.',
    scopeType: 'read',
    method: 'GET',
    path: 'manufacturers',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'trends_list',
    label: '트렌드 목록 조회',
    description: 'List trends.',
    scopeType: 'read',
    method: 'GET',
    path: 'trends',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  // Phase 6d — collection (brands CRUD baseline)
  {
    id: 'brands_count',
    label: '브랜드 개수 조회',
    description: 'Retrieve the count of brands.',
    scopeType: 'read',
    method: 'GET',
    path: 'brands/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'brands_create',
    label: '브랜드 생성',
    description: 'Create a brand. brand_name required.',
    scopeType: 'write',
    method: 'POST',
    path: 'brands',
    requiredFields: ['brand_name'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      brand_name: { type: 'string', location: 'body' },
      brand_code: { type: 'string', location: 'body' },
      brand_description: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'brands_update',
    label: '브랜드 수정',
    description: 'Update a brand by brand_code.',
    scopeType: 'write',
    method: 'PUT',
    path: 'brands/{brand_code}',
    requiredFields: ['brand_code'],
    fields: {
      brand_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      brand_name: { type: 'string', location: 'body' },
      brand_description: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'brands_delete',
    label: '브랜드 삭제',
    description: 'Delete a brand by brand_code.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'brands/{brand_code}',
    requiredFields: ['brand_code'],
    fields: {
      brand_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
];
