import type { Cafe24OperationMetadata } from './types.js';

export const communityOperations: Cafe24OperationMetadata[] = [
  {
    id: 'boards_list',
    label: '게시판 목록 조회',
    description: 'List boards in the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'boards',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'board_articles_list',
    label: '게시판 글 목록 조회',
    description: 'List articles in a specific board.',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}/articles',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'board_article_get',
    label: '게시판 글 단건 조회',
    description: 'Get a single article.',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}/articles/{article_no}',
    requiredFields: ['board_no', 'article_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  // Phase 7c — Community boards CRUD + comments + commenttemplates + urgentinquiry
  {
    id: 'boards_settings_get',
    label: '게시판 설정 조회',
    description: 'Retrieve a board\'s settings.',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'boards_settings_update',
    label: '게시판 설정 수정',
    description: 'Update a board\'s settings (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'boards/{board_no}',
    requiredFields: ['board_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      board_name: { type: 'string', location: 'body' },
      use_board: { type: 'enum', location: 'body', enum: ['T', 'F'] },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_create',
    label: '게시판 글 작성',
    description: 'Create a board article.',
    scopeType: 'write',
    method: 'POST',
    path: 'boards/{board_no}/articles',
    requiredFields: ['board_no', 'title', 'content'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      title: { type: 'string', location: 'body' },
      content: { type: 'string', location: 'body' },
      writer_name: { type: 'string', location: 'body' },
      writer_email: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_update',
    label: '게시판 글 수정',
    description: 'Update a board article.',
    scopeType: 'write',
    method: 'PUT',
    path: 'boards/{board_no}/articles/{article_no}',
    requiredFields: ['board_no', 'article_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      title: { type: 'string', location: 'body' },
      content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_delete',
    label: '게시판 글 삭제',
    description: 'Delete a board article.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'boards/{board_no}/articles/{article_no}',
    requiredFields: ['board_no', 'article_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_comments_list',
    label: '게시판 댓글 목록',
    description: 'List comments on a board article.',
    scopeType: 'read',
    method: 'GET',
    path: 'boards/{board_no}/articles/{article_no}/comments',
    requiredFields: ['board_no', 'article_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'board_articles_comments_create',
    label: '게시판 댓글 작성',
    description: 'Create a comment on a board article.',
    scopeType: 'write',
    method: 'POST',
    path: 'boards/{board_no}/articles/{article_no}/comments',
    requiredFields: ['board_no', 'article_no', 'content'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      content: { type: 'string', location: 'body' },
      writer_name: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'board_articles_comments_delete',
    label: '게시판 댓글 삭제',
    description: 'Delete a comment on a board article.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'boards/{board_no}/articles/{article_no}/comments/{comment_no}',
    requiredFields: ['board_no', 'article_no', 'comment_no'],
    fields: {
      board_no: { type: 'number', location: 'path' },
      article_no: { type: 'number', location: 'path' },
      comment_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'commenttemplates_list',
    label: '자주 쓰는 답변 목록',
    description: 'List the frequently-used reply templates.',
    scopeType: 'read',
    method: 'GET',
    path: 'commenttemplates',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'commenttemplates_create',
    label: '자주 쓰는 답변 생성',
    description: 'Create a frequently-used reply template.',
    scopeType: 'write',
    method: 'POST',
    path: 'commenttemplates',
    requiredFields: ['template_name', 'template_content'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      template_name: { type: 'string', location: 'body' },
      template_content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
];
