import type { Cafe24OperationMetadata } from './types.js';

export const customerOperations: Cafe24OperationMetadata[] = [
  {
    id: 'customer_list',
    label: '회원 목록 조회',
    description:
      'List members (customers) with filters by group, signup date, etc.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      group_no: { type: 'number', location: 'query' },
      member_id: { type: 'string', location: 'query' },
      since: {
        type: 'string',
        location: 'query',
        description: 'ISO8601 — created_after',
      },
      until: { type: 'string', location: 'query' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'customer_get',
    label: '회원 단건 조회',
    description: 'Get a single customer by member_id.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_update',
    label: '회원 정보 수정',
    description: 'Update customer profile fields.',
    scopeType: 'write',
    method: 'PUT',
    path: 'customers/{member_id}',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      email: { type: 'string', location: 'body' },
      phone: { type: 'string', location: 'body' },
      sms: { type: 'enum', location: 'body', enum: ['T', 'F'] },
      news_mail: { type: 'enum', location: 'body', enum: ['T', 'F'] },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_group_update',
    label: '회원 등급 변경',
    description: 'Move a customer to a different group.',
    scopeType: 'write',
    method: 'PUT',
    path: 'customergroups/customers',
    requiredFields: ['member_id', 'group_no'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      member_id: { type: 'string', location: 'body' },
      group_no: { type: 'number', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_memos_create',
    label: '회원 메모 작성',
    description: 'Add a memo to a customer.',
    scopeType: 'write',
    method: 'POST',
    path: 'customers/{member_id}/memos',
    requiredFields: ['member_id', 'author', 'content'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      author: { type: 'string', location: 'body' },
      content: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_memos_count',
    label: '회원 메모 개수 조회',
    description:
      'Retrieve the count of memos attached to a customer. Sibling of `customer_memos_list`.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/memos/count',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_memos_list',
    label: '회원 메모 목록 조회',
    description: 'List the memos attached to a customer.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/memos',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'customer_memos_get',
    label: '회원 메모 단건 조회',
    description: 'Get a single customer memo by `memo_no`.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/memos/{memo_no}',
    requiredFields: ['member_id', 'memo_no'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      memo_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_memos_update',
    label: '회원 메모 수정',
    description:
      'Update an existing customer memo. `content` is required; other fields are optional.',
    scopeType: 'write',
    method: 'PUT',
    path: 'customers/{member_id}/memos/{memo_no}',
    requiredFields: ['member_id', 'memo_no', 'content'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      memo_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      content: { type: 'string', location: 'body' },
      memo_type: {
        type: 'string',
        location: 'body',
        description: 'Memo classification (e.g. general, warning)',
      },
      is_display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        description: 'Visibility flag (T=show, F=hidden)',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'customer_memos_delete',
    label: '회원 메모 삭제',
    description: 'Delete a customer memo by `memo_no`.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'customers/{member_id}/memos/{memo_no}',
    requiredFields: ['member_id', 'memo_no'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      memo_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
];
