import type { Cafe24OperationMetadata } from './types.js';

export const mileageOperations: Cafe24OperationMetadata[] = [
  {
    id: 'mileage_list',
    label: '적립금 내역 조회',
    description: 'List mileage (loyalty point) transactions.',
    scopeType: 'read',
    method: 'GET',
    path: 'points',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      member_id: { type: 'string', location: 'query' },
      start_date: { type: 'string', location: 'query' },
      end_date: { type: 'string', location: 'query' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'mileage_grant',
    label: '적립금 지급',
    description: 'Grant mileage to a member.',
    scopeType: 'write',
    method: 'POST',
    path: 'points',
    requiredFields: ['member_id', 'amount', 'reason'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      member_id: { type: 'string', location: 'body' },
      amount: {
        type: 'string',
        location: 'body',
        description: 'Positive decimal — grant amount',
      },
      reason: { type: 'string', location: 'body' },
      type: {
        type: 'enum',
        location: 'body',
        enum: ['increase', 'decrease'],
        default: 'increase',
      },
    },
    responseShape: 'single',
  },
  // Phase 6e — Mileage 보완
  {
    id: 'points_autoexpiration_get',
    label: '적립금 자동 만료 조회',
    description:
      'Retrieve an automatic points-expiration rule by id. Uses codebase `member_id` for the customer reference (Cafe24 docs vary by endpoint).',
    scopeType: 'read',
    method: 'GET',
    path: 'points/autoexpiration/{id}',
    requiredFields: ['id'],
    fields: {
      id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'points_autoexpiration_create',
    label: '적립금 자동 만료 생성',
    description:
      'Register an automatic points-expiration rule. Body should include customer reference + expiration_date + points_amount.',
    scopeType: 'write',
    method: 'POST',
    path: 'points/autoexpiration',
    requiredFields: ['member_id', 'expiration_date', 'points_amount'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      member_id: { type: 'string', location: 'body' },
      expiration_date: { type: 'string', location: 'body' },
      points_amount: {
        type: 'string',
        location: 'body',
        description: 'Decimal string — amount of points to expire',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'points_autoexpiration_delete',
    label: '적립금 자동 만료 삭제',
    description: 'Remove an automatic points-expiration rule by id.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'points/autoexpiration/{id}',
    requiredFields: ['id'],
    fields: {
      id: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'credits_list',
    label: '예치금 내역 조회',
    description: 'Retrieve the credit (예치금) ledger for a date range.',
    scopeType: 'read',
    method: 'GET',
    path: 'credits',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      start_date: { type: 'string', location: 'query' },
      end_date: { type: 'string', location: 'query' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'credits_report',
    label: '예치금 리포트 조회',
    description: 'Retrieve the credit (예치금) summary report for a date range.',
    scopeType: 'read',
    method: 'GET',
    path: 'credits/report',
    requiredFields: ['start_date', 'end_date'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      start_date: { type: 'string', location: 'query' },
      end_date: { type: 'string', location: 'query' },
    },
    responseShape: 'single',
  },
];
