import type { Cafe24OperationMetadata } from './types.js';

export const orderOperations: Cafe24OperationMetadata[] = [
  {
    id: 'order_list',
    label: '주문 목록 조회',
    description:
      'List orders with filters by date range, status, payment method, etc.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders',
    requiredFields: ['shop_no', 'start_date', 'end_date'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      start_date: {
        type: 'string',
        location: 'query',
        description: 'YYYY-MM-DD',
      },
      end_date: {
        type: 'string',
        location: 'query',
        description: 'YYYY-MM-DD',
      },
      date_type: {
        type: 'enum',
        location: 'query',
        enum: ['order_date', 'pay_date', 'ship_date'],
        default: 'order_date',
      },
      order_status: {
        type: 'string',
        location: 'query',
        description: 'Comma-separated order status codes (e.g. "N00,N10")',
      },
      payment_method: { type: 'string', location: 'query' },
      member_id: { type: 'string', location: 'query' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'order_get',
    label: '주문 단건 조회',
    description: 'Get a single order by order_id.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}',
    requiredFields: ['order_id'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'order_items_list',
    label: '주문 상품 목록 조회',
    description: 'List items in an order.',
    scopeType: 'read',
    method: 'GET',
    path: 'orders/{order_id}/items',
    requiredFields: ['order_id'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'order_shipments_create',
    label: '주문 배송 정보 등록',
    description: 'Register shipping info (carrier, tracking number) for order items.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/shipments',
    requiredFields: ['order_id', 'shipping_company_code', 'tracking_no'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      shipping_company_code: { type: 'string', location: 'body' },
      tracking_no: { type: 'string', location: 'body' },
      status: {
        type: 'enum',
        location: 'body',
        enum: ['standby', 'shipping', 'shipped'],
        default: 'shipped',
      },
      items: {
        type: 'array',
        location: 'body',
        description: 'Array of `{ order_item_code, ... }`',
      },
    },
    responseShape: 'single',
  },
  {
    id: 'order_buyer_update',
    label: '주문자 정보 수정',
    description: 'Update buyer information on an order.',
    scopeType: 'write',
    method: 'PUT',
    path: 'orders/{order_id}/buyer',
    requiredFields: ['order_id'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      name: { type: 'string', location: 'body' },
      phone: { type: 'string', location: 'body' },
      email: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'order_memos_create',
    label: '주문 메모 작성',
    description: 'Add a memo to an order.',
    scopeType: 'write',
    method: 'POST',
    path: 'orders/{order_id}/memos',
    requiredFields: ['order_id', 'author', 'content'],
    fields: {
      order_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      author: { type: 'string', location: 'body' },
      content: { type: 'string', location: 'body' },
      fixed: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'F',
      },
    },
    responseShape: 'single',
  },
];
