/**
 * Cafe24 Admin API — planned (yet-to-be-implemented) operations.
 *
 * SoT for these rows lives in `spec/conventions/cafe24-api-catalog/<resource>.md`
 * as `status: planned`. This file is the backend mirror that ships through
 * `GET /nodes/definitions` so the frontend Operation select can show
 * 'planned' items as disabled + '지원 예정' badge.
 *
 * Drift is caught by `catalog-sync.spec.ts` — adding/removing a planned row
 * in the catalog MD requires the same change here.
 */

import type { Cafe24Resource } from './types.js';

export interface Cafe24PlannedOperationEntry {
  id: string;
  label: string;
  paginated?: boolean;
}

export const CAFE24_PLANNED_BY_RESOURCE: Record<
  Cafe24Resource,
  readonly Cafe24PlannedOperationEntry[]
> = {
  store: [
    { id: 'shops_get', label: '멀티쇼핑몰 단건 조회' },
    { id: 'activitylogs_list', label: '액션 로그 목록', paginated: true },
    { id: 'activitylogs_get', label: '액션 로그 단건 조회' },
    { id: 'automessages_arguments_get', label: '자동 메시지 변수 목록' },
    { id: 'automessages_setting_get', label: '자동 메시지 설정 조회' },
    { id: 'automessages_setting_update', label: '자동 메시지 설정 수정' },
    { id: 'benefits_setting_get', label: '혜택 설정 조회' },
    { id: 'benefits_setting_update', label: '혜택 설정 수정' },
    { id: 'boards_setting_get', label: '게시판 설정 조회 (store)' },
    { id: 'boards_setting_update', label: '게시판 설정 수정 (store)' },
    { id: 'carts_setting_get', label: '장바구니 설정 조회' },
    { id: 'carts_setting_update', label: '장바구니 설정 수정' },
    { id: 'categories_properties_setting_get', label: '카테고리 진열 추가 설정 조회' },
    { id: 'categories_properties_setting_update', label: '카테고리 진열 추가 설정 수정' },
    { id: 'coupons_setting_get', label: '쿠폰 설정 조회' },
    { id: 'coupons_setting_update', label: '쿠폰 설정 수정' },
    { id: 'currency_get', label: '통화 설정 조회' },
    { id: 'currency_update', label: '통화 수정' },
    { id: 'customers_setting_get', label: '회원 관련 설정 조회' },
    { id: 'customers_setting_update', label: '회원 관련 설정 수정' },
    { id: 'dashboard_get', label: '대시보드 조회' },
    { id: 'financials_paymentgateway_get', label: '결제대행사 계약 정보 조회' },
    { id: 'financials_store_get', label: '상점 거래 정보 조회' },
    { id: 'images_setting_get', label: '상품 이미지 크기 설정 조회' },
    { id: 'images_setting_update', label: '상품 이미지 크기 설정 수정' },
    { id: 'information_get', label: '상점 정책 조회' },
    { id: 'information_update', label: '상점 정책 수정' },
    { id: 'kakaoalimtalk_profile_get', label: '카카오 채널 발신자 프로필 키 조회' },
    { id: 'kakaoalimtalk_setting_get', label: '카카오 알림톡 설정 조회' },
    { id: 'kakaoalimtalk_setting_update', label: '카카오 알림톡 설정 수정' },
    { id: 'kakaopay_setting_get', label: '카카오페이 주문 설정 조회' },
    { id: 'kakaopay_setting_update', label: '카카오페이 주문 설정 수정' },
    { id: 'mains_properties_setting_get', label: '메인 진열 추가 설정 조회' },
    { id: 'mains_properties_setting_update', label: '메인 진열 추가 설정 수정' },
    { id: 'menus_get', label: '메뉴 조회' },
    { id: 'mobile_setting_get', label: '모바일 설정 조회' },
    { id: 'mobile_setting_update', label: '모바일 설정 수정' },
    { id: 'naverpay_setting_get', label: '네이버페이 설정 조회' },
    { id: 'naverpay_setting_create', label: '네이버페이 설정 생성' },
    { id: 'naverpay_setting_update', label: '네이버페이 설정 수정' },
    { id: 'orderform_setting_get', label: '주문서 양식 설정 조회' },
    { id: 'orderform_setting_update', label: '주문서 양식 설정 수정' },
    { id: 'orders_setting_get', label: '주문 설정 조회' },
    { id: 'orders_setting_update', label: '주문 설정 수정' },
    { id: 'orders_status_get', label: '주문 상태 표기 조회' },
    { id: 'orders_status_update', label: '주문 상태 표기 수정' },
    { id: 'payment_setting_get', label: '결제 설정 조회' },
    { id: 'payment_setting_update', label: '결제 설정 수정' },
    { id: 'paymentgateway_create', label: '결제대행사 생성' },
    { id: 'paymentgateway_update', label: '결제대행사 수정' },
    { id: 'paymentgateway_delete', label: '결제대행사 삭제' },
    { id: 'paymentgateway_paymentmethods_list', label: '결제대행사 결제수단 목록' },
    { id: 'paymentgateway_paymentmethods_create', label: '결제대행사 결제수단 생성' },
    { id: 'paymentgateway_paymentmethods_update', label: '결제대행사 결제수단 수정' },
    { id: 'paymentgateway_paymentmethods_delete', label: '결제대행사 결제수단 삭제' },
    { id: 'paymentmethods_list', label: '결제수단 목록' },
    { id: 'paymentmethods_paymentproviders_list', label: '결제수단별 제공사 목록' },
    { id: 'paymentmethods_paymentproviders_update_display', label: '결제수단 노출 상태 수정' },
    { id: 'paymentservices_get', label: 'PG 설정 목록 조회' },
    { id: 'points_setting_get', label: '적립금 설정 조회' },
    { id: 'points_setting_update', label: '적립금 설정 수정' },
    { id: 'policy_get', label: '상점 프로필 조회' },
    { id: 'policy_update', label: '상점 프로필 수정' },
    { id: 'privacy_boards_get', label: '게시판 개인정보 정책 조회' },
    { id: 'privacy_boards_update', label: '게시판 개인정보 정책 수정' },
    { id: 'privacy_join_get', label: '회원가입 개인정보 정책 조회' },
    { id: 'privacy_join_update', label: '회원가입 개인정보 정책 수정' },
    { id: 'privacy_orders_get', label: '주문 개인정보 정책 조회' },
    { id: 'privacy_orders_update', label: '주문 개인정보 정책 수정' },
    { id: 'products_display_setting_list', label: '상품 진열 설정 목록' },
    { id: 'products_display_setting_update', label: '상품 진열 설정 수정' },
    { id: 'products_properties_setting_get', label: '상품 상세 추가 설정 조회' },
    { id: 'products_properties_setting_update', label: '상품 상세 추가 설정 수정' },
    { id: 'products_setting_get', label: '상품 설정 조회' },
    { id: 'redirects_list', label: '리다이렉트 목록', paginated: true },
    { id: 'redirects_create', label: '리다이렉트 생성' },
    { id: 'redirects_update', label: '리다이렉트 수정' },
    { id: 'redirects_delete', label: '리다이렉트 삭제' },
    { id: 'restocknotification_setting_get', label: '재입고 알림 설정 조회' },
    { id: 'restocknotification_setting_update', label: '재입고 알림 설정 수정' },
    { id: 'seo_setting_get', label: 'SEO 설정 조회' },
    { id: 'seo_setting_update', label: 'SEO 설정 수정' },
    { id: 'shippingmanager_get', label: '배송 매니저 활성화 정보' },
    { id: 'sms_setting_get', label: 'SMS 설정 조회' },
    { id: 'sms_setting_update', label: 'SMS 설정 수정' },
    { id: 'socials_apple_get', label: 'Apple 로그인 연동 상세' },
    { id: 'socials_apple_settings_get', label: 'Apple 로그인 연동 설정' },
    { id: 'socials_kakaosync_get', label: '카카오 싱크 상세' },
    { id: 'socials_kakaosync_update', label: '카카오 싱크 수정' },
    { id: 'socials_naverlogin_get', label: '네이버 로그인 상세' },
    { id: 'socials_naverlogin_update', label: '네이버 로그인 수정' },
    { id: 'socials_navershopping_get', label: '네이버 쇼핑 설정' },
    { id: 'store_accounts_list', label: '상점 계좌 목록' },
    { id: 'store_dropshipping_get', label: '위탁배송 설정 조회' },
    { id: 'store_dropshipping_manage', label: '위탁배송 설정 관리' },
    { id: 'store_setting_get', label: '상점 보안 설정 조회' },
    { id: 'store_setting_update', label: '상점 보안 설정 수정' },
    { id: 'subscription_shipments_setting_list', label: '정기배송 상품 목록', paginated: true },
    { id: 'subscription_shipments_setting_create_rule', label: '정기배송 결제 규칙 생성' },
    { id: 'subscription_shipments_setting_update', label: '정기배송 상품 수정' },
    { id: 'subscription_shipments_setting_delete', label: '정기배송 상품 삭제' },
    { id: 'taxmanager_get', label: '세금 매니저 활성화 정보' },
    { id: 'users_list', label: '운영자 사용자 목록', paginated: true },
    { id: 'users_get', label: '운영자 사용자 상세' },
  ],
  product: [
    { id: 'product_count', label: '상품 개수 조회' },
    { id: 'product_variants_get', label: '상품 품목 단건 조회' },
    { id: 'product_variants_update', label: '상품 품목 수정' },
    { id: 'product_variants_update_multiple', label: '상품 품목 일괄 수정' },
    { id: 'product_variants_delete', label: '상품 품목 삭제' },
    { id: 'product_variants_inventory_get', label: '상품 품목 재고 조회' },
    { id: 'product_options_list', label: '상품 옵션 목록 조회', paginated: true },
    { id: 'product_options_create', label: '상품 옵션 생성' },
    { id: 'product_options_update', label: '상품 옵션 수정' },
    { id: 'product_options_delete', label: '상품 옵션 삭제' },
    { id: 'product_additionalimages_create', label: '추가 이미지 등록' },
    { id: 'product_additionalimages_update', label: '추가 이미지 수정' },
    { id: 'product_additionalimages_delete', label: '추가 이미지 삭제' },
    { id: 'product_images_upload', label: '상품 이미지 업로드' },
    { id: 'product_images_delete', label: '상품 이미지 삭제' },
    { id: 'product_approve_get', label: '상품 승인 상태 조회' },
    { id: 'product_approve_create', label: '상품 승인 요청' },
    { id: 'product_approve_update', label: '상품 승인 상태 변경' },
    { id: 'product_customproperties_get', label: '상품 사용자 정의 속성 조회' },
    { id: 'product_customproperties_update', label: '상품 사용자 정의 속성 수정' },
    { id: 'product_customproperties_delete', label: '상품 사용자 정의 속성 삭제' },
    { id: 'product_decorationimages_list', label: '상품 꾸미기 이미지 목록', paginated: true },
    { id: 'product_decorationimages_set', label: '상품 꾸미기 이미지 설정' },
    { id: 'product_decorationimages_update', label: '상품 꾸미기 이미지 수정' },
    { id: 'product_decorationimages_delete', label: '상품 꾸미기 이미지 삭제' },
    { id: 'product_discountprice_get', label: '상품 할인가 조회' },
    { id: 'product_hits_count', label: '상품 조회수 카운트' },
    { id: 'product_icons_list', label: '상품 아이콘 목록', paginated: true },
    { id: 'product_icons_set', label: '상품 아이콘 설정' },
    { id: 'product_icons_update', label: '상품 아이콘 수정' },
    { id: 'product_icons_delete', label: '상품 아이콘 삭제' },
    { id: 'product_memos_list', label: '상품 메모 목록', paginated: true },
    { id: 'product_memos_get', label: '상품 메모 단건 조회' },
    { id: 'product_memos_create', label: '상품 메모 생성' },
    { id: 'product_memos_update', label: '상품 메모 수정' },
    { id: 'product_memos_delete', label: '상품 메모 삭제' },
    { id: 'product_seo_get', label: '상품 SEO 조회' },
    { id: 'product_seo_update', label: '상품 SEO 수정' },
    { id: 'product_tags_list', label: '상품 태그 목록', paginated: true },
    { id: 'product_tags_count', label: '상품 태그 개수' },
    { id: 'product_tags_create', label: '상품 태그 생성' },
    { id: 'product_tags_delete', label: '상품 태그 삭제' },
    { id: 'bundleproducts_list', label: '묶음 상품 목록', paginated: true },
    { id: 'bundleproducts_get', label: '묶음 상품 단건 조회' },
    { id: 'bundleproducts_create', label: '묶음 상품 생성' },
    { id: 'bundleproducts_update', label: '묶음 상품 수정' },
    { id: 'bundleproducts_delete', label: '묶음 상품 삭제' },
    { id: 'categories_products_count', label: '카테고리 내 상품 개수' },
    { id: 'categories_products_add', label: '카테고리에 상품 추가' },
    { id: 'categories_products_update', label: '카테고리 상품 수정' },
    { id: 'categories_products_delete', label: '카테고리 상품 삭제' },
    { id: 'mains_products_list', label: '메인 카테고리 상품 목록', paginated: true },
    { id: 'mains_products_count', label: '메인 카테고리 상품 개수' },
    { id: 'mains_products_set', label: '메인 카테고리 상품 설정' },
    { id: 'mains_products_update_sorting', label: '메인 카테고리 상품 정렬 수정' },
    { id: 'mains_products_delete', label: '메인 카테고리 상품 삭제' },
  ],
  order: [
    { id: 'order_count', label: '주문 개수 조회' },
    { id: 'order_status_update_multiple', label: '주문 상태 일괄 변경' },
    { id: 'order_status_update', label: '주문 상태 변경' },
    { id: 'order_autocalculation_delete', label: '주문 자동 계산 해제' },
    { id: 'order_buyer_get', label: '주문자 정보 조회' },
    { id: 'order_buyer_history_list', label: '주문자 정보 변경 이력' },
    { id: 'order_cancellation_create', label: '주문 취소 생성' },
    { id: 'order_cancellation_update', label: '주문 취소 상세 변경' },
    { id: 'order_completions_complete', label: 'PG 결제 후 주문 완료' },
    { id: 'order_exchange_create', label: '주문 교환 생성' },
    { id: 'order_exchange_update', label: '주문 교환 수정' },
    { id: 'order_exchangerequests_reject', label: '교환 요청 반려' },
    { id: 'order_items_create', label: '주문 상품 추가' },
    { id: 'order_items_update', label: '주문 상품 수정' },
    { id: 'order_items_labels_get', label: '주문 상품 라벨 조회' },
    { id: 'order_items_labels_create', label: '주문 상품 라벨 생성' },
    { id: 'order_items_labels_update', label: '주문 상품 라벨 수정' },
    { id: 'order_items_labels_delete', label: '주문 상품 라벨 삭제' },
    { id: 'order_items_options_create', label: '주문 상품 옵션 생성' },
    { id: 'order_items_options_update', label: '주문 상품 옵션 수정' },
    { id: 'order_memos_list', label: '주문 메모 목록' },
    { id: 'order_memos_update', label: '주문 메모 수정' },
    { id: 'order_memos_delete', label: '주문 메모 삭제' },
    { id: 'order_payments_status_update', label: '주문 결제 상태 수정' },
    { id: 'order_paymenttimeline_history', label: '결제 이력 조회' },
    { id: 'order_paymenttimeline_details', label: '결제 상세 조회' },
    { id: 'order_receivers_list', label: '받는 사람 목록' },
    { id: 'order_receivers_update', label: '받는 사람 수정' },
    { id: 'order_receivers_change_shipping', label: '받는 사람 배송지 변경' },
    { id: 'order_receivers_history_list', label: '받는 사람 변경 이력' },
    { id: 'order_refunds_update', label: '주문 환불 수정' },
    { id: 'order_return_create', label: '주문 반품 생성' },
    { id: 'order_return_update', label: '주문 반품 수정' },
    { id: 'order_shipments_list', label: '주문 배송 정보 목록' },
    { id: 'order_shipments_update', label: '주문 배송 정보 수정' },
    { id: 'order_shipments_delete', label: '주문 배송 정보 삭제' },
    { id: 'order_shippingfeecancellation_get', label: '배송비 취소 상세' },
    { id: 'order_shippingfeecancellation_create', label: '배송비 취소 생성' },
    { id: 'order_shortagecancellation_create', label: '재고 부족 취소 생성' },
    { id: 'orders_benefits_list', label: '주문 혜택 목록' },
    { id: 'orders_calculation_total', label: '주문 결제 금액 계산' },
    { id: 'orders_coupons_list', label: '주문 쿠폰 목록' },
    { id: 'orders_dashboard_list', label: '주문 대시보드' },
    { id: 'orders_inflowgroups_list', label: '유입 그룹 목록', paginated: true },
    { id: 'orders_inflowgroups_create', label: '유입 그룹 생성' },
    { id: 'orders_inflowgroups_update', label: '유입 그룹 수정' },
    { id: 'orders_inflowgroups_delete', label: '유입 그룹 삭제' },
    { id: 'orders_inflows_list', label: '유입 출처 목록', paginated: true },
    { id: 'orders_inflows_create', label: '유입 출처 생성' },
    { id: 'orders_inflows_update', label: '유입 출처 수정' },
    { id: 'orders_inflows_delete', label: '유입 출처 삭제' },
    { id: 'orders_memos_list', label: '관리자 메모 목록' },
    { id: 'orders_migrations_get', label: '이관 주문 조회' },
    { id: 'orders_migrations_create', label: '이관 주문 생성' },
    { id: 'orders_migrations_update', label: '이관 주문 수정' },
    { id: 'orders_migrations_delete', label: '이관 주문 삭제' },
    { id: 'orders_paymentamount_get', label: '결제 금액 조회' },
    { id: 'orders_saleschannels_list', label: '판매 채널 목록', paginated: true },
    { id: 'orders_saleschannels_create', label: '판매 채널 생성' },
    { id: 'orders_saleschannels_update', label: '판매 채널 수정' },
    { id: 'orders_saleschannels_delete', label: '판매 채널 삭제' },
    { id: 'payments_status_update_multiple', label: '결제 상태 일괄 변경' },
    { id: 'refunds_list', label: '환불 목록', paginated: true },
    { id: 'refunds_get', label: '환불 단건 조회' },
    { id: 'reservations_get', label: '예약 상품 조회' },
    { id: 'return_get', label: '반품 조회' },
    { id: 'return_create_multiple', label: '반품 일괄 생성' },
    { id: 'return_update', label: '반품 수정' },
    { id: 'returnrequests_create', label: '반품 요청 생성' },
    { id: 'returnrequests_reject', label: '반품 요청 거부' },
    { id: 'cancellation_get', label: '취소 조회' },
    { id: 'cancellation_create_multiple', label: '취소 일괄 생성' },
    { id: 'cancellation_update_bulk', label: '취소 상세 일괄 변경' },
    { id: 'cancellationrequests_create', label: '취소 요청 생성' },
    { id: 'cancellationrequests_reject', label: '취소 요청 거부' },
    { id: 'cashreceipt_list', label: '현금영수증 목록', paginated: true },
    { id: 'cashreceipt_create', label: '현금영수증 발행' },
    { id: 'cashreceipt_update', label: '현금영수증 수정' },
    { id: 'cashreceipt_cancel', label: '현금영수증 취소' },
    { id: 'collectrequests_update', label: '수거 요청 수정' },
    { id: 'control', label: '주문 컨트롤' },
    { id: 'exchange_get', label: '교환 조회' },
    { id: 'exchange_create_multiple', label: '교환 일괄 생성' },
    { id: 'exchange_update_multiple', label: '교환 일괄 수정' },
    { id: 'exchangerequests_create_bulk', label: '교환 요청 일괄 생성' },
    { id: 'exchangerequests_reject_multiple', label: '교환 요청 일괄 거부' },
    { id: 'fulfillments_create', label: '풀필먼트 배송 생성' },
    { id: 'labels_list', label: '주문 라벨 목록' },
    { id: 'labels_create_multiple', label: '주문 라벨 일괄 생성' },
    { id: 'orderform_properties_get', label: '주문서 추가 필드 조회' },
    { id: 'orderform_properties_create', label: '주문서 추가 필드 생성' },
    { id: 'orderform_properties_update', label: '주문서 추가 필드 수정' },
    { id: 'orderform_properties_delete', label: '주문서 추가 필드 삭제' },
    { id: 'shipments_create_multiple', label: '배송 일괄 생성' },
    { id: 'shipments_update_multiple', label: '배송 일괄 수정' },
    { id: 'subscription_shipments_get', label: '정기배송 조회' },
    { id: 'subscription_shipments_create', label: '정기배송 생성' },
    { id: 'subscription_shipments_update', label: '정기배송 수정' },
    { id: 'subscription_shipments_items_update', label: '정기배송 상품 옵션 수정' },
    { id: 'unpaidorders_list', label: '미결제 주문 목록', paginated: true },
  ],
  customer: [
    { id: 'customer_delete', label: '회원 탈퇴 처리' },
    { id: 'customer_autoupdate_get', label: '회원 등급 자동 갱신 조회' },
    { id: 'customer_memos_count', label: '회원 메모 개수' },
    { id: 'customer_memos_list', label: '회원 메모 목록', paginated: true },
    { id: 'customer_memos_get', label: '회원 메모 단건 조회' },
    { id: 'customer_memos_update', label: '회원 메모 수정' },
    { id: 'customer_memos_delete', label: '회원 메모 삭제' },
    { id: 'customer_paymentinfo_list', label: '회원 결제수단 목록' },
    { id: 'customer_paymentinfo_delete', label: '회원 결제수단 삭제' },
    { id: 'customer_paymentinfo_delete_by_id', label: '회원 결제수단 ID 삭제' },
    { id: 'customer_plusapp_get', label: 'Plus 앱 설치 정보 조회' },
    { id: 'customer_social_get', label: '소셜 계정 조회' },
    { id: 'customers_properties_view', label: '회원가입 필드 조회' },
    { id: 'customers_properties_edit', label: '회원가입 필드 수정' },
    { id: 'social_list', label: '소셜 연동 목록' },
    { id: 'customergroups_list', label: '회원 등급 목록', paginated: true },
    { id: 'customergroups_count', label: '회원 등급 개수' },
    { id: 'customergroups_get', label: '회원 등급 단건 조회' },
    { id: 'customergroups_settings_get', label: '회원 등급 설정 조회' },
  ],
  community: [
    { id: 'boards_settings_get', label: '게시판 설정 조회' },
    { id: 'boards_settings_update', label: '게시판 설정 수정' },
    { id: 'board_articles_create', label: '게시판 글 작성' },
    { id: 'board_articles_update', label: '게시판 글 수정' },
    { id: 'board_articles_delete', label: '게시판 글 삭제' },
    { id: 'board_articles_comments_list', label: '게시판 댓글 목록', paginated: true },
    { id: 'board_articles_comments_create', label: '게시판 댓글 작성' },
    { id: 'board_articles_comments_delete', label: '게시판 댓글 삭제' },
    { id: 'boards_comments_bulk', label: '게시판 댓글 일괄 조회' },
    { id: 'boards_seo_get', label: '게시판 SEO 조회' },
    { id: 'boards_seo_update', label: '게시판 SEO 수정' },
    { id: 'commenttemplates_list', label: '자주 쓰는 답변 목록', paginated: true },
    { id: 'commenttemplates_get', label: '자주 쓰는 답변 단건' },
    { id: 'commenttemplates_create', label: '자주 쓰는 답변 생성' },
    { id: 'commenttemplates_update', label: '자주 쓰는 답변 수정' },
    { id: 'commenttemplates_delete', label: '자주 쓰는 답변 삭제' },
    { id: 'financials_monthlyreviews_count', label: '월별 후기 카운트' },
    { id: 'urgentinquiry_get', label: '긴급 문의 게시글 조회' },
    { id: 'urgentinquiry_reply_get', label: '긴급 문의 답변 조회' },
    { id: 'urgentinquiry_reply_create', label: '긴급 문의 답변 작성' },
    { id: 'urgentinquiry_reply_update', label: '긴급 문의 답변 수정' },
  ],
  design: [
    { id: 'themes_count', label: '테마 개수 조회' },
    { id: 'themes_get', label: '테마 단건 조회' },
    { id: 'theme_pages_get', label: '테마 페이지 조회' },
    { id: 'theme_pages_create', label: '테마 페이지 생성' },
    { id: 'theme_pages_update', label: '테마 페이지 수정' },
    { id: 'theme_pages_delete', label: '테마 페이지 삭제' },
    { id: 'icons_list', label: '디자인 아이콘 목록 조회' },
    { id: 'icons_update_settings', label: '상점 아이콘 설정 수정' },
  ],
  promotion: [
    { id: 'coupon_count', label: '쿠폰 개수 조회' },
    { id: 'coupon_manage', label: '쿠폰 관리 (사용/중지)' },
    { id: 'coupon_issuance_customers_list', label: '쿠폰 발급 대상 회원 목록', paginated: true },
    { id: 'coupon_issues_list', label: '발급 쿠폰 목록', paginated: true },
    { id: 'benefits_list', label: '회원 혜택 목록', paginated: true },
    { id: 'benefits_count', label: '회원 혜택 개수' },
    { id: 'benefits_get', label: '회원 혜택 단건 조회' },
    { id: 'benefits_create', label: '회원 혜택 생성' },
    { id: 'benefits_update', label: '회원 혜택 수정' },
    { id: 'benefits_delete', label: '회원 혜택 삭제' },
    { id: 'commonevents_list', label: '전체 이벤트 목록', paginated: true },
    { id: 'commonevents_create', label: '전체 이벤트 생성' },
    { id: 'commonevents_update', label: '전체 이벤트 수정' },
    { id: 'commonevents_delete', label: '전체 이벤트 삭제' },
    { id: 'customerevents_get', label: '회원 정보 이벤트 조회' },
    { id: 'customerevents_create', label: '회원 정보 이벤트 생성' },
    { id: 'customerevents_update_status', label: '회원 정보 이벤트 상태 수정' },
    { id: 'customers_coupons_list', label: '회원별 쿠폰 목록', paginated: true },
    { id: 'customers_coupons_count', label: '회원별 쿠폰 개수' },
    { id: 'customers_coupons_delete', label: '회원 쿠폰 삭제' },
    { id: 'discountcodes_list', label: '할인 코드 목록', paginated: true },
    { id: 'discountcodes_get', label: '할인 코드 단건 조회' },
    { id: 'discountcodes_create', label: '할인 코드 생성' },
    { id: 'discountcodes_update', label: '할인 코드 수정' },
    { id: 'discountcodes_delete', label: '할인 코드 삭제' },
    { id: 'serialcoupons_list', label: '시리얼 쿠폰 코드 조회', paginated: true },
    { id: 'serialcoupons_generate', label: '시리얼 쿠폰 코드 생성' },
    { id: 'serialcoupons_delete', label: '시리얼 쿠폰 코드 삭제' },
    { id: 'serialcoupons_issues_get', label: '시리얼 쿠폰 발급 코드 조회' },
    { id: 'serialcoupons_issues_register', label: '시리얼 쿠폰 발급 코드 등록' },
  ],
  application: [
    { id: 'apps_update', label: '앱 정보 수정' },
    { id: 'appstore_orders_get', label: '앱스토어 주문 조회' },
    { id: 'appstore_orders_create', label: '앱스토어 주문 생성' },
    { id: 'appstore_payments_list', label: '앱스토어 결제 목록', paginated: true },
    { id: 'appstore_payments_count', label: '앱스토어 결제 수' },
    { id: 'databridge_logs_list', label: 'DataBridge 로그 목록', paginated: true },
    { id: 'recipes_list', label: '레시피 목록 조회', paginated: true },
    { id: 'recipes_create', label: '레시피 생성' },
    { id: 'recipes_delete', label: '레시피 삭제' },
    { id: 'scripttags_count', label: '스크립트태그 개수 조회' },
    { id: 'scripttags_get', label: '스크립트태그 단건 조회' },
    { id: 'scripttags_create', label: '스크립트태그 생성' },
    { id: 'scripttags_update', label: '스크립트태그 수정' },
    { id: 'scripttags_delete', label: '스크립트태그 삭제' },
    { id: 'webhooks_logs_list', label: 'Webhook 로그 목록', paginated: true },
    { id: 'webhooks_update', label: 'Webhook 설정 수정' },
  ],
  category: [
    { id: 'category_count', label: '카테고리 개수 조회' },
    { id: 'category_decorationimages_get', label: '카테고리 꾸미기 이미지 조회' },
    { id: 'category_decorationimages_update', label: '카테고리 꾸미기 이미지 수정' },
    { id: 'category_seo_get', label: '카테고리 SEO 조회' },
    { id: 'category_seo_update', label: '카테고리 SEO 수정' },
    { id: 'mains_list', label: '메인 카테고리 목록 조회', paginated: true },
    { id: 'mains_add', label: '메인 카테고리 추가' },
    { id: 'mains_update', label: '메인 카테고리 수정' },
    { id: 'mains_delete', label: '메인 카테고리 삭제' },
    { id: 'autodisplay_list', label: '자동 진열 목록 조회', paginated: true },
    { id: 'autodisplay_create', label: '자동 진열 생성' },
    { id: 'autodisplay_update', label: '자동 진열 수정' },
    { id: 'autodisplay_delete', label: '자동 진열 삭제' },
  ],
  collection: [
    { id: 'brands_count', label: '브랜드 개수 조회' },
    { id: 'brands_create', label: '브랜드 생성' },
    { id: 'brands_update', label: '브랜드 수정' },
    { id: 'brands_delete', label: '브랜드 삭제' },
    { id: 'manufacturers_count', label: '제조사 개수 조회' },
    { id: 'manufacturers_get', label: '제조사 단건 조회' },
    { id: 'manufacturers_create', label: '제조사 생성' },
    { id: 'manufacturers_update', label: '제조사 수정' },
    { id: 'trends_count', label: '트렌드 개수 조회' },
    { id: 'classifications_list', label: '사용자 정의 카테고리 목록', paginated: true },
    { id: 'classifications_count', label: '사용자 정의 카테고리 수' },
    { id: 'origin_list', label: '원산지 목록 조회', paginated: true },
  ],
  supply: [
    { id: 'suppliers_count', label: '공급사 개수 조회' },
    { id: 'suppliers_get', label: '공급사 단건 조회' },
    { id: 'suppliers_create', label: '공급사 등록' },
    { id: 'suppliers_update', label: '공급사 수정' },
    { id: 'suppliers_delete', label: '공급사 삭제' },
    { id: 'suppliers_users_list', label: '공급사 사용자 목록', paginated: true },
    { id: 'suppliers_users_count', label: '공급사 사용자 수' },
    { id: 'suppliers_users_get', label: '공급사 사용자 단건 조회' },
    { id: 'suppliers_users_create', label: '공급사 사용자 등록' },
    { id: 'suppliers_users_update', label: '공급사 사용자 수정' },
    { id: 'suppliers_users_delete', label: '공급사 사용자 삭제' },
    { id: 'suppliers_users_regional_list', label: '사용자 지역별 배송비 목록' },
    { id: 'suppliers_users_regional_create', label: '사용자 지역별 배송비 등록' },
    { id: 'suppliers_users_regional_delete', label: '사용자 지역별 배송비 삭제' },
    { id: 'suppliers_users_regional_settings_get', label: '지역별 배송비 설정 조회' },
    { id: 'suppliers_users_regional_settings_update', label: '지역별 배송비 설정 수정' },
    { id: 'shipping_suppliers_get', label: '공급사 배송 설정 조회' },
    { id: 'shipping_suppliers_update', label: '공급사 배송 설정 수정' },
    { id: 'shipping_suppliers_additionalfees_get', label: '공급사 국제 배송 추가비 조회' },
  ],
  shipping: [
    { id: 'carriers_get', label: '배송사 단건 조회' },
    { id: 'carriers_create', label: '배송사 등록' },
    { id: 'carriers_update', label: '배송사 수정' },
    { id: 'carriers_delete', label: '배송사 삭제' },
    { id: 'regionalsurcharges_get', label: '지역별 배송비 조회' },
    { id: 'regionalsurcharges_update', label: '지역별 배송비 수정' },
    { id: 'shipping_settings_get', label: '배송·반품 설정 조회' },
    { id: 'shipping_settings_update', label: '배송·반품 설정 수정' },
    { id: 'shipping_additionalfees_countries', label: '국제 배송 추가비 국가 목록' },
    { id: 'shippingorigins_list', label: '출고지 목록 조회', paginated: true },
    { id: 'shippingorigins_get', label: '출고지 단건 조회' },
    { id: 'shippingorigins_create', label: '출고지 등록' },
    { id: 'shippingorigins_update', label: '출고지 수정' },
    { id: 'shippingorigins_delete', label: '출고지 삭제' },
  ],
  salesreport: [
    { id: 'salesreport_monthly', label: '월별 매출 통계' },
    { id: 'salesreport_hourly', label: '시간대별 매출 통계' },
    { id: 'salesreport_volume', label: '매출 리포트 조회' },
  ],
  personal: [
    { id: 'customers_wishlist_count', label: '위시리스트 상품 개수' },
    { id: 'products_carts_count', label: '상품 담은 장바구니 수' },
    { id: 'products_carts_list', label: '상품 담은 장바구니 목록', paginated: true },
  ],
  privacy: [
    { id: 'customers_privacy_list', label: '회원 개인정보 목록 조회', paginated: true },
    { id: 'customers_privacy_count', label: '회원 개인정보 개수 조회' },
    { id: 'customers_privacy_update', label: '회원 개인정보 수정' },
    { id: 'products_wishlist_customers_list', label: '위시리스트 보유 회원 목록', paginated: true },
    { id: 'products_wishlist_customers_count', label: '위시리스트 보유 회원 수' },
  ],
  mileage: [
    { id: 'points_autoexpiration_get', label: '적립금 자동 만료 조회' },
    { id: 'points_autoexpiration_create', label: '적립금 자동 만료 생성' },
    { id: 'points_autoexpiration_delete', label: '적립금 자동 만료 삭제' },
    { id: 'points_report', label: '적립금 리포트 조회' },
    { id: 'credits_list', label: '예치금 내역 조회', paginated: true },
    { id: 'credits_report', label: '예치금 리포트 조회' },
  ],
  notification: [
    { id: 'sms_receivers_get', label: 'SMS 수신자 조회' },
    { id: 'sms_senders_list', label: 'SMS 발신자 목록 조회' },
    { id: 'automails_get', label: '자동 이메일 설정 조회' },
    { id: 'automails_update', label: '자동 이메일 설정 수정' },
    { id: 'customers_invitation_send', label: '회원 활성화 초대 발송' },
    { id: 'recipientgroups_list', label: '수신자 그룹 목록', paginated: true },
    { id: 'recipientgroups_get', label: '수신자 그룹 상세' },
    { id: 'recipientgroups_create', label: '수신자 그룹 생성' },
    { id: 'recipientgroups_update', label: '수신자 그룹 수정' },
    { id: 'recipientgroups_delete', label: '수신자 그룹 삭제' },
  ],
  translation: [
    { id: 'translation_products_update', label: '상품 번역 수정' },
    { id: 'translation_categories_list', label: '카테고리 번역 목록 조회', paginated: true },
    { id: 'translation_categories_update', label: '카테고리 번역 수정' },
    { id: 'translation_store_list', label: '상점 번역 목록 조회', paginated: true },
    { id: 'translation_store_update', label: '상점 번역 수정' },
    { id: 'translation_themes_list', label: '테마 번역 목록 조회', paginated: true },
    { id: 'translation_themes_get', label: '테마 번역 단건 조회' },
    { id: 'translation_themes_update', label: '테마 번역 수정' },
  ],
};
