import type { Cafe24OperationMetadata } from './types.js';

export const productOperations: Cafe24OperationMetadata[] = [
  {
    id: 'product_list',
    label: '상품 목록 조회',
    description:
      'List products in the mall. Supports filtering by category, display status, date range, price range.',
    scopeType: 'read',
    method: 'GET',
    path: 'products',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: {
        type: 'number',
        location: 'query',
        description: 'Multi-shop number (default 1)',
        default: 1,
      },
      category_no: {
        type: 'number',
        location: 'query',
        description: 'Filter by category number',
      },
      display: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Display on/off (T=on, F=off)',
      },
      selling: {
        type: 'enum',
        location: 'query',
        enum: ['T', 'F'],
        description: 'Selling on/off',
      },
      since: {
        type: 'string',
        location: 'query',
        description: 'ISO8601 date — created_after',
      },
      until: {
        type: 'string',
        location: 'query',
        description: 'ISO8601 date — created_before',
      },
      product_name: {
        type: 'string',
        location: 'query',
        description: 'Filter by product name (partial match)',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'product_get',
    label: '상품 단건 조회',
    description: 'Get a single product by product_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'product_create',
    label: '상품 생성',
    description:
      'Create a new product. Required fields vary by mall settings; refer to Cafe24 docs for the full field list.',
    scopeType: 'write',
    method: 'POST',
    path: 'products',
    requiredFields: ['product_name', 'price', 'supply_price'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      product_name: { type: 'string', location: 'body' },
      price: {
        type: 'string',
        location: 'body',
        description: 'Decimal string (KRW)',
      },
      supply_price: { type: 'string', location: 'body' },
      display: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'T',
      },
      selling: {
        type: 'enum',
        location: 'body',
        enum: ['T', 'F'],
        default: 'T',
      },
      description: { type: 'string', location: 'body' },
      category_no: { type: 'array', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_update',
    label: '상품 수정',
    description:
      'Update a product (name, price, display, selling, description, ...).',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      product_name: { type: 'string', location: 'body' },
      price: { type: 'string', location: 'body' },
      display: { type: 'enum', location: 'body', enum: ['T', 'F'] },
      selling: { type: 'enum', location: 'body', enum: ['T', 'F'] },
      description: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_delete',
    label: '상품 삭제',
    description: 'Delete a product by product_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'products/{product_no}',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'product_variants_list',
    label: '상품 품목(옵션) 목록 조회',
    description: 'List variants (option combinations) for a product.',
    scopeType: 'read',
    method: 'GET',
    path: 'products/{product_no}/variants',
    requiredFields: ['product_no'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'product_variants_inventory_update',
    label: '상품 품목 재고 수정',
    description: 'Update inventory quantity for a specific variant.',
    scopeType: 'write',
    method: 'PUT',
    path: 'products/{product_no}/variants/{variant_code}/inventories',
    requiredFields: ['product_no', 'variant_code', 'quantity'],
    fields: {
      product_no: { type: 'number', location: 'path' },
      variant_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      quantity: { type: 'number', location: 'body' },
      use_inventory: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'B', 'C'],
        description: 'Inventory control mode',
      },
    },
    responseShape: 'single',
  },
];
