import type { Cafe24OperationMetadata } from './types.js';

export const promotionOperations: Cafe24OperationMetadata[] = [
  {
    id: 'coupon_list',
    label: '쿠폰 목록 조회',
    description: 'List coupons available in the mall.',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons',
    requiredFields: ['shop_no'],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      coupon_type: { type: 'string', location: 'query' },
      issue_type: {
        type: 'enum',
        location: 'query',
        enum: ['M', 'D', 'O', 'A', 'R'],
        description:
          'M=manual, D=download, O=auto-give, A=action, R=re-engagement',
      },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'coupon_get',
    label: '쿠폰 단건 조회',
    description: 'Get a single coupon by coupon_no.',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons/{coupon_no}',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'coupon_create',
    label: '쿠폰 생성',
    description: 'Create a new coupon.',
    scopeType: 'write',
    method: 'POST',
    path: 'coupons',
    requiredFields: ['coupon_name', 'benefit_type', 'benefit_amount'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      coupon_name: { type: 'string', location: 'body' },
      benefit_type: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'B', 'C', 'D'],
        description: 'A=discount price, B=discount %, C=shipping, D=points',
      },
      benefit_amount: { type: 'string', location: 'body' },
      issue_type: {
        type: 'enum',
        location: 'body',
        enum: ['M', 'D', 'O', 'A', 'R'],
      },
      issued_count: { type: 'number', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'coupon_issue',
    label: '쿠폰 발급',
    description: 'Issue a coupon to specified members.',
    scopeType: 'write',
    method: 'POST',
    path: 'coupons/{coupon_no}/issues',
    requiredFields: ['coupon_no', 'issued_member_scope'],
    fields: {
      coupon_no: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      issued_member_scope: {
        type: 'enum',
        location: 'body',
        enum: ['A', 'M', 'G'],
        description: 'A=all, M=specific members, G=group',
      },
      member_ids: { type: 'array', location: 'body' },
      group_no: { type: 'number', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'coupon_delete',
    label: '쿠폰 삭제',
    description: 'Delete a coupon by coupon_no.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'coupons/{coupon_no}',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'coupon_count',
    label: '쿠폰 개수 조회',
    description:
      'Retrieve the total count of coupons. Sibling of coupon_list (paginated).',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'coupon_issues_list',
    label: '발급 쿠폰 목록 조회',
    description:
      'List the issuance records of a coupon (who received it, when).',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons/issues',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'number', location: 'query' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'coupon_issuance_customers_list',
    label: '쿠폰 발급 대상 회원 목록',
    description:
      'List customers eligible for conditional issuance of a coupon.',
    scopeType: 'read',
    method: 'GET',
    path: 'coupons/{coupon_no}/issuancecustomers',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'customers_coupons_list',
    label: '회원별 쿠폰 목록',
    description:
      "List the coupons a customer holds. Uses the codebase-wide `member_id` path placeholder (Cafe24 docs call this `customer_no`).",
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/coupons',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'customers_coupons_count',
    label: '회원별 쿠폰 개수',
    description: 'Retrieve the count of coupons a customer holds.',
    scopeType: 'read',
    method: 'GET',
    path: 'customers/{member_id}/coupons/count',
    requiredFields: ['member_id'],
    fields: {
      member_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'serialcoupons_list',
    label: '시리얼 쿠폰 코드 조회',
    description:
      'Retrieve the generated serial coupon codes for a coupon (paginated by limit/offset).',
    scopeType: 'read',
    method: 'GET',
    path: 'serialcoupons',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'number', location: 'query' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'serialcoupons_generate',
    label: '시리얼 쿠폰 코드 생성',
    description:
      'Generate a batch of serial coupon codes. `quantity` is required; optional prefix/suffix decorate the generated codes.',
    scopeType: 'write',
    method: 'POST',
    path: 'serialcoupons/{coupon_no}/generate',
    requiredFields: ['coupon_no', 'quantity'],
    fields: {
      coupon_no: { type: 'number', location: 'path' },
      quantity: { type: 'number', location: 'body' },
      prefix: { type: 'string', location: 'body' },
      suffix: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'serialcoupons_delete',
    label: '시리얼 쿠폰 코드 삭제',
    description: 'Delete a specific serial coupon code by code value.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'serialcoupons/{coupon_no}/{code}',
    requiredFields: ['coupon_no', 'code'],
    fields: {
      coupon_no: { type: 'number', location: 'path' },
      code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'serialcoupons_issues_get',
    label: '시리얼 쿠폰 발급 코드 조회',
    description: 'List the issued/used codes for a serial coupon.',
    scopeType: 'read',
    method: 'GET',
    path: 'serialcoupons/{coupon_no}/issues',
    requiredFields: ['coupon_no'],
    fields: {
      coupon_no: { type: 'number', location: 'path' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'serialcoupons_issues_register',
    label: '시리얼 쿠폰 발급 코드 등록',
    description: 'Register a specific code into the serial coupon issued set.',
    scopeType: 'write',
    method: 'POST',
    path: 'serialcoupons/{coupon_no}/issues',
    requiredFields: ['coupon_no', 'code'],
    fields: {
      coupon_no: { type: 'number', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      code: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
];
