import type { Cafe24OperationMetadata } from './types.js';

export const supplyOperations: Cafe24OperationMetadata[] = [
  {
    id: 'suppliers_list',
    label: '공급사 목록 조회',
    description: 'List suppliers.',
    scopeType: 'read',
    method: 'GET',
    path: 'suppliers',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
    paginated: true,
  },
  // Phase 6d — supply baselines
  {
    id: 'suppliers_count',
    label: '공급사 개수 조회',
    description: 'Retrieve the count of suppliers.',
    scopeType: 'read',
    method: 'GET',
    path: 'suppliers/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'suppliers_get',
    label: '공급사 단건 조회',
    description: 'Retrieve a single supplier by supplier_code.',
    scopeType: 'read',
    method: 'GET',
    path: 'suppliers/{supplier_code}',
    requiredFields: ['supplier_code'],
    fields: {
      supplier_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  // Phase 7g — Supply 완성 (suppliers CUD + suppliers_users CRUD + regional shipping + shipping_suppliers)
  {
    id: 'suppliers_create',
    label: '공급사 등록',
    description: 'Register a new supplier. Body schema partial — refer to Cafe24 docs for full schema.',
    scopeType: 'write',
    method: 'POST',
    path: 'suppliers',
    requiredFields: ['supplier_name'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      supplier_name: { type: 'string', location: 'body' },
      use_supplier: { type: 'enum', location: 'body', enum: ['T', 'F'], default: 'T' },
    },
    responseShape: 'single',
  },
  {
    id: 'suppliers_update',
    label: '공급사 수정',
    description: 'Update an existing supplier (partial). Refer to Cafe24 docs for full schema.',
    scopeType: 'write',
    method: 'PUT',
    path: 'suppliers/{supplier_code}',
    requiredFields: ['supplier_code'],
    fields: {
      supplier_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      supplier_name: { type: 'string', location: 'body' },
      use_supplier: { type: 'enum', location: 'body', enum: ['T', 'F'] },
    },
    responseShape: 'single',
  },
  {
    id: 'suppliers_delete',
    label: '공급사 삭제',
    description: 'Delete a supplier by supplier_code.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'suppliers/{supplier_code}',
    requiredFields: ['supplier_code'],
    fields: {
      supplier_code: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'suppliers_users_list',
    label: '공급사 사용자 목록',
    description: 'List supplier user accounts.',
    scopeType: 'read',
    method: 'GET',
    path: 'suppliers/users',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      supplier_code: { type: 'string', location: 'query' },
    },
    responseShape: 'list',
    paginated: true,
  },
  {
    id: 'suppliers_users_count',
    label: '공급사 사용자 수',
    description: 'Retrieve the count of supplier user accounts.',
    scopeType: 'read',
    method: 'GET',
    path: 'suppliers/users/count',
    requiredFields: [],
    fields: {
      shop_no: { type: 'number', location: 'query', default: 1 },
      supplier_code: { type: 'string', location: 'query' },
    },
    responseShape: 'single',
  },
  {
    id: 'suppliers_users_get',
    label: '공급사 사용자 단건 조회',
    description: 'Retrieve supplier user details by user_id.',
    scopeType: 'read',
    method: 'GET',
    path: 'suppliers/users/{user_id}',
    requiredFields: ['user_id'],
    fields: {
      user_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'suppliers_users_create',
    label: '공급사 사용자 등록',
    description: 'Create a supplier user account. Body schema partial — refer to Cafe24 docs.',
    scopeType: 'write',
    method: 'POST',
    path: 'suppliers/users',
    requiredFields: ['supplier_code', 'user_id'],
    fields: {
      shop_no: { type: 'number', location: 'body', default: 1 },
      supplier_code: { type: 'string', location: 'body' },
      user_id: { type: 'string', location: 'body' },
      user_name: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'suppliers_users_update',
    label: '공급사 사용자 수정',
    description: 'Update supplier user details (partial).',
    scopeType: 'write',
    method: 'PUT',
    path: 'suppliers/users/{user_id}',
    requiredFields: ['user_id'],
    fields: {
      user_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
      user_name: { type: 'string', location: 'body' },
    },
    responseShape: 'single',
  },
  {
    id: 'suppliers_users_delete',
    label: '공급사 사용자 삭제',
    description: 'Delete a supplier user by user_id.',
    scopeType: 'write',
    method: 'DELETE',
    path: 'suppliers/users/{user_id}',
    requiredFields: ['user_id'],
    fields: {
      user_id: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'suppliers_users_regional_list',
    label: '사용자 지역별 배송비 목록',
    description: "Retrieve a supplier user's list of regional shipping fees.",
    scopeType: 'read',
    method: 'GET',
    path: 'suppliers/users/{user_id}/regionalshippingfees',
    requiredFields: ['user_id'],
    fields: {
      user_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'list',
  },
  {
    id: 'suppliers_users_regional_create',
    label: '사용자 지역별 배송비 등록',
    description: 'Create regional shipping fee for a supplier user. Body schema partial — refer to Cafe24 docs.',
    scopeType: 'write',
    method: 'POST',
    path: 'suppliers/users/{user_id}/regionalshippingfees',
    requiredFields: ['user_id'],
    fields: {
      user_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'suppliers_users_regional_delete',
    label: '사용자 지역별 배송비 삭제',
    description: "Delete supplier user's regional shipping fee settings.",
    scopeType: 'write',
    method: 'DELETE',
    path: 'suppliers/users/{user_id}/regionalshippingfees',
    requiredFields: ['user_id'],
    fields: {
      user_id: { type: 'string', location: 'path' },
    },
    responseShape: 'single',
  },
  {
    id: 'suppliers_users_regional_settings_get',
    label: '지역별 배송비 설정 조회',
    description: "Retrieve a supplier user's regional shipping fee settings.",
    scopeType: 'read',
    method: 'GET',
    path: 'suppliers/users/{user_id}/regionalshippingfees/settings',
    requiredFields: ['user_id'],
    fields: {
      user_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'suppliers_users_regional_settings_update',
    label: '지역별 배송비 설정 수정',
    description: "Update a supplier user's regional shipping fee settings (partial).",
    scopeType: 'write',
    method: 'PUT',
    path: 'suppliers/users/{user_id}/regionalshippingfees/settings',
    requiredFields: ['user_id'],
    fields: {
      user_id: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shipping_suppliers_get',
    label: '공급사 배송 설정 조회',
    description: "Retrieve a supplier's shipping settings.",
    scopeType: 'read',
    method: 'GET',
    path: 'shipping/suppliers/{supplier_code}',
    requiredFields: ['supplier_code'],
    fields: {
      supplier_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shipping_suppliers_update',
    label: '공급사 배송 설정 수정',
    description: "Update a supplier's shipping settings (partial).",
    scopeType: 'write',
    method: 'PUT',
    path: 'shipping/suppliers/{supplier_code}',
    requiredFields: ['supplier_code'],
    fields: {
      supplier_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'body', default: 1 },
    },
    responseShape: 'single',
  },
  {
    id: 'shipping_suppliers_additionalfees_get',
    label: '공급사 국제 배송 추가비 조회',
    description: 'Retrieve additional handling fees for supplier international shipping.',
    scopeType: 'read',
    method: 'GET',
    path: 'shipping/suppliers/{supplier_code}/additionalfees',
    requiredFields: ['supplier_code'],
    fields: {
      supplier_code: { type: 'string', location: 'path' },
      shop_no: { type: 'number', location: 'query', default: 1 },
    },
    responseShape: 'single',
  },
];
