apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: clemvion
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: clemvion
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 3011
      targetPort: http
      protocol: TCP
