apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: idea-workflow
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: idea-workflow
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
