apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clemvion

labels:
  - pairs:
      app.kubernetes.io/name: clemvion
      app.kubernetes.io/part-of: clemvion
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - migrate-job.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

images:
  - name: clemvion/backend
    newTag: latest
  - name: clemvion/frontend
    newTag: latest
  - name: clemvion/migrate
    newTag: latest
